export const TOPIC_TERMS = Object.freeze({
  "conflict": [
    "airstrike",
    "air strike",
    "missile",
    "drone attack",
    "rocket",
    "shelling",
    "offensive",
    "troops",
    "military operation",
    "mobilisation",
    "mobilization",
    "incursion",
    "warship",
    "fighter jet",
    "intercepted",
    "casualties",
    "ceasefire",
    "truce",
    "hostilities",
    "attack"
  ],
  "sanctions": [
    "sanction",
    "ofac",
    "asset freeze",
    "blacklist",
    "designated",
    "secondary sanctions",
    "export restriction",
    "entity list",
    "trade restriction",
    "embargo"
  ],
  "shipping": [
    "shipping",
    "vessel",
    "tanker",
    "container ship",
    "port closure",
    "port congestion",
    "canal",
    "strait",
    "red sea",
    "hormuz",
    "bab el-mandeb",
    "suez",
    "malacca",
    "blockade",
    "maritime",
    "freight",
    "war risk insurance"
  ],
  "energy": [
    "oil",
    "crude",
    "brent",
    "wti",
    "natural gas",
    "lng",
    "pipeline",
    "refinery",
    "opec",
    "production cut",
    "energy export",
    "power grid",
    "electricity",
    "nuclear plant"
  ],
  "macro": [
    "central bank",
    "interest rate",
    "rate cut",
    "rate hike",
    "inflation",
    "cpi",
    "gdp",
    "recession",
    "bond yield",
    "treasury yield",
    "currency intervention",
    "capital controls",
    "liquidity"
  ],
  "policy": [
    "tariff",
    "trade deal",
    "export control",
    "import ban",
    "industrial policy",
    "subsidy",
    "regulation",
    "executive order",
    "legislation",
    "tax",
    "procurement"
  ],
  "cyber": [
    "cyberattack",
    "cyber attack",
    "ransomware",
    "data breach",
    "critical infrastructure",
    "cisa",
    "zero-day",
    "zero day",
    "network outage",
    "telecom outage"
  ],
  "aviation": [
    "airspace",
    "flight suspension",
    "airport closure",
    "notam",
    "airline",
    "reroute",
    "aviation warning"
  ],
  "semiconductors": [
    "semiconductor",
    "chip",
    "foundry",
    "tsmc",
    "asml",
    "nvidia",
    "hbm",
    "advanced chip",
    "lithography",
    "rare earth",
    "gallium",
    "germanium"
  ],
  "politics": [
    "election",
    "government collapse",
    "coalition",
    "resignation",
    "parliament",
    "president",
    "prime minister",
    "coup",
    "emergency law",
    "martial law",
    "protest",
    "general strike"
  ],
  "nuclear": [
    "nuclear",
    "uranium",
    "enrichment",
    "centrifuge",
    "iaea",
    "reactor",
    "radiological"
  ],
  "financial-stability": [
    "bank run",
    "bank failure",
    "default",
    "sovereign debt",
    "debt restructuring",
    "capital controls",
    "currency crisis",
    "liquidity crisis",
    "payment system"
  ],
  "prediction": [
    "prediction market",
    "implied probability",
    "market odds"
  ],
  "humanitarian": [
    "evacuation",
    "refugee",
    "displacement",
    "humanitarian corridor",
    "food shortage",
    "water shortage"
  ],
  "natural-hazard": [
    "earthquake",
    "tsunami",
    "volcano",
    "hurricane",
    "typhoon",
    "flood",
    "wildfire"
  ]
});

export const CATEGORY_WEIGHTS = Object.freeze({
  "conflict": 1.15,
  "sanctions": 1.12,
  "shipping": 1.18,
  "energy": 1.15,
  "macro": 1.08,
  "policy": 1.06,
  "cyber": 1.12,
  "aviation": 1.08,
  "semiconductors": 1.12,
  "politics": 1.0,
  "nuclear": 1.2,
  "financial-stability": 1.2,
  "prediction": 0.9,
  "humanitarian": 0.86,
  "natural-hazard": 0.9,
  "other": 0.6
});
export function detectTopics(text){ const h=String(text||'').toLowerCase(); const hits=[]; for(const [topic,terms] of Object.entries(TOPIC_TERMS)){ const matched=terms.filter(term=>h.includes(term)); if(matched.length)hits.push({topic,matched}); } return hits.sort((a,b)=>b.matched.length-a.matched.length); }
