const deepLanguageCatalog = {
  "en": {
    languageName: "English",
    "safe": "SAFE [en]",
    "unsafe": "UNSAFE [en]",
    "caution": "CAUTION [en]",
    "avoid": "AVOID [en]",
    "unknown": "UNKNOWN [en]",
    "official_local": "OFFICIAL LOCAL [en]",
    "official_national": "OFFICIAL NATIONAL [en]",
    "live_event": "LIVE EVENT [en]",
    "estimate": "ESTIMATE [en]",
    "missing": "MISSING [en]",
    "source_failed": "SOURCE FAILED [en]",
    "hospital_access": "HOSPITAL ACCESS [en]",
    "police_access": "POLICE ACCESS [en]",
    "pharmacy_access": "PHARMACY ACCESS [en]",
    "airport_access": "AIRPORT ACCESS [en]",
    "border_access": "BORDER ACCESS [en]",
    "fuel_access": "FUEL ACCESS [en]",
    "port_access": "PORT ACCESS [en]",
    "rail_access": "RAIL ACCESS [en]",
    "main_road_access": "MAIN ROAD ACCESS [en]",
    "communications": "COMMUNICATIONS [en]",
    "water": "WATER [en]",
    "shelter": "SHELTER [en]",
    "food": "FOOD [en]",
    "power": "POWER [en]",
    "money": "MONEY [en]",
    "security": "SECURITY [en]",
    "politics": "POLITICS [en]",
    "crisis": "CRISIS [en]",
    "war": "WAR [en]",
    "terror": "TERROR [en]",
    "crime": "CRIME [en]",
    "burglary": "BURGLARY [en]",
    "active_attacker": "ACTIVE ATTACKER [en]",
    "travel_advisory": "TRAVEL ADVISORY [en]",
    "route_safety": "ROUTE SAFETY [en]",
    "family_zone": "FAMILY ZONE [en]",
    "business_site": "BUSINESS SITE [en]",
    "offline_pack": "OFFLINE PACK [en]",
    "what_changed_today": "WHAT CHANGED TODAY [en]",
    "nearest_help": "NEAREST HELP [en]",
    "what_to_check": "WHAT TO CHECK [en]",
    "source_confidence": "SOURCE CONFIDENCE [en]",
    featureLabels: {
      "radius_scan": "Radius Scan [en]",
      "country_watch": "Country Watch [en]",
      "city_watch": "City Watch [en]",
      "route_planner": "Route Planner [en]",
      "embassy_locator": "Embassy Locator [en]",
      "hospital_locator": "Hospital Locator [en]",
      "pharmacy_locator": "Pharmacy Locator [en]",
      "fuel_locator": "Fuel Locator [en]",
      "border_watch": "Border Watch [en]",
      "airport_watch": "Airport Watch [en]",
      "rail_watch": "Rail Watch [en]",
      "port_watch": "Port Watch [en]",
      "conflict_layer": "Conflict Layer [en]",
      "politics_layer": "Politics Layer [en]",
      "crime_layer": "Crime Layer [en]",
      "terror_layer": "Terror Layer [en]",
      "active_attacker_layer": "Active Attacker Layer [en]",
      "protest_layer": "Protest Layer [en]",
      "strike_layer": "Strike Layer [en]",
      "advisory_tracker": "Advisory Tracker [en]",
      "money_movement": "Money Movement [en]",
      "offline_pack": "Offline Pack [en]",
      "source_health": "Source Health [en]",
      "language_pack": "Language Pack [en]",
      "live_alerts": "Live Alerts [en]",
      "family_contact_zone": "Family Contact Zone [en]",
      "business_site_watch": "Business Site Watch [en]",
      "supply_route_watch": "Supply Route Watch [en]",
      "safe_arrival_plan": "Safe Arrival Plan [en]",
      "night_movement_risk": "Night Movement Risk [en]",
      "communications_status": "Communications Status [en]",
      "infrastructure_resilience": "Infrastructure Resilience [en]",
      "evacuation_support": "Evacuation Support [en]",
      "check_before_travel": "Check Before Travel [en]",
      "local_area_brief": "Local Area Brief [en]",
      "daily_security_digest": "Daily Security Digest [en]",
      "red_team_data_audit": "Red Team Data Audit [en]",
      "estimate_explainer": "Estimate Explainer [en]",
      "confidence_labels": "Confidence Labels [en]",
      "news_noise_filter": "News Noise Filter [en]",
      "country_timeline": "Country Timeline [en]",
      "city_timeline": "City Timeline [en]",
      "nearest_safe_point": "Nearest Safe Point [en]",
      "shelter_locator": "Shelter Locator [en]",
      "water_locator": "Water Locator [en]",
      "power_locator": "Power Locator [en]",
      "cash_access": "Cash Access [en]",
      "crypto_access": "Crypto Access [en]",
      "sanctions_watch": "Sanctions Watch [en]",
      "frontline_estimates": "Frontline Estimates [en]",
      "political_unrest_heatmap": "Political Unrest Heatmap [en]",
    }
  },
  "ar": {
    languageName: "Arabic",
    "safe": "SAFE [ar]",
    "unsafe": "UNSAFE [ar]",
    "caution": "CAUTION [ar]",
    "avoid": "AVOID [ar]",
    "unknown": "UNKNOWN [ar]",
    "official_local": "OFFICIAL LOCAL [ar]",
    "official_national": "OFFICIAL NATIONAL [ar]",
    "live_event": "LIVE EVENT [ar]",
    "estimate": "ESTIMATE [ar]",
    "missing": "MISSING [ar]",
    "source_failed": "SOURCE FAILED [ar]",
    "hospital_access": "HOSPITAL ACCESS [ar]",
    "police_access": "POLICE ACCESS [ar]",
    "pharmacy_access": "PHARMACY ACCESS [ar]",
    "airport_access": "AIRPORT ACCESS [ar]",
    "border_access": "BORDER ACCESS [ar]",
    "fuel_access": "FUEL ACCESS [ar]",
    "port_access": "PORT ACCESS [ar]",
    "rail_access": "RAIL ACCESS [ar]",
    "main_road_access": "MAIN ROAD ACCESS [ar]",
    "communications": "COMMUNICATIONS [ar]",
    "water": "WATER [ar]",
    "shelter": "SHELTER [ar]",
    "food": "FOOD [ar]",
    "power": "POWER [ar]",
    "money": "MONEY [ar]",
    "security": "SECURITY [ar]",
    "politics": "POLITICS [ar]",
    "crisis": "CRISIS [ar]",
    "war": "WAR [ar]",
    "terror": "TERROR [ar]",
    "crime": "CRIME [ar]",
    "burglary": "BURGLARY [ar]",
    "active_attacker": "ACTIVE ATTACKER [ar]",
    "travel_advisory": "TRAVEL ADVISORY [ar]",
    "route_safety": "ROUTE SAFETY [ar]",
    "family_zone": "FAMILY ZONE [ar]",
    "business_site": "BUSINESS SITE [ar]",
    "offline_pack": "OFFLINE PACK [ar]",
    "what_changed_today": "WHAT CHANGED TODAY [ar]",
    "nearest_help": "NEAREST HELP [ar]",
    "what_to_check": "WHAT TO CHECK [ar]",
    "source_confidence": "SOURCE CONFIDENCE [ar]",
    featureLabels: {
      "radius_scan": "Radius Scan [ar]",
      "country_watch": "Country Watch [ar]",
      "city_watch": "City Watch [ar]",
      "route_planner": "Route Planner [ar]",
      "embassy_locator": "Embassy Locator [ar]",
      "hospital_locator": "Hospital Locator [ar]",
      "pharmacy_locator": "Pharmacy Locator [ar]",
      "fuel_locator": "Fuel Locator [ar]",
      "border_watch": "Border Watch [ar]",
      "airport_watch": "Airport Watch [ar]",
      "rail_watch": "Rail Watch [ar]",
      "port_watch": "Port Watch [ar]",
      "conflict_layer": "Conflict Layer [ar]",
      "politics_layer": "Politics Layer [ar]",
      "crime_layer": "Crime Layer [ar]",
      "terror_layer": "Terror Layer [ar]",
      "active_attacker_layer": "Active Attacker Layer [ar]",
      "protest_layer": "Protest Layer [ar]",
      "strike_layer": "Strike Layer [ar]",
      "advisory_tracker": "Advisory Tracker [ar]",
      "money_movement": "Money Movement [ar]",
      "offline_pack": "Offline Pack [ar]",
      "source_health": "Source Health [ar]",
      "language_pack": "Language Pack [ar]",
      "live_alerts": "Live Alerts [ar]",
      "family_contact_zone": "Family Contact Zone [ar]",
      "business_site_watch": "Business Site Watch [ar]",
      "supply_route_watch": "Supply Route Watch [ar]",
      "safe_arrival_plan": "Safe Arrival Plan [ar]",
      "night_movement_risk": "Night Movement Risk [ar]",
      "communications_status": "Communications Status [ar]",
      "infrastructure_resilience": "Infrastructure Resilience [ar]",
      "evacuation_support": "Evacuation Support [ar]",
      "check_before_travel": "Check Before Travel [ar]",
      "local_area_brief": "Local Area Brief [ar]",
      "daily_security_digest": "Daily Security Digest [ar]",
      "red_team_data_audit": "Red Team Data Audit [ar]",
      "estimate_explainer": "Estimate Explainer [ar]",
      "confidence_labels": "Confidence Labels [ar]",
      "news_noise_filter": "News Noise Filter [ar]",
      "country_timeline": "Country Timeline [ar]",
      "city_timeline": "City Timeline [ar]",
      "nearest_safe_point": "Nearest Safe Point [ar]",
      "shelter_locator": "Shelter Locator [ar]",
      "water_locator": "Water Locator [ar]",
      "power_locator": "Power Locator [ar]",
      "cash_access": "Cash Access [ar]",
      "crypto_access": "Crypto Access [ar]",
      "sanctions_watch": "Sanctions Watch [ar]",
      "frontline_estimates": "Frontline Estimates [ar]",
      "political_unrest_heatmap": "Political Unrest Heatmap [ar]",
    }
  },
  "uk": {
    languageName: "Ukrainian",
    "safe": "SAFE [uk]",
    "unsafe": "UNSAFE [uk]",
    "caution": "CAUTION [uk]",
    "avoid": "AVOID [uk]",
    "unknown": "UNKNOWN [uk]",
    "official_local": "OFFICIAL LOCAL [uk]",
    "official_national": "OFFICIAL NATIONAL [uk]",
    "live_event": "LIVE EVENT [uk]",
    "estimate": "ESTIMATE [uk]",
    "missing": "MISSING [uk]",
    "source_failed": "SOURCE FAILED [uk]",
    "hospital_access": "HOSPITAL ACCESS [uk]",
    "police_access": "POLICE ACCESS [uk]",
    "pharmacy_access": "PHARMACY ACCESS [uk]",
    "airport_access": "AIRPORT ACCESS [uk]",
    "border_access": "BORDER ACCESS [uk]",
    "fuel_access": "FUEL ACCESS [uk]",
    "port_access": "PORT ACCESS [uk]",
    "rail_access": "RAIL ACCESS [uk]",
    "main_road_access": "MAIN ROAD ACCESS [uk]",
    "communications": "COMMUNICATIONS [uk]",
    "water": "WATER [uk]",
    "shelter": "SHELTER [uk]",
    "food": "FOOD [uk]",
    "power": "POWER [uk]",
    "money": "MONEY [uk]",
    "security": "SECURITY [uk]",
    "politics": "POLITICS [uk]",
    "crisis": "CRISIS [uk]",
    "war": "WAR [uk]",
    "terror": "TERROR [uk]",
    "crime": "CRIME [uk]",
    "burglary": "BURGLARY [uk]",
    "active_attacker": "ACTIVE ATTACKER [uk]",
    "travel_advisory": "TRAVEL ADVISORY [uk]",
    "route_safety": "ROUTE SAFETY [uk]",
    "family_zone": "FAMILY ZONE [uk]",
    "business_site": "BUSINESS SITE [uk]",
    "offline_pack": "OFFLINE PACK [uk]",
    "what_changed_today": "WHAT CHANGED TODAY [uk]",
    "nearest_help": "NEAREST HELP [uk]",
    "what_to_check": "WHAT TO CHECK [uk]",
    "source_confidence": "SOURCE CONFIDENCE [uk]",
    featureLabels: {
      "radius_scan": "Radius Scan [uk]",
      "country_watch": "Country Watch [uk]",
      "city_watch": "City Watch [uk]",
      "route_planner": "Route Planner [uk]",
      "embassy_locator": "Embassy Locator [uk]",
      "hospital_locator": "Hospital Locator [uk]",
      "pharmacy_locator": "Pharmacy Locator [uk]",
      "fuel_locator": "Fuel Locator [uk]",
      "border_watch": "Border Watch [uk]",
      "airport_watch": "Airport Watch [uk]",
      "rail_watch": "Rail Watch [uk]",
      "port_watch": "Port Watch [uk]",
      "conflict_layer": "Conflict Layer [uk]",
      "politics_layer": "Politics Layer [uk]",
      "crime_layer": "Crime Layer [uk]",
      "terror_layer": "Terror Layer [uk]",
      "active_attacker_layer": "Active Attacker Layer [uk]",
      "protest_layer": "Protest Layer [uk]",
      "strike_layer": "Strike Layer [uk]",
      "advisory_tracker": "Advisory Tracker [uk]",
      "money_movement": "Money Movement [uk]",
      "offline_pack": "Offline Pack [uk]",
      "source_health": "Source Health [uk]",
      "language_pack": "Language Pack [uk]",
      "live_alerts": "Live Alerts [uk]",
      "family_contact_zone": "Family Contact Zone [uk]",
      "business_site_watch": "Business Site Watch [uk]",
      "supply_route_watch": "Supply Route Watch [uk]",
      "safe_arrival_plan": "Safe Arrival Plan [uk]",
      "night_movement_risk": "Night Movement Risk [uk]",
      "communications_status": "Communications Status [uk]",
      "infrastructure_resilience": "Infrastructure Resilience [uk]",
      "evacuation_support": "Evacuation Support [uk]",
      "check_before_travel": "Check Before Travel [uk]",
      "local_area_brief": "Local Area Brief [uk]",
      "daily_security_digest": "Daily Security Digest [uk]",
      "red_team_data_audit": "Red Team Data Audit [uk]",
      "estimate_explainer": "Estimate Explainer [uk]",
      "confidence_labels": "Confidence Labels [uk]",
      "news_noise_filter": "News Noise Filter [uk]",
      "country_timeline": "Country Timeline [uk]",
      "city_timeline": "City Timeline [uk]",
      "nearest_safe_point": "Nearest Safe Point [uk]",
      "shelter_locator": "Shelter Locator [uk]",
      "water_locator": "Water Locator [uk]",
      "power_locator": "Power Locator [uk]",
      "cash_access": "Cash Access [uk]",
      "crypto_access": "Crypto Access [uk]",
      "sanctions_watch": "Sanctions Watch [uk]",
      "frontline_estimates": "Frontline Estimates [uk]",
      "political_unrest_heatmap": "Political Unrest Heatmap [uk]",
    }
  },
  "es": {
    languageName: "Spanish",
    "safe": "SAFE [es]",
    "unsafe": "UNSAFE [es]",
    "caution": "CAUTION [es]",
    "avoid": "AVOID [es]",
    "unknown": "UNKNOWN [es]",
    "official_local": "OFFICIAL LOCAL [es]",
    "official_national": "OFFICIAL NATIONAL [es]",
    "live_event": "LIVE EVENT [es]",
    "estimate": "ESTIMATE [es]",
    "missing": "MISSING [es]",
    "source_failed": "SOURCE FAILED [es]",
    "hospital_access": "HOSPITAL ACCESS [es]",
    "police_access": "POLICE ACCESS [es]",
    "pharmacy_access": "PHARMACY ACCESS [es]",
    "airport_access": "AIRPORT ACCESS [es]",
    "border_access": "BORDER ACCESS [es]",
    "fuel_access": "FUEL ACCESS [es]",
    "port_access": "PORT ACCESS [es]",
    "rail_access": "RAIL ACCESS [es]",
    "main_road_access": "MAIN ROAD ACCESS [es]",
    "communications": "COMMUNICATIONS [es]",
    "water": "WATER [es]",
    "shelter": "SHELTER [es]",
    "food": "FOOD [es]",
    "power": "POWER [es]",
    "money": "MONEY [es]",
    "security": "SECURITY [es]",
    "politics": "POLITICS [es]",
    "crisis": "CRISIS [es]",
    "war": "WAR [es]",
    "terror": "TERROR [es]",
    "crime": "CRIME [es]",
    "burglary": "BURGLARY [es]",
    "active_attacker": "ACTIVE ATTACKER [es]",
    "travel_advisory": "TRAVEL ADVISORY [es]",
    "route_safety": "ROUTE SAFETY [es]",
    "family_zone": "FAMILY ZONE [es]",
    "business_site": "BUSINESS SITE [es]",
    "offline_pack": "OFFLINE PACK [es]",
    "what_changed_today": "WHAT CHANGED TODAY [es]",
    "nearest_help": "NEAREST HELP [es]",
    "what_to_check": "WHAT TO CHECK [es]",
    "source_confidence": "SOURCE CONFIDENCE [es]",
    featureLabels: {
      "radius_scan": "Radius Scan [es]",
      "country_watch": "Country Watch [es]",
      "city_watch": "City Watch [es]",
      "route_planner": "Route Planner [es]",
      "embassy_locator": "Embassy Locator [es]",
      "hospital_locator": "Hospital Locator [es]",
      "pharmacy_locator": "Pharmacy Locator [es]",
      "fuel_locator": "Fuel Locator [es]",
      "border_watch": "Border Watch [es]",
      "airport_watch": "Airport Watch [es]",
      "rail_watch": "Rail Watch [es]",
      "port_watch": "Port Watch [es]",
      "conflict_layer": "Conflict Layer [es]",
      "politics_layer": "Politics Layer [es]",
      "crime_layer": "Crime Layer [es]",
      "terror_layer": "Terror Layer [es]",
      "active_attacker_layer": "Active Attacker Layer [es]",
      "protest_layer": "Protest Layer [es]",
      "strike_layer": "Strike Layer [es]",
      "advisory_tracker": "Advisory Tracker [es]",
      "money_movement": "Money Movement [es]",
      "offline_pack": "Offline Pack [es]",
      "source_health": "Source Health [es]",
      "language_pack": "Language Pack [es]",
      "live_alerts": "Live Alerts [es]",
      "family_contact_zone": "Family Contact Zone [es]",
      "business_site_watch": "Business Site Watch [es]",
      "supply_route_watch": "Supply Route Watch [es]",
      "safe_arrival_plan": "Safe Arrival Plan [es]",
      "night_movement_risk": "Night Movement Risk [es]",
      "communications_status": "Communications Status [es]",
      "infrastructure_resilience": "Infrastructure Resilience [es]",
      "evacuation_support": "Evacuation Support [es]",
      "check_before_travel": "Check Before Travel [es]",
      "local_area_brief": "Local Area Brief [es]",
      "daily_security_digest": "Daily Security Digest [es]",
      "red_team_data_audit": "Red Team Data Audit [es]",
      "estimate_explainer": "Estimate Explainer [es]",
      "confidence_labels": "Confidence Labels [es]",
      "news_noise_filter": "News Noise Filter [es]",
      "country_timeline": "Country Timeline [es]",
      "city_timeline": "City Timeline [es]",
      "nearest_safe_point": "Nearest Safe Point [es]",
      "shelter_locator": "Shelter Locator [es]",
      "water_locator": "Water Locator [es]",
      "power_locator": "Power Locator [es]",
      "cash_access": "Cash Access [es]",
      "crypto_access": "Crypto Access [es]",
      "sanctions_watch": "Sanctions Watch [es]",
      "frontline_estimates": "Frontline Estimates [es]",
      "political_unrest_heatmap": "Political Unrest Heatmap [es]",
    }
  },
  "ru": {
    languageName: "Russian",
    "safe": "SAFE [ru]",
    "unsafe": "UNSAFE [ru]",
    "caution": "CAUTION [ru]",
    "avoid": "AVOID [ru]",
    "unknown": "UNKNOWN [ru]",
    "official_local": "OFFICIAL LOCAL [ru]",
    "official_national": "OFFICIAL NATIONAL [ru]",
    "live_event": "LIVE EVENT [ru]",
    "estimate": "ESTIMATE [ru]",
    "missing": "MISSING [ru]",
    "source_failed": "SOURCE FAILED [ru]",
    "hospital_access": "HOSPITAL ACCESS [ru]",
    "police_access": "POLICE ACCESS [ru]",
    "pharmacy_access": "PHARMACY ACCESS [ru]",
    "airport_access": "AIRPORT ACCESS [ru]",
    "border_access": "BORDER ACCESS [ru]",
    "fuel_access": "FUEL ACCESS [ru]",
    "port_access": "PORT ACCESS [ru]",
    "rail_access": "RAIL ACCESS [ru]",
    "main_road_access": "MAIN ROAD ACCESS [ru]",
    "communications": "COMMUNICATIONS [ru]",
    "water": "WATER [ru]",
    "shelter": "SHELTER [ru]",
    "food": "FOOD [ru]",
    "power": "POWER [ru]",
    "money": "MONEY [ru]",
    "security": "SECURITY [ru]",
    "politics": "POLITICS [ru]",
    "crisis": "CRISIS [ru]",
    "war": "WAR [ru]",
    "terror": "TERROR [ru]",
    "crime": "CRIME [ru]",
    "burglary": "BURGLARY [ru]",
    "active_attacker": "ACTIVE ATTACKER [ru]",
    "travel_advisory": "TRAVEL ADVISORY [ru]",
    "route_safety": "ROUTE SAFETY [ru]",
    "family_zone": "FAMILY ZONE [ru]",
    "business_site": "BUSINESS SITE [ru]",
    "offline_pack": "OFFLINE PACK [ru]",
    "what_changed_today": "WHAT CHANGED TODAY [ru]",
    "nearest_help": "NEAREST HELP [ru]",
    "what_to_check": "WHAT TO CHECK [ru]",
    "source_confidence": "SOURCE CONFIDENCE [ru]",
    featureLabels: {
      "radius_scan": "Radius Scan [ru]",
      "country_watch": "Country Watch [ru]",
      "city_watch": "City Watch [ru]",
      "route_planner": "Route Planner [ru]",
      "embassy_locator": "Embassy Locator [ru]",
      "hospital_locator": "Hospital Locator [ru]",
      "pharmacy_locator": "Pharmacy Locator [ru]",
      "fuel_locator": "Fuel Locator [ru]",
      "border_watch": "Border Watch [ru]",
      "airport_watch": "Airport Watch [ru]",
      "rail_watch": "Rail Watch [ru]",
      "port_watch": "Port Watch [ru]",
      "conflict_layer": "Conflict Layer [ru]",
      "politics_layer": "Politics Layer [ru]",
      "crime_layer": "Crime Layer [ru]",
      "terror_layer": "Terror Layer [ru]",
      "active_attacker_layer": "Active Attacker Layer [ru]",
      "protest_layer": "Protest Layer [ru]",
      "strike_layer": "Strike Layer [ru]",
      "advisory_tracker": "Advisory Tracker [ru]",
      "money_movement": "Money Movement [ru]",
      "offline_pack": "Offline Pack [ru]",
      "source_health": "Source Health [ru]",
      "language_pack": "Language Pack [ru]",
      "live_alerts": "Live Alerts [ru]",
      "family_contact_zone": "Family Contact Zone [ru]",
      "business_site_watch": "Business Site Watch [ru]",
      "supply_route_watch": "Supply Route Watch [ru]",
      "safe_arrival_plan": "Safe Arrival Plan [ru]",
      "night_movement_risk": "Night Movement Risk [ru]",
      "communications_status": "Communications Status [ru]",
      "infrastructure_resilience": "Infrastructure Resilience [ru]",
      "evacuation_support": "Evacuation Support [ru]",
      "check_before_travel": "Check Before Travel [ru]",
      "local_area_brief": "Local Area Brief [ru]",
      "daily_security_digest": "Daily Security Digest [ru]",
      "red_team_data_audit": "Red Team Data Audit [ru]",
      "estimate_explainer": "Estimate Explainer [ru]",
      "confidence_labels": "Confidence Labels [ru]",
      "news_noise_filter": "News Noise Filter [ru]",
      "country_timeline": "Country Timeline [ru]",
      "city_timeline": "City Timeline [ru]",
      "nearest_safe_point": "Nearest Safe Point [ru]",
      "shelter_locator": "Shelter Locator [ru]",
      "water_locator": "Water Locator [ru]",
      "power_locator": "Power Locator [ru]",
      "cash_access": "Cash Access [ru]",
      "crypto_access": "Crypto Access [ru]",
      "sanctions_watch": "Sanctions Watch [ru]",
      "frontline_estimates": "Frontline Estimates [ru]",
      "political_unrest_heatmap": "Political Unrest Heatmap [ru]",
    }
  },
  "fa": {
    languageName: "Farsi",
    "safe": "SAFE [fa]",
    "unsafe": "UNSAFE [fa]",
    "caution": "CAUTION [fa]",
    "avoid": "AVOID [fa]",
    "unknown": "UNKNOWN [fa]",
    "official_local": "OFFICIAL LOCAL [fa]",
    "official_national": "OFFICIAL NATIONAL [fa]",
    "live_event": "LIVE EVENT [fa]",
    "estimate": "ESTIMATE [fa]",
    "missing": "MISSING [fa]",
    "source_failed": "SOURCE FAILED [fa]",
    "hospital_access": "HOSPITAL ACCESS [fa]",
    "police_access": "POLICE ACCESS [fa]",
    "pharmacy_access": "PHARMACY ACCESS [fa]",
    "airport_access": "AIRPORT ACCESS [fa]",
    "border_access": "BORDER ACCESS [fa]",
    "fuel_access": "FUEL ACCESS [fa]",
    "port_access": "PORT ACCESS [fa]",
    "rail_access": "RAIL ACCESS [fa]",
    "main_road_access": "MAIN ROAD ACCESS [fa]",
    "communications": "COMMUNICATIONS [fa]",
    "water": "WATER [fa]",
    "shelter": "SHELTER [fa]",
    "food": "FOOD [fa]",
    "power": "POWER [fa]",
    "money": "MONEY [fa]",
    "security": "SECURITY [fa]",
    "politics": "POLITICS [fa]",
    "crisis": "CRISIS [fa]",
    "war": "WAR [fa]",
    "terror": "TERROR [fa]",
    "crime": "CRIME [fa]",
    "burglary": "BURGLARY [fa]",
    "active_attacker": "ACTIVE ATTACKER [fa]",
    "travel_advisory": "TRAVEL ADVISORY [fa]",
    "route_safety": "ROUTE SAFETY [fa]",
    "family_zone": "FAMILY ZONE [fa]",
    "business_site": "BUSINESS SITE [fa]",
    "offline_pack": "OFFLINE PACK [fa]",
    "what_changed_today": "WHAT CHANGED TODAY [fa]",
    "nearest_help": "NEAREST HELP [fa]",
    "what_to_check": "WHAT TO CHECK [fa]",
    "source_confidence": "SOURCE CONFIDENCE [fa]",
    featureLabels: {
      "radius_scan": "Radius Scan [fa]",
      "country_watch": "Country Watch [fa]",
      "city_watch": "City Watch [fa]",
      "route_planner": "Route Planner [fa]",
      "embassy_locator": "Embassy Locator [fa]",
      "hospital_locator": "Hospital Locator [fa]",
      "pharmacy_locator": "Pharmacy Locator [fa]",
      "fuel_locator": "Fuel Locator [fa]",
      "border_watch": "Border Watch [fa]",
      "airport_watch": "Airport Watch [fa]",
      "rail_watch": "Rail Watch [fa]",
      "port_watch": "Port Watch [fa]",
      "conflict_layer": "Conflict Layer [fa]",
      "politics_layer": "Politics Layer [fa]",
      "crime_layer": "Crime Layer [fa]",
      "terror_layer": "Terror Layer [fa]",
      "active_attacker_layer": "Active Attacker Layer [fa]",
      "protest_layer": "Protest Layer [fa]",
      "strike_layer": "Strike Layer [fa]",
      "advisory_tracker": "Advisory Tracker [fa]",
      "money_movement": "Money Movement [fa]",
      "offline_pack": "Offline Pack [fa]",
      "source_health": "Source Health [fa]",
      "language_pack": "Language Pack [fa]",
      "live_alerts": "Live Alerts [fa]",
      "family_contact_zone": "Family Contact Zone [fa]",
      "business_site_watch": "Business Site Watch [fa]",
      "supply_route_watch": "Supply Route Watch [fa]",
      "safe_arrival_plan": "Safe Arrival Plan [fa]",
      "night_movement_risk": "Night Movement Risk [fa]",
      "communications_status": "Communications Status [fa]",
      "infrastructure_resilience": "Infrastructure Resilience [fa]",
      "evacuation_support": "Evacuation Support [fa]",
      "check_before_travel": "Check Before Travel [fa]",
      "local_area_brief": "Local Area Brief [fa]",
      "daily_security_digest": "Daily Security Digest [fa]",
      "red_team_data_audit": "Red Team Data Audit [fa]",
      "estimate_explainer": "Estimate Explainer [fa]",
      "confidence_labels": "Confidence Labels [fa]",
      "news_noise_filter": "News Noise Filter [fa]",
      "country_timeline": "Country Timeline [fa]",
      "city_timeline": "City Timeline [fa]",
      "nearest_safe_point": "Nearest Safe Point [fa]",
      "shelter_locator": "Shelter Locator [fa]",
      "water_locator": "Water Locator [fa]",
      "power_locator": "Power Locator [fa]",
      "cash_access": "Cash Access [fa]",
      "crypto_access": "Crypto Access [fa]",
      "sanctions_watch": "Sanctions Watch [fa]",
      "frontline_estimates": "Frontline Estimates [fa]",
      "political_unrest_heatmap": "Political Unrest Heatmap [fa]",
    }
  },
  "tr": {
    languageName: "Turkish",
    "safe": "SAFE [tr]",
    "unsafe": "UNSAFE [tr]",
    "caution": "CAUTION [tr]",
    "avoid": "AVOID [tr]",
    "unknown": "UNKNOWN [tr]",
    "official_local": "OFFICIAL LOCAL [tr]",
    "official_national": "OFFICIAL NATIONAL [tr]",
    "live_event": "LIVE EVENT [tr]",
    "estimate": "ESTIMATE [tr]",
    "missing": "MISSING [tr]",
    "source_failed": "SOURCE FAILED [tr]",
    "hospital_access": "HOSPITAL ACCESS [tr]",
    "police_access": "POLICE ACCESS [tr]",
    "pharmacy_access": "PHARMACY ACCESS [tr]",
    "airport_access": "AIRPORT ACCESS [tr]",
    "border_access": "BORDER ACCESS [tr]",
    "fuel_access": "FUEL ACCESS [tr]",
    "port_access": "PORT ACCESS [tr]",
    "rail_access": "RAIL ACCESS [tr]",
    "main_road_access": "MAIN ROAD ACCESS [tr]",
    "communications": "COMMUNICATIONS [tr]",
    "water": "WATER [tr]",
    "shelter": "SHELTER [tr]",
    "food": "FOOD [tr]",
    "power": "POWER [tr]",
    "money": "MONEY [tr]",
    "security": "SECURITY [tr]",
    "politics": "POLITICS [tr]",
    "crisis": "CRISIS [tr]",
    "war": "WAR [tr]",
    "terror": "TERROR [tr]",
    "crime": "CRIME [tr]",
    "burglary": "BURGLARY [tr]",
    "active_attacker": "ACTIVE ATTACKER [tr]",
    "travel_advisory": "TRAVEL ADVISORY [tr]",
    "route_safety": "ROUTE SAFETY [tr]",
    "family_zone": "FAMILY ZONE [tr]",
    "business_site": "BUSINESS SITE [tr]",
    "offline_pack": "OFFLINE PACK [tr]",
    "what_changed_today": "WHAT CHANGED TODAY [tr]",
    "nearest_help": "NEAREST HELP [tr]",
    "what_to_check": "WHAT TO CHECK [tr]",
    "source_confidence": "SOURCE CONFIDENCE [tr]",
    featureLabels: {
      "radius_scan": "Radius Scan [tr]",
      "country_watch": "Country Watch [tr]",
      "city_watch": "City Watch [tr]",
      "route_planner": "Route Planner [tr]",
      "embassy_locator": "Embassy Locator [tr]",
      "hospital_locator": "Hospital Locator [tr]",
      "pharmacy_locator": "Pharmacy Locator [tr]",
      "fuel_locator": "Fuel Locator [tr]",
      "border_watch": "Border Watch [tr]",
      "airport_watch": "Airport Watch [tr]",
      "rail_watch": "Rail Watch [tr]",
      "port_watch": "Port Watch [tr]",
      "conflict_layer": "Conflict Layer [tr]",
      "politics_layer": "Politics Layer [tr]",
      "crime_layer": "Crime Layer [tr]",
      "terror_layer": "Terror Layer [tr]",
      "active_attacker_layer": "Active Attacker Layer [tr]",
      "protest_layer": "Protest Layer [tr]",
      "strike_layer": "Strike Layer [tr]",
      "advisory_tracker": "Advisory Tracker [tr]",
      "money_movement": "Money Movement [tr]",
      "offline_pack": "Offline Pack [tr]",
      "source_health": "Source Health [tr]",
      "language_pack": "Language Pack [tr]",
      "live_alerts": "Live Alerts [tr]",
      "family_contact_zone": "Family Contact Zone [tr]",
      "business_site_watch": "Business Site Watch [tr]",
      "supply_route_watch": "Supply Route Watch [tr]",
      "safe_arrival_plan": "Safe Arrival Plan [tr]",
      "night_movement_risk": "Night Movement Risk [tr]",
      "communications_status": "Communications Status [tr]",
      "infrastructure_resilience": "Infrastructure Resilience [tr]",
      "evacuation_support": "Evacuation Support [tr]",
      "check_before_travel": "Check Before Travel [tr]",
      "local_area_brief": "Local Area Brief [tr]",
      "daily_security_digest": "Daily Security Digest [tr]",
      "red_team_data_audit": "Red Team Data Audit [tr]",
      "estimate_explainer": "Estimate Explainer [tr]",
      "confidence_labels": "Confidence Labels [tr]",
      "news_noise_filter": "News Noise Filter [tr]",
      "country_timeline": "Country Timeline [tr]",
      "city_timeline": "City Timeline [tr]",
      "nearest_safe_point": "Nearest Safe Point [tr]",
      "shelter_locator": "Shelter Locator [tr]",
      "water_locator": "Water Locator [tr]",
      "power_locator": "Power Locator [tr]",
      "cash_access": "Cash Access [tr]",
      "crypto_access": "Crypto Access [tr]",
      "sanctions_watch": "Sanctions Watch [tr]",
      "frontline_estimates": "Frontline Estimates [tr]",
      "political_unrest_heatmap": "Political Unrest Heatmap [tr]",
    }
  },
};
function getLang(code){ return deepLanguageCatalog[code] || deepLanguageCatalog.en; }
module.exports = { deepLanguageCatalog, getLang };