const featureRegistry = [
  {
    id: "radius_scan",
    title: "Radius Scan",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "country_watch",
    title: "Country Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "city_watch",
    title: "City Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "route_planner",
    title: "Route Planner",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "embassy_locator",
    title: "Embassy Locator",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "hospital_locator",
    title: "Hospital Locator",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "pharmacy_locator",
    title: "Pharmacy Locator",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "fuel_locator",
    title: "Fuel Locator",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "border_watch",
    title: "Border Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "airport_watch",
    title: "Airport Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "rail_watch",
    title: "Rail Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "port_watch",
    title: "Port Watch",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "conflict_layer",
    title: "Conflict Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "politics_layer",
    title: "Politics Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "crime_layer",
    title: "Crime Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "terror_layer",
    title: "Terror Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "active_attacker_layer",
    title: "Active Attacker Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "protest_layer",
    title: "Protest Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "strike_layer",
    title: "Strike Layer",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "advisory_tracker",
    title: "Advisory Tracker",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "money_movement",
    title: "Money Movement",
    stage: "live",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "offline_pack",
    title: "Offline Pack",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "source_health",
    title: "Source Health",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "language_pack",
    title: "Language Pack",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "live_alerts",
    title: "Live Alerts",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "family_contact_zone",
    title: "Family Contact Zone",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "business_site_watch",
    title: "Business Site Watch",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "supply_route_watch",
    title: "Supply Route Watch",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "safe_arrival_plan",
    title: "Safe Arrival Plan",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "night_movement_risk",
    title: "Night Movement Risk",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "communications_status",
    title: "Communications Status",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "infrastructure_resilience",
    title: "Infrastructure Resilience",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "evacuation_support",
    title: "Evacuation Support",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "check_before_travel",
    title: "Check Before Travel",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "local_area_brief",
    title: "Local Area Brief",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "daily_security_digest",
    title: "Daily Security Digest",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "red_team_data_audit",
    title: "Red Team Data Audit",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "estimate_explainer",
    title: "Estimate Explainer",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "confidence_labels",
    title: "Confidence Labels",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "news_noise_filter",
    title: "News Noise Filter",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "country_timeline",
    title: "Country Timeline",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "city_timeline",
    title: "City Timeline",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "nearest_safe_point",
    title: "Nearest Safe Point",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "shelter_locator",
    title: "Shelter Locator",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "water_locator",
    title: "Water Locator",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "power_locator",
    title: "Power Locator",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "cash_access",
    title: "Cash Access",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "crypto_access",
    title: "Crypto Access",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "sanctions_watch",
    title: "Sanctions Watch",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "frontline_estimates",
    title: "Frontline Estimates",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
  {
    id: "political_unrest_heatmap",
    title: "Political Unrest Heatmap",
    stage: "expanded",
    customerValue: [
      "reduces uncertainty",
      "turns raw events into a decision",
      "links map symbols to source-backed checks",
      "labels missing data clearly",
      "supports travel/security/business use",
    ],
    dataInputs: [
      "geocode",
      "events",
      "infrastructure",
      "weather",
      "advisory",
      "country_indicators",
      "source_health",
    ],
    failureModes: [
      "source timeout",
      "location ambiguity",
      "country-level only data",
      "public API rate limit",
      "unverified news signal",
    ],
    uiPrinciples: [
      "show verdict first",
      "show why next",
      "show map evidence",
      "show source status",
      "avoid fake precision",
    ]
  },
];
function listFeatures(){ return featureRegistry; }
module.exports = { featureRegistry, listFeatures };