const sourcePipelineRegistry = [
  {
    id: "SRC-001",
    name: "GDELT DOC",
    tier: "core",
    freshnessTargetMinutes: 5,
    dataLevel: "source-index",
    useFor: [
      "country_watch",
      "offline_pack",
      "conflict_layer",
      "country_timeline",
      "city_watch",
      "frontline_estimates",
      "money_movement",
      "advisory_tracker",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-002",
    name: "GDELT Events",
    tier: "core",
    freshnessTargetMinutes: 15,
    dataLevel: "source-index",
    useFor: [
      "hospital_locator",
      "city_watch",
      "pharmacy_locator",
      "fuel_locator",
      "city_timeline",
      "rail_watch",
      "confidence_labels",
      "business_site_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-003",
    name: "ReliefWeb",
    tier: "core",
    freshnessTargetMinutes: 1440,
    dataLevel: "country",
    useFor: [
      "city_timeline",
      "shelter_locator",
      "infrastructure_resilience",
      "sanctions_watch",
      "red_team_data_audit",
      "language_pack",
      "frontline_estimates",
      "embassy_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-004",
    name: "USGS Earthquakes",
    tier: "core",
    freshnessTargetMinutes: 30,
    dataLevel: "source-index",
    useFor: [
      "strike_layer",
      "crime_layer",
      "cash_access",
      "country_timeline",
      "active_attacker_layer",
      "border_watch",
      "politics_layer",
      "news_noise_filter",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-005",
    name: "GDACS",
    tier: "core",
    freshnessTargetMinutes: 5,
    dataLevel: "point",
    useFor: [
      "local_area_brief",
      "offline_pack",
      "strike_layer",
      "water_locator",
      "safe_arrival_plan",
      "sanctions_watch",
      "route_planner",
      "frontline_estimates",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-006",
    name: "NASA EONET",
    tier: "core",
    freshnessTargetMinutes: 60,
    dataLevel: "source-index",
    useFor: [
      "terror_layer",
      "nearest_safe_point",
      "border_watch",
      "active_attacker_layer",
      "city_timeline",
      "port_watch",
      "advisory_tracker",
      "daily_security_digest",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-007",
    name: "Open-Meteo",
    tier: "core",
    freshnessTargetMinutes: 60,
    dataLevel: "route",
    useFor: [
      "pharmacy_locator",
      "offline_pack",
      "confidence_labels",
      "power_locator",
      "source_health",
      "border_watch",
      "advisory_tracker",
      "city_timeline",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-008",
    name: "Nominatim",
    tier: "core",
    freshnessTargetMinutes: 10,
    dataLevel: "country",
    useFor: [
      "language_pack",
      "political_unrest_heatmap",
      "crime_layer",
      "city_timeline",
      "port_watch",
      "family_contact_zone",
      "red_team_data_audit",
      "power_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-009",
    name: "Overpass",
    tier: "core",
    freshnessTargetMinutes: 30,
    dataLevel: "point",
    useFor: [
      "route_planner",
      "protest_layer",
      "frontline_estimates",
      "money_movement",
      "check_before_travel",
      "confidence_labels",
      "strike_layer",
      "fuel_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-010",
    name: "Wikipedia",
    tier: "core",
    freshnessTargetMinutes: 5,
    dataLevel: "point",
    useFor: [
      "route_planner",
      "daily_security_digest",
      "politics_layer",
      "country_watch",
      "crime_layer",
      "frontline_estimates",
      "safe_arrival_plan",
      "check_before_travel",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-011",
    name: "Wikimedia Commons",
    tier: "core",
    freshnessTargetMinutes: 60,
    dataLevel: "country",
    useFor: [
      "hospital_locator",
      "active_attacker_layer",
      "crypto_access",
      "estimate_explainer",
      "port_watch",
      "embassy_locator",
      "business_site_watch",
      "supply_route_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-012",
    name: "World Bank",
    tier: "core",
    freshnessTargetMinutes: 15,
    dataLevel: "country",
    useFor: [
      "rail_watch",
      "shelter_locator",
      "sanctions_watch",
      "nearest_safe_point",
      "source_health",
      "supply_route_watch",
      "red_team_data_audit",
      "infrastructure_resilience",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-013",
    name: "data.police.uk",
    tier: "core",
    freshnessTargetMinutes: 180,
    dataLevel: "global",
    useFor: [
      "confidence_labels",
      "frontline_estimates",
      "offline_pack",
      "check_before_travel",
      "embassy_locator",
      "conflict_layer",
      "port_watch",
      "communications_status",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-014",
    name: "FCDO",
    tier: "core",
    freshnessTargetMinutes: 30,
    dataLevel: "point",
    useFor: [
      "rail_watch",
      "city_watch",
      "fuel_locator",
      "offline_pack",
      "strike_layer",
      "shelter_locator",
      "crime_layer",
      "radius_scan",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-015",
    name: "US State Dept",
    tier: "expanded",
    freshnessTargetMinutes: 30,
    dataLevel: "point",
    useFor: [
      "rail_watch",
      "family_contact_zone",
      "border_watch",
      "strike_layer",
      "money_movement",
      "estimate_explainer",
      "city_watch",
      "protest_layer",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-016",
    name: "Canada Travel",
    tier: "expanded",
    freshnessTargetMinutes: 15,
    dataLevel: "point",
    useFor: [
      "terror_layer",
      "city_timeline",
      "evacuation_support",
      "offline_pack",
      "confidence_labels",
      "communications_status",
      "border_watch",
      "family_contact_zone",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-017",
    name: "Australia Smartraveller",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "city",
    useFor: [
      "hospital_locator",
      "supply_route_watch",
      "sanctions_watch",
      "fuel_locator",
      "nearest_safe_point",
      "rail_watch",
      "strike_layer",
      "active_attacker_layer",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-018",
    name: "ECB",
    tier: "expanded",
    freshnessTargetMinutes: 5,
    dataLevel: "route",
    useFor: [
      "supply_route_watch",
      "cash_access",
      "hospital_locator",
      "conflict_layer",
      "political_unrest_heatmap",
      "embassy_locator",
      "port_watch",
      "news_noise_filter",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-019",
    name: "Binance",
    tier: "expanded",
    freshnessTargetMinutes: 10,
    dataLevel: "route",
    useFor: [
      "city_timeline",
      "politics_layer",
      "communications_status",
      "money_movement",
      "country_watch",
      "infrastructure_resilience",
      "crime_layer",
      "fuel_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-020",
    name: "CoinGecko",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "city",
    useFor: [
      "confidence_labels",
      "terror_layer",
      "shelter_locator",
      "protest_layer",
      "conflict_layer",
      "city_timeline",
      "language_pack",
      "source_health",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-021",
    name: "Yahoo Finance",
    tier: "expanded",
    freshnessTargetMinutes: 360,
    dataLevel: "global",
    useFor: [
      "rail_watch",
      "frontline_estimates",
      "country_timeline",
      "political_unrest_heatmap",
      "communications_status",
      "terror_layer",
      "strike_layer",
      "language_pack",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-022",
    name: "Stooq",
    tier: "expanded",
    freshnessTargetMinutes: 30,
    dataLevel: "city",
    useFor: [
      "port_watch",
      "family_contact_zone",
      "communications_status",
      "hospital_locator",
      "radius_scan",
      "fuel_locator",
      "water_locator",
      "night_movement_risk",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-023",
    name: "UN News",
    tier: "expanded",
    freshnessTargetMinutes: 15,
    dataLevel: "global",
    useFor: [
      "fuel_locator",
      "local_area_brief",
      "language_pack",
      "night_movement_risk",
      "city_timeline",
      "water_locator",
      "country_watch",
      "hospital_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-024",
    name: "Google News Travel Security",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "global",
    useFor: [
      "estimate_explainer",
      "politics_layer",
      "conflict_layer",
      "nearest_safe_point",
      "shelter_locator",
      "daily_security_digest",
      "border_watch",
      "source_health",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-025",
    name: "Google News Conflict",
    tier: "expanded",
    freshnessTargetMinutes: 15,
    dataLevel: "point",
    useFor: [
      "rail_watch",
      "radius_scan",
      "country_watch",
      "language_pack",
      "red_team_data_audit",
      "route_planner",
      "terror_layer",
      "live_alerts",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-026",
    name: "Google News Border Disruption",
    tier: "expanded",
    freshnessTargetMinutes: 15,
    dataLevel: "city",
    useFor: [
      "conflict_layer",
      "family_contact_zone",
      "crypto_access",
      "radius_scan",
      "country_watch",
      "terror_layer",
      "city_watch",
      "power_locator",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-027",
    name: "Google News Embassy",
    tier: "expanded",
    freshnessTargetMinutes: 10,
    dataLevel: "source-index",
    useFor: [
      "confidence_labels",
      "frontline_estimates",
      "city_timeline",
      "radius_scan",
      "news_noise_filter",
      "safe_arrival_plan",
      "embassy_locator",
      "supply_route_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-028",
    name: "Google News Active Attacker",
    tier: "expanded",
    freshnessTargetMinutes: 30,
    dataLevel: "global",
    useFor: [
      "active_attacker_layer",
      "infrastructure_resilience",
      "border_watch",
      "business_site_watch",
      "red_team_data_audit",
      "money_movement",
      "city_timeline",
      "country_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-029",
    name: "Google News Burglary Crime",
    tier: "expanded",
    freshnessTargetMinutes: 30,
    dataLevel: "point",
    useFor: [
      "estimate_explainer",
      "hospital_locator",
      "business_site_watch",
      "shelter_locator",
      "daily_security_digest",
      "money_movement",
      "airport_watch",
      "nearest_safe_point",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-030",
    name: "Google News Strike Protest",
    tier: "expanded",
    freshnessTargetMinutes: 15,
    dataLevel: "city",
    useFor: [
      "fuel_locator",
      "country_watch",
      "cash_access",
      "political_unrest_heatmap",
      "crime_layer",
      "city_watch",
      "conflict_layer",
      "supply_route_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-031",
    name: "Reuters RSS if connected",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "point",
    useFor: [
      "embassy_locator",
      "city_timeline",
      "shelter_locator",
      "politics_layer",
      "rail_watch",
      "estimate_explainer",
      "port_watch",
      "advisory_tracker",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-032",
    name: "AP RSS if connected",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "global",
    useFor: [
      "political_unrest_heatmap",
      "rail_watch",
      "money_movement",
      "radius_scan",
      "shelter_locator",
      "check_before_travel",
      "route_planner",
      "supply_route_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-033",
    name: "BBC World",
    tier: "expanded",
    freshnessTargetMinutes: 360,
    dataLevel: "country",
    useFor: [
      "live_alerts",
      "fuel_locator",
      "check_before_travel",
      "crime_layer",
      "power_locator",
      "city_timeline",
      "embassy_locator",
      "business_site_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-034",
    name: "Al Jazeera",
    tier: "expanded",
    freshnessTargetMinutes: 180,
    dataLevel: "global",
    useFor: [
      "hospital_locator",
      "airport_watch",
      "water_locator",
      "source_health",
      "night_movement_risk",
      "shelter_locator",
      "politics_layer",
      "red_team_data_audit",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-035",
    name: "France24",
    tier: "expanded",
    freshnessTargetMinutes: 30,
    dataLevel: "source-index",
    useFor: [
      "safe_arrival_plan",
      "offline_pack",
      "local_area_brief",
      "conflict_layer",
      "route_planner",
      "supply_route_watch",
      "embassy_locator",
      "family_contact_zone",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-036",
    name: "DW",
    tier: "expanded",
    freshnessTargetMinutes: 360,
    dataLevel: "source-index",
    useFor: [
      "active_attacker_layer",
      "country_watch",
      "live_alerts",
      "hospital_locator",
      "water_locator",
      "politics_layer",
      "shelter_locator",
      "terror_layer",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-037",
    name: "RFE/RL",
    tier: "expanded",
    freshnessTargetMinutes: 360,
    dataLevel: "route",
    useFor: [
      "family_contact_zone",
      "frontline_estimates",
      "advisory_tracker",
      "pharmacy_locator",
      "terror_layer",
      "daily_security_digest",
      "political_unrest_heatmap",
      "communications_status",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-038",
    name: "OSAC public items if connected",
    tier: "expanded",
    freshnessTargetMinutes: 10,
    dataLevel: "route",
    useFor: [
      "rail_watch",
      "news_noise_filter",
      "nearest_safe_point",
      "country_watch",
      "cash_access",
      "embassy_locator",
      "crime_layer",
      "politics_layer",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-039",
    name: "ACLED optional paid",
    tier: "expanded",
    freshnessTargetMinutes: 5,
    dataLevel: "city",
    useFor: [
      "port_watch",
      "strike_layer",
      "cash_access",
      "advisory_tracker",
      "country_watch",
      "supply_route_watch",
      "local_area_brief",
      "terror_layer",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-040",
    name: "HDX datasets optional",
    tier: "expanded",
    freshnessTargetMinutes: 1440,
    dataLevel: "source-index",
    useFor: [
      "city_watch",
      "country_watch",
      "shelter_locator",
      "city_timeline",
      "crypto_access",
      "port_watch",
      "protest_layer",
      "rail_watch",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
  {
    id: "SRC-041",
    name: "OpenSanctions optional",
    tier: "expanded",
    freshnessTargetMinutes: 60,
    dataLevel: "city",
    useFor: [
      "power_locator",
      "fuel_locator",
      "embassy_locator",
      "local_area_brief",
      "live_alerts",
      "frontline_estimates",
      "active_attacker_layer",
      "nearest_safe_point",
    ],
    customerWarnings: [
      "may be delayed",
      "may be country-level only",
      "requires de-duplication",
      "needs source confidence label",
      "must not create fake precision",
    ],
    healthChecks: [
      "last_success",
      "last_failure",
      "records_loaded",
      "median_latency",
      "rate_limit_status",
      "source_url",
      "used_by_features",
    ]
  },
];
function listSourcePipelines(){ return sourcePipelineRegistry; }
module.exports = { sourcePipelineRegistry, listSourcePipelines };