import test from 'node:test';import assert from 'node:assert/strict';
import { fixtureResults } from '../src/sources/fixture.js';import { runIntelligencePipeline } from '../src/intel/pipeline.js';import { sourceCatalog } from '../src/sources/registry.js';
function pipeline(){const f=fixtureResults();return runIntelligencePipeline({rawItems:f.items,markets:f.markets,predictions:f.predictions,sourceStatuses:sourceCatalog().map(s=>({id:s.id,name:s.name,status:'ok',kind:s.kind}))})}
test('fixture pipeline creates only material decision signals',()=>{const p=pipeline();assert.equal(p.metrics.rawItems,32);assert.ok(p.signals.length>=20);assert.ok(p.signals.every(s=>s.signalScore>=48))});
test('Middle East US-Iran fixture becomes a scored Hormuz-linked signal',()=>{const s=pipeline().signals.find(x=>/US military adjusts Gulf posture|Iran-linked shipping|Persian Gulf and Hormuz/.test(x.title));assert.ok(s);assert.ok(['Strait of Hormuz','Iran'].includes(s.location?.name));assert.ok(s.market.rules.length>=1)});
test('prediction market context links to US-Iran signal after canonical entity normalization',()=>{const s=pipeline().signals.find(x=>/US military adjusts Gulf posture|Iran-linked shipping|Persian Gulf and Hormuz/.test(x.title));assert.ok(s.predictions.length>=1);assert.equal(s.predictions[0].probability,.38)});
test('Taiwan signal geocodes correctly',()=>assert.equal(pipeline().signals.find(x=>x.title.startsWith('Taiwan')).location.name,'Taiwan'));
test('briefing promotes high priority current signals',()=>{const p=pipeline();assert.ok(p.briefing.critical.length>=1);assert.ok(p.briefing.headline.length>10)});
test('market context is carried through without inventing missing data',()=>{const p=pipeline();assert.equal(p.markets.length,10);assert.ok(p.markets.some(m=>m.symbol==='BRENT'))});
test('evidence and verification metadata is present',()=>{const s=pipeline().signals[0];assert.ok(s.evidence.length>=1);assert.ok(['A','B','C','D'].includes(s.evidenceGrade));assert.ok(Array.isArray(s.verification))});
