import test from 'node:test';import assert from 'node:assert/strict';
import { parseFeed } from '../src/core/xml.js';import { runGdelt, gdeltUrl } from '../src/sources/gdelt.js';import { runOfficialPage } from '../src/sources/official-page.js';import { runPolymarket } from '../src/sources/polymarket.js';

test('RSS parser handles RSS 2.0',()=>{const rows=parseFeed(`<rss><channel><item><title>Iran sanctions update</title><link>https://reuters.com/x</link><description>Summary</description><pubDate>Fri, 07 Aug 2026 10:00:00 GMT</pubDate></item></channel></rss>`);assert.equal(rows.length,1);assert.equal(rows[0].title,'Iran sanctions update')});
test('RSS parser handles Atom',()=>{const rows=parseFeed(`<feed><entry><title>ECB policy</title><link href="https://ecb.europa.eu/x"/><summary>Rates</summary><updated>2026-08-07T10:00:00Z</updated></entry></feed>`);assert.equal(rows[0].url,'https://ecb.europa.eu/x')});
test('GDELT URL requests article list JSON with a bounded record count',()=>{const u=new URL(gdeltUrl({query:'Iran sanctions'}));assert.equal(u.searchParams.get('mode'),'ArtList');assert.equal(u.searchParams.get('maxrecords'),'250')});
test('GDELT adapter filters tabloid results through source policy',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({articles:[{title:'Good',url:'https://reuters.com/world/x',seendate:'20260807T100000Z'},{title:'Noise',url:'https://thesun.co.uk/x',seendate:'20260807T100000Z'}]}),{status:200});try{const r=await runGdelt({id:'g',name:'G',query:'Iran',regionId:'middle-east'});assert.equal(r.items.length,1);assert.equal(r.items[0].sourceName,'Reuters')}finally{globalThis.fetch=old}});
test('official-page adapter extracts dated recent primary-source links',async()=>{const old=globalThis.fetch;const today=new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});globalThis.fetch=async()=>new Response(`<html><div>${today}<a href="/recent-actions/20260807">Iran-related Designations and General License</a></div></html>`,{status:200});try{const r=await runOfficialPage({id:'ofac',name:'OFAC',url:'https://ofac.treasury.gov/recent-actions',includePath:'/recent-actions/',quality:1});assert.equal(r.items.length,1);assert.equal(r.items[0].sourceMode,'primary-claim')}finally{globalThis.fetch=old}});
test('Polymarket adapter reads yes probability but ignores tiny markets',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify([{id:'1',title:'Will event happen?',slug:'event',volume:50000,liquidity:10000,markets:[{outcomes:'["Yes","No"]',outcomePrices:'["0.62","0.38"]',volume:50000}]}]),{status:200});try{const r=await runPolymarket({id:'pm',name:'Polymarket',url:'https://gamma-api.polymarket.com/events'});assert.equal(r.predictions.length,1);assert.equal(r.predictions[0].probability,.62)}finally{globalThis.fetch=old}});
