const ruleBook = [
  { id:'red-sea-shipping', name:'Suez / Red Sea route risk', themes:['shipping','oil','war','freight'], assets:['BRENT','WTI','GOLD','IYT','ITA','LMT'], trigger:'Route disruption appears and oil/shipping/insurance assets react in the same direction.', action:'Check Brent, WTI, freight headlines and shipping names. Ignore it if oil and freight do not move.', verify:['Brent or WTI rising on the same refresh','shipping/freight source confirms rerouting or insurance pressure','related shipping/defence asset is not weak'], risk:'high' },
  { id:'ai-power-grid', name:'AI power / grid constraint', themes:['ai-power','grid','copper','data-centres','tech'], assets:['VRT','PWR','ETN','COPPER','URA'], trigger:'AI/data-centre power demand appears while grid, cooling, copper or uranium proxies are rising.', action:'Check grid equipment, cooling, copper and uranium names. Ignore vague AI headlines.', verify:['VRT/PWR/ETN trend positive','Copper not falling','headline mentions power, cooling, grid, transformers or capacity'], risk:'medium' },
  { id:'defence-capex', name:'Defence budget / procurement', themes:['defence','war','security','government-capex'], assets:['LMT','RTX','ITA','GOLD'], trigger:'Security risk is paired with actual procurement, budget or equipment demand language.', action:'Check defence ETF/primes and gold. Ignore fear-only headlines with no budget effect.', verify:['LMT/RTX/ITA green vs market','procurement or budget language present','market is not selling everything indiscriminately'], risk:'medium' },
  { id:'copper-electrification', name:'Copper / electrification pressure', themes:['copper','grid','construction','ai-power'], assets:['COPPER','PWR','ETN','VRT'], trigger:'Copper strength appears together with grid/data-centre/infrastructure pressure.', action:'Check copper plus grid equipment names. Ignore if dollar/rates are crushing metals.', verify:['Copper trend positive','dollar/rates not overwhelming metals','grid or infrastructure news active'], risk:'medium' },
  { id:'oil-energy-risk', name:'Oil supply route risk', themes:['oil','energy','iran','war','shipping'], assets:['BRENT','WTI','XLE','GOLD'], trigger:'Supply-route risk appears and oil futures react.', action:'Check Brent/WTI and energy ETF. Ignore if the event is not supply-route relevant.', verify:['Brent or WTI green','XLE not weak','event touches supply, sanctions, tankers or chokepoints'], risk:'high' },
  { id:'prediction-market-misalignment', name:'Prediction-market odds move', themes:['election','fed','rate','crypto','war','weather'], assets:['BTC','GOLD','TLT','QQQ'], trigger:'High-volume Polymarket odds move before related liquid assets fully react.', action:'Use event odds as an early warning, then check liquid assets. Do not trade odds alone.', verify:['Polymarket volume/liquidity high','odds moved materially','related asset confirms'], risk:'high' },
  { id:'disaster-rebuild', name:'Disaster rebuild / insurance pressure', themes:['earthquake','hurricane','flood','wildfire','disaster'], assets:['XLE','insurance','PWR','building materials'], trigger:'Large disaster appears near infrastructure, ports, energy assets or dense property markets.', action:'Check insurers, utilities, builders, energy and local government response.', verify:['fresh disaster source within current day','infrastructure/property damage likely','related sector starts moving'], risk:'medium' }
];
module.exports = { ruleBook };
