(async function(){
const $=id=>document.getElementById(id);
MoneyMap.init(); MoneyMap.legend();
$('panelClose').onclick=()=>$('panel').style.display='none';
async function load(){const [s,m]=await Promise.all([API.state(),API.mapData()]);window.APP_STATE=s;window.MAP_DATA=m;MoneyMap.setData(m,s);Renderers.liveBrief(s.liveBrief);} 
try{await load();}catch(e){Renderers.panel('Load failed',`<div class="card"><h3>Backend failed</h3><p>${e.message}</p></div>`)}
document.querySelectorAll('#tabs button[data-tab]').forEach(btn=>btn.onclick=async()=>{const tab=btn.dataset.tab;const s=window.APP_STATE||await API.state();if(tab==='live')Renderers.liveBrief(s.liveBrief);else if(tab==='family')Renderers.family(await API.family());else if(tab==='money')Renderers.markets(await API.markets());else if(tab==='sources')Renderers.sources(await API.sources());else if(tab==='crisis')Renderers.crisis(s);else if(tab==='travel')Renderers.travel(s);else if(tab==='europe')Renderers.panel('Europe',`<div class="card"><h3>Europe-first security view</h3><p class="plain">Click European places for local UK crime where available, national indicators, movement disruption, protest/terror/conflict/crisis signals and infrastructure.</p></div><div class="list">${(s.countryRisk||[]).filter(r=>String(r.region).includes('Europe')).sort((a,b)=>b.risk-a.risk).map(r=>`<div class="item ${r.risk>=55?'red':r.risk>=25?'orange':''}"><b>${r.country}</b> risk ${r.risk} | war ${r.war} | terror ${r.terror} | crisis ${r.crisis}</div>`).join('')}</div>`);else if(tab==='middleeast')Renderers.panel('Middle East / Syria',`<div class="card"><h3>Middle East and Syria watch</h3><p class="plain">Prioritised for family safety, travel risk and live conflict/humanitarian signals.</p></div><div class="list">${(s.countryRisk||[]).filter(r=>String(r.region).includes('Middle East')).sort((a,b)=>b.risk-a.risk).map(r=>`<div class="item ${r.risk>=55?'red':r.risk>=25?'orange':''}"><b>${r.country}</b> risk ${r.risk} | war ${r.war} | terror ${r.terror} | crisis ${r.crisis}</div>`).join('')}</div>`);else if(tab==='risk')Renderers.panel('Country Risk',`<div class="card"><h3>Country risk ranking</h3><p class="plain">Country-level. Not town crime.</p></div><div class="list">${(s.countryRisk||[]).sort((a,b)=>b.risk-a.risk).map(r=>`<div class="item ${r.risk>=55?'red':r.risk>=25?'orange':''}"><b>${r.country}</b> risk ${r.risk}<br><span class="muted">war ${r.war} | terror ${r.terror} | politics ${r.politics} | crisis ${r.crisis} | movement ${r.movement}</span></div>`).join('')}</div>`);});
$('searchBtn').onclick=async()=>{const q=$('searchBox').value.trim();if(!q)return;const data=await API.search(q);if(data.places&&data.places[0]){const p=data.places[0];window.map.setView([p.lat,p.lng],9);MoneyMap.openPlace(p.lat,p.lng);}else Renderers.panel('Search',`<div class="card"><h3>No place found</h3></div>`)};
const ev=new EventSource('/api/stream');ev.onmessage=msg=>{try{const p=JSON.parse(msg.data);if(p.state){window.APP_STATE=p.state;API.mapData().then(m=>{window.MAP_DATA=m;MoneyMap.setData(m,p.state);});}}catch{}};
})();
