(function(){
  let map, baseLayer, topoLayer, countryLayer, conflictLayer, eventLayer, cityLayer, infraLayer, scanLayer, routeLayer, selectedLayer;
  let state = {}, mapData = {}, countryGeo = null, dotsOn = true, topoOn = false, politicsOn = false, legendCollapsed = false, currentLang = {};
  const COLORS = { war:'#ff174f', terror:'#ff8c00', crime:'#ff3b7a', crisis:'#ffffff', politics:'#b24cff', movement:'#00d8ff', money:'#ffd94a', city:'#7aa7ff', earthquake:'#ffffff', infra:'#00eaff', route:'#00ff87' };
  const SYMBOLS = { earthquake:'⌁', politics:'⚑', movement:'↔', money:'£', crime:'🛡', hospital:'🏥', clinic:'⚕', pharmacy:'✚', police_station:'★', embassy_consulate:'⚐', airport_airfield:'✈', fuel_station:'⛽', border_crossing:'⇄', port_harbour:'⚓', rail_station:'▣', main_road:'═', communications:'📡', water_point:'💧', shelter:'⌂', food_supply:'▤', power_infrastructure:'⚡' };
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const valid = (lat,lng) => Number.isFinite(Number(lat)) && Number.isFinite(Number(lng)) && Math.abs(Number(lat)) <= 90 && Math.abs(Number(lng)) <= 180;
  function init(){
    if(map) return;
    injectCss();
    map = L.map('map', { preferCanvas:true, minZoom:2, maxZoom:18, zoomControl:true, worldCopyJump:true, zoomSnap:0.25 }).setView([20,12],2.75);
    window.map = map;
    baseLayer = L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { subdomains:'abcd', attribution:'&copy; OpenStreetMap &copy; CARTO', keepBuffer:4, updateWhenIdle:false, maxNativeZoom:19 }).addTo(map);
    topoLayer = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', { subdomains:'abc', opacity:0.85, attribution:'OpenTopoMap', keepBuffer:3 });
    countryLayer=L.layerGroup().addTo(map); conflictLayer=L.layerGroup().addTo(map); eventLayer=L.layerGroup().addTo(map); cityLayer=L.layerGroup().addTo(map); infraLayer=L.layerGroup().addTo(map); scanLayer=L.layerGroup().addTo(map); routeLayer=L.layerGroup().addTo(map); selectedLayer=L.layerGroup().addTo(map);
    map.on('click', e => openPlace(e.latlng.lat, e.latlng.lng));
    map.on('zoomend moveend', () => { renderCities(); renderVisibleInfrastructure(); });
    bind(); loadBoundaries(); legend();
    setTimeout(()=>map.invalidateSize(),250); setTimeout(()=>map.invalidateSize(),1200);
  }
  function bind(){
    if($('homeBtn')) $('homeBtn').onclick = () => { closePanel(); selectedLayer.clearLayers(); scanLayer.clearLayers(); routeLayer.clearLayers(); map.setView([20,12],2.75); };
    if($('dotBtn')) $('dotBtn').onclick = () => { dotsOn=!dotsOn; $('dotBtn').textContent = dotsOn?'DOTS ON':'DOTS OFF'; renderEvents(); renderCities(); renderVisibleInfrastructure(); };
    if($('topoBtn')) $('topoBtn').onclick = () => { topoOn=!topoOn; if(topoOn){ map.removeLayer(baseLayer); topoLayer.addTo(map); document.body.classList.add('topo-on'); } else { map.removeLayer(topoLayer); baseLayer.addTo(map); document.body.classList.remove('topo-on'); } };
    if($('politicsOverlayBtn')) $('politicsOverlayBtn').onclick = () => { politicsOn=!politicsOn; $('politicsOverlayBtn').classList.toggle('active',politicsOn); renderCountries(); };
    if($('overlayBtn')) $('overlayBtn').onclick = () => Renderers.overlayHelp();
    if($('refreshBtn')) $('refreshBtn').onclick = async () => { Renderers.miniLoading('Refreshing'); const r=await API.refresh(); const md=await API.mapData(); setData(md,r.state||r); };
  }
  async function loadBoundaries(){ try{ countryGeo = await API.json('/api/boundaries/admin0'); renderCountries(); } catch(e){ console.warn('boundaries failed', e.message); } }
  function setLanguage(t){ currentLang=t||{}; legend(); }
  function setData(md, st){ mapData=md||{}; state=st||{}; renderCountries(); renderConflictZones(); renderEvents(); renderCities(); renderVisibleInfrastructure(); renderTicker(); legend(); }
  function renderTicker(){ const ticker=$('ticker'); if(!ticker) return; const rows=(state.markets||[]).filter(m=>Number.isFinite(Number(m.changePct))).slice(0,9); ticker.innerHTML = rows.length ? rows.map(m=>`<span class="${Number(m.changePct)>=0?'up':'down'}">${esc(m.id||m.symbol)} ${Number(m.changePct)>=0?'▲':'▼'} ${Math.abs(Number(m.changePct)).toFixed(2)}%</span>`).join(' ') : '<span>No live market data</span>'; }
  function countryName(f){ const p=f.properties||{}; return p.ADMIN||p.NAME_EN||p.name||p.NAME||''; }
  function riskFor(name){ const n=String(name||'').toLowerCase(); return (state.countryRisk||mapData.countryRisk||[]).find(r=>{ const c=String(r.country||'').toLowerCase(); return c && (c===n || c.includes(n) || n.includes(c)); }); }
  function renderCountries(){ if(!countryGeo||!countryLayer) return; countryLayer.clearLayers(); L.geoJSON(countryGeo,{ style:f=>{ const r=riskFor(countryName(f)); let fill='#0b4f3a', op=.025, line='#0ba77d', w=.45, lop=.15; if(r && r.overlayWar){ fill='#5a0013'; op=.44; line='#ff174f'; w=1.2; lop=.8; } else if(politicsOn && r && ((r.politics||0)>0 || (r.movement||0)>0)){ fill='#4e148f'; op=.32; line='#b24cff'; w=1; lop=.65; } return {color:line, weight:w, opacity:lop, fillColor:fill, fillOpacity:op, className:'country-fill'}; }, onEachFeature:(f,l)=>l.on('click',ev=>{ L.DomEvent.stopPropagation(ev); const r=riskFor(countryName(f)); if(politicsOn && r && Renderers.politicsOverlayCard) Renderers.politicsOverlayCard(r); else openPlace(ev.latlng.lat, ev.latlng.lng); }) }).addTo(countryLayer); }
  function renderConflictZones(){ if(!conflictLayer) return; conflictLayer.clearLayers(); (mapData.conflictZones||[]).forEach(z=>{ let layer=null; if(Array.isArray(z.polygon)) layer=L.polygon(z.polygon,{color:'#ff174f',weight:2,fillColor:'#5a0013',fillOpacity:.38}); else if(valid(z.lat,z.lng)) layer=L.circle([+z.lat,+z.lng],{radius:(Number(z.radiusKm)||50)*1000,color:'#ff174f',weight:2,fillColor:'#5a0013',fillOpacity:.25}); if(!layer) return; layer.on('click',ev=>{L.DomEvent.stopPropagation(ev); Renderers.conflictCard(z);}); layer.addTo(conflictLayer); }); }
  function eventKind(e){ if(e.subtype==='earthquake') return 'earthquake'; return String(e.kind||'security').toLowerCase(); }
  function iconFor(type){ const t=String(type||'security'); if(SYMBOLS[t]) return L.divIcon({className:'',html:`<div class="map-symbol sym-${esc(t)}" data-symbol="${esc(t)}">${esc(SYMBOLS[t])}</div>`,iconSize:[18,18],iconAnchor:[9,9]}); const c=COLORS[t]||COLORS.infra; return L.divIcon({className:'',html:`<div class="dot dot-${esc(t)}" data-symbol="${esc(t)}" style="background:${c};box-shadow:0 0 8px ${c}"></div>`,iconSize:[8,8],iconAnchor:[4,4]}); }
  function renderEvents(){ eventLayer.clearLayers(); if(!dotsOn) return; (state.events||[]).filter(e=>e.displayOnMap!==false).forEach(e=>{ if(!valid(e.lat,e.lng)) return; if(e.subtype==='earthquake' && Number(e.magnitude||0)<5) return; const k=eventKind(e); const m=L.marker([+e.lat,+e.lng],{icon:iconFor(k)}).on('click',ev=>{L.DomEvent.stopPropagation(ev); Renderers.eventCard(e);}).addTo(eventLayer); m._smeType=k; }); }
  function renderCities(){ cityLayer.clearLayers(); if(!dotsOn || map.getZoom()<7) return; const b=map.getBounds(); (mapData.cityNodes||[]).filter(c=>valid(c.lat,c.lng)&&b.pad(.25).contains([c.lat,c.lng])).slice(0,260).forEach(c=>{ const m=L.marker([c.lat,c.lng],{icon:iconFor('city')}).on('click',ev=>{L.DomEvent.stopPropagation(ev); openPlace(c.lat,c.lng);}).addTo(cityLayer); m._smeType='city'; }); }
  let infraTimer=null, lastInfraKey=''; function renderVisibleInfrastructure(){ clearTimeout(infraTimer); infraTimer=setTimeout(async()=>{ if(!dotsOn || map.getZoom()<13){ infraLayer.clearLayers(); return; } const c=map.getCenter(); const key=`${c.lat.toFixed(2)},${c.lng.toFixed(2)},${Math.floor(map.getZoom())}`; if(key===lastInfraKey) return; lastInfraKey=key; try{ const data=await API.json(`/api/infrastructure/radius?lat=${c.lat}&lng=${c.lng}&km=3`); infraLayer.clearLayers(); (data.items||[]).slice(0,180).forEach(item=>{ if(!valid(item.lat,item.lng)) return; const type=item.type||item.kind||'infra'; const m=L.marker([item.lat,item.lng],{icon:iconFor(type)}).on('click',ev=>{L.DomEvent.stopPropagation(ev); Renderers.infrastructureCard(item);}).addTo(infraLayer); m._smeType=type; }); }catch(e){} },400); }
  async function openPlace(lat,lng){ selectedLayer.clearLayers(); L.circleMarker([lat,lng],{radius:6,color:'#00eaff',weight:2,fillColor:'#00eaff',fillOpacity:.24}).addTo(selectedLayer); Renderers.miniLoading('Loading place'); try{ const data=await API.place(lat,lng); Renderers.placeCard(data); } catch(e){ Renderers.panel('Place failed',`<div class="card"><h3>Place failed</h3><p>${esc(e.message)}</p></div>`); } }
  function drawAreaScan(result){ scanLayer.clearLayers(); routeLayer.clearLayers(); if(!result || !result.target || !valid(result.target.lat,result.target.lng)) return; const t=result.target, radius=Number(result.radiusMiles||5)*1609.344; map.setView([t.lat,t.lng], Math.max(map.getZoom(), 12)); L.circle([t.lat,t.lng],{radius,color:'#00eaff',weight:3,fillColor:'#00eaff',fillOpacity:.13}).addTo(scanLayer); L.marker([t.lat,t.lng],{icon:iconFor('city')}).addTo(scanLayer); (result.infrastructure && result.infrastructure.items || []).slice(0,250).forEach(item=>{ if(!valid(item.lat,item.lng)) return; const type=item.type||item.kind||'infra'; const m=L.marker([item.lat,item.lng],{icon:iconFor(type)}).on('click',ev=>{L.DomEvent.stopPropagation(ev); Renderers.infrastructureCard(item);}).addTo(scanLayer); m._smeType=type; }); }
  function drawRoute(result){ routeLayer.clearLayers(); if(!result || !result.route || !Array.isArray(result.route.mapLine) || result.route.mapLine.length<2) return; const line=L.polyline(result.route.mapLine,{color:'#00ff87',weight:4,opacity:.88,dashArray:'8 8'}).addTo(routeLayer); map.fitBounds(line.getBounds().pad(.35)); }
  function liveAlert(e){ if(!e) return; const toast=$('toast'); if(!toast) return; toast.innerHTML=`<button class="toast-close">×</button><div class="a-title">LIVE ALERT</div><div class="a-meta">${esc(e.title||e.summary||'New signal')}</div><button id="alertOpen">OPEN ON MAP</button>`; toast.classList.add('show'); toast.querySelector('.toast-close').onclick=()=>toast.classList.remove('show'); toast.querySelector('#alertOpen').onclick=()=>{ if(valid(e.lat,e.lng)) map.setView([+e.lat,+e.lng],9); Renderers.eventCard(e); }; setTimeout(()=>toast.classList.remove('show'),18000); }
  function legend(){ const el=$('legend'); if(!el) return; const rows=[['terror','terror'],['earthquake','earthquake'],['crisis','crisis'],['politics','politics'],['movement','movement'],['money','money'],['city','city'],['hospital','hospital'],['clinic','clinic'],['pharmacy','pharmacy'],['police','police_station'],['embassy','embassy_consulate'],['airport','airport_airfield'],['fuel','fuel_station'],['border','border_crossing'],['port','port_harbour'],['rail','rail_station'],['main road','main_road'],['comms','communications'],['water','water_point'],['shelter','shelter'],['food','food_supply'],['power','power_infrastructure']]; el.innerHTML=`<button id="legendToggle">${legendCollapsed?'KEY':'MINIMISE'}</button><div class="legendRows" style="display:${legendCollapsed?'none':'flex'}">${rows.map(([label,type])=>`<button class="legend-chip" data-type="${esc(type)}"><span class="legend-sample">${SYMBOLS[type]?esc(SYMBOLS[type]):'●'}</span>${esc(label)}</button>`).join('')}</div>`; $('legendToggle').onclick=()=>{legendCollapsed=!legendCollapsed; legend();}; el.querySelectorAll('[data-type]').forEach(btn=>btn.onclick=()=>highlight(btn.dataset.type)); }
  function highlight(type){ document.querySelectorAll('.map-symbol,.dot').forEach(x=>x.classList.toggle('symbol-muted', x.dataset.symbol!==type)); }
  function closePanel(){ const p=$('panel'); if(p) p.classList.remove('open'); }
  function injectCss(){ if(document.getElementById('map-v7-css')) return; const st=document.createElement('style'); st.id='map-v7-css'; st.textContent=`#map{background:#062b43!important}.leaflet-container{background:#062b43!important}.topo-on .leaflet-tile-pane{filter:brightness(.64) contrast(1.18) saturate(.92)!important}.leaflet-tile-pane{filter:brightness(.82) contrast(1.12) saturate(1.08)!important}.country-fill{mix-blend-mode:screen}.dot{width:8px;height:8px;border:1px solid #fff;border-radius:50%}.map-symbol{min-width:17px;height:17px;border-radius:4px;border:1px solid #00eaff;background:#002b3a;color:#eaffff;font-size:11px;display:flex;align-items:center;justify-content:center;box-shadow:0 0 7px #00eaff}.symbol-muted{opacity:.18!important;filter:grayscale(1)}.toast-close{float:right}.leaflet-control-zoom{margin-top:12px!important}`; document.head.appendChild(st); }
  window.MoneyMap={init,setData,setLanguage,drawAreaScan,drawRoute,liveAlert,legend};
})();
