(function(){
let map, countryLayer, conflictLayer, eventLayer, cityLayer, selectedLayer, areaScanLayer, countryGeo;
let state={}, mapData={}, langText={dotsOn:'DOTS ON',dotsOff:'DOTS OFF'};
const overlays={war:true,crisis:false,watch:false};
let dotsOn=true;
const colors={war:'#ff174f',terror:'#ff8c00',crisis:'#ffffff',politics:'#b24cff',movement:'#00d8ff',money:'#ffd94a',security:'#3ea0ff',city:'#7aa7ff'};
const featureSymbols={movement:'↔',money:'£',security:'!',politics:'⚑'};
function $(id){return document.getElementById(id);} 
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function init(){map=L.map('map',{preferCanvas:true,minZoom:2,maxZoom:16,zoomControl:true,worldCopyJump:false,maxBounds:[[-85,-180],[85,180]],maxBoundsViscosity:1}).setView([34,16],3);window.map=map;L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',attribution:'&copy; OpenStreetMap &copy; CARTO',noWrap:true,bounds:[[-85,-180],[85,180]]}).addTo(map);countryLayer=L.layerGroup().addTo(map);conflictLayer=L.layerGroup().addTo(map);eventLayer=L.layerGroup().addTo(map);cityLayer=L.layerGroup().addTo(map);selectedLayer=L.layerGroup().addTo(map);areaScanLayer=L.layerGroup().addTo(map);bind();loadBoundaries();map.on('click',e=>openPlace(e.latlng.lat,e.latlng.lng));map.on('zoomend moveend',renderCities);setTimeout(()=>map.invalidateSize(),300);}
function bind(){const h=$('homeBtn');if(h)h.onclick=()=>map.setView([34,16],3); const d=$('dotBtn'); if(d)d.onclick=()=>{dotsOn=!dotsOn;d.textContent=dotsOn?(langText.dotsOn||'DOTS ON'):(langText.dotsOff||'DOTS OFF');renderEvents();renderCities();}; const o=$('overlayBtn'); if(o)o.onclick=overlayPanel; const r=$('refreshBtn'); if(r)r.onclick=async()=>{Renderers.panel('Refreshing',`<div class="card"><h3>Refreshing sources</h3><div class="loader"><span></span></div></div>`);await API.refresh();const [s,m]=await Promise.all([API.state(),API.mapData()]);setData(m,s);Renderers.liveBrief(s.liveBrief);};}
function setLanguage(t){langText=t||langText;const d=$('dotBtn');if(d)d.textContent=dotsOn?(langText.dotsOn||'DOTS ON'):(langText.dotsOff||'DOTS OFF');}
async function loadBoundaries(){try{countryGeo=await API.json('/api/boundaries/admin0');renderCountries();}catch(e){console.warn(e)}}
function setData(md,st){mapData=md||{};state=st||{};renderCountries();renderConflictZones();renderEvents();renderCities();renderTicker();}
function cName(f){const p=f.properties||{};return p.ADMIN||p.NAME_EN||p.name||p.NAME||'';}
function cRisk(name){const n=String(name||'').toLowerCase();return (state.countryRisk||mapData.countryRisk||[]).find(r=>{const c=String(r.country||'').toLowerCase();return c&&(n===c||n.includes(c)||c.includes(n));});}
function renderCountries(){if(!countryGeo||!countryLayer)return;countryLayer.clearLayers();L.geoJSON(countryGeo,{style:f=>{const name=cName(f),r=cRisk(name);let fill='#00a66a',op=.012,line=.08,w=.5;if(overlays.war&&r&&r.overlayWar){fill='#ff174f';op=.38;line=.76;w=1.2}else if(overlays.crisis&&r&&r.crisis>3){fill='#ff8c00';op=.16;line=.38;w=.8}else if(overlays.watch&&r&&r.watch){fill='#ffd94a';op=.14;line=.42;w=.8}return{color:fill,weight:w,opacity:line,fillColor:fill,fillOpacity:op,className:'country-fill'}},onEachFeature:(f,l)=>l.on('click',e=>{L.DomEvent.stopPropagation(e);openPlace(e.latlng.lat,e.latlng.lng);})}).addTo(countryLayer)}

function renderConflictZones(){
  if(!conflictLayer)return;
  conflictLayer.clearLayers();
  if(!overlays.war)return;
  (mapData.conflictZones||[]).forEach(z=>{
    if(!Number.isFinite(+z.lat)||!Number.isFinite(+z.lng))return;
    L.circle([+z.lat,+z.lng],{radius:(+z.radiusKm||50)*1000,color:'#7d001b',fillColor:'#7d001b',fillOpacity:.34,weight:2,className:'conflict-zone'})
      .on('click',ev=>{L.DomEvent.stopPropagation(ev);Renderers.panel('Estimated conflict zone',`<div class="card"><h3>${esc(z.name||'Conflict zone')}</h3><div class="list"><div class="item"><b>Type:</b> estimated active conflict/security area</div><div class="item"><b>Country:</b> ${esc(z.country||'mapped')}</div><div class="item"><b>Use:</b> public-source warning layer for travellers and people in/near active conflict zones. It is not a verified military frontline.</div><div class="item yellow"><b>Check:</b> local contacts, official advice and live reports before movement.</div></div></div>`);})
      .addTo(conflictLayer);
  });
}

function eventKind(input){const k=String(input||'security').toLowerCase();if(k==='earthquake'||k==='quake')return'earthquake';if(['weather','disaster'].includes(k))return'crisis';return k;}
function icon(kind,subtype){const k=subtype==='earthquake'?'earthquake':eventKind(kind);if(k==='earthquake')return L.divIcon({className:'',html:`<div class="dot earthquake">⌁</div>`,iconSize:[16,16],iconAnchor:[8,8]});if(featureSymbols[k])return L.divIcon({className:'',html:`<div class="map-symbol" style="background:${colors[k]||colors.security};box-shadow:0 0 9px ${colors[k]||colors.security}">${esc(featureSymbols[k])}</div>`,iconSize:[16,16],iconAnchor:[8,8]});const col=colors[k]||colors.security;return L.divIcon({className:'',html:`<div class="dot" style="background:${col};box-shadow:0 0 9px ${col}"></div>`,iconSize:[9,9],iconAnchor:[4,4]});}
function renderEvents(){eventLayer.clearLayers();if(!dotsOn)return;(state.events||[]).filter(e=>e.displayOnMap!==false).forEach(e=>{if(!Number.isFinite(+e.lat)||!Number.isFinite(+e.lng))return;if(e.subtype==='earthquake'&&Number(e.magnitude||0)<5)return;L.marker([+e.lat,+e.lng],{icon:icon(e.kind,e.subtype)}).on('click',ev=>{L.DomEvent.stopPropagation(ev);Renderers.eventCard(e)}).addTo(eventLayer);});}
function renderCities(){cityLayer.clearLayers();if(!dotsOn||map.getZoom()<6)return;const b=map.getBounds();(mapData.cityNodes||[]).filter(c=>b.pad(.25).contains([c.lat,c.lng])).slice(0,260).forEach(c=>L.marker([c.lat,c.lng],{icon:icon('city')}).on('click',ev=>{L.DomEvent.stopPropagation(ev);openPlace(c.lat,c.lng)}).addTo(cityLayer));}
async function openPlace(lat,lng){selectedLayer.clearLayers();L.circleMarker([lat,lng],{radius:6,color:'#00eaff',weight:2,fillOpacity:.25}).addTo(selectedLayer);Renderers.panel('Loading place',`<div class="card"><h3>Checking this place</h3><div class="loader"><span></span></div><p class="plain">Loading exact place, country context, infrastructure, weather, live signals and image.</p></div>`);try{const data=await API.place(lat,lng);Renderers.placeCard(data)}catch(e){Renderers.panel('Place failed',`<div class="card"><h3>Place data failed</h3><p class="plain">${esc(e.message)}</p></div>`)}}
function overlayPanel(){Renderers.panel('Map overlays',`<div class="panel-subhead">War overlay starts on. Crisis and watch layers start off.</div><div class="card"><div class="list"><label class="item"><input id="ovWar" type="checkbox" ${overlays.war?'checked':''}> War / active conflict country colour</label><label class="item"><input id="ovCrisis" type="checkbox" ${overlays.crisis?'checked':''}> Crisis / disaster country colour</label><label class="item"><input id="ovWatch" type="checkbox" ${overlays.watch?'checked':''}> Watchlist country colour</label><div class="item yellow"><b>Rule:</b> red is only for active conflict countries or strict war events. General warnings do not make a country red.</div></div></div>`);$('ovWar').onchange=e=>{overlays.war=e.target.checked;renderCountries();renderConflictZones();renderConflictZones();};$('ovCrisis').onchange=e=>{overlays.crisis=e.target.checked;renderCountries();};$('ovWatch').onchange=e=>{overlays.watch=e.target.checked;renderCountries();};}
function drawAreaScan(scan){areaScanLayer.clearLayers();if(!scan||!scan.target)return;const lat=+scan.target.lat,lng=+scan.target.lng,km=+scan.radiusKm||8.04672;map.setView([lat,lng],Math.max(map.getZoom(),12));L.circle([lat,lng],{radius:km*1000,color:'#00eaff',fillColor:'#00eaff',fillOpacity:.15,weight:3,className:'area-scan-circle'}).addTo(areaScanLayer);L.marker([lat,lng],{icon:icon('city')}).addTo(areaScanLayer);(scan.infrastructure&&scan.infrastructure.items||[]).slice(0,80).forEach(item=>{if(!Number.isFinite(+item.lat)||!Number.isFinite(+item.lng))return;L.marker([+item.lat,+item.lng],{icon:infraIcon(item.type)}).on('click',ev=>{L.DomEvent.stopPropagation(ev);Renderers.panel(item.name||'Infrastructure',`<div class="card"><h3>${esc(item.name||item.type)}</h3><div class="list"><div class="item"><b>Type:</b> ${esc((item.type||'').replace(/_/g,' '))}</div><div class="item"><b>Distance:</b> ${Number(item.distanceMiles||0).toFixed(2)} miles</div><div class="item"><b>Source:</b> OpenStreetMap/Overpass</div></div></div>`)}).addTo(areaScanLayer);});(scan.insideEvents||[]).slice(0,60).forEach(e=>{if(!Number.isFinite(+e.lat)||!Number.isFinite(+e.lng))return;L.marker([+e.lat,+e.lng],{icon:icon(e.kind,e.subtype)}).on('click',ev=>{L.DomEvent.stopPropagation(ev);Renderers.eventCard(e)}).addTo(areaScanLayer);});}
function infraIcon(type){const iconMap={hospital:'🏥',clinic:'⚕',pharmacy:'✚',police_station:'★',embassy_consulate:'⚑',airport_airfield:'✈',fuel_station:'⛽',border_crossing:'⇄',port_harbour:'⚓',rail_station:'▣',main_road:'═'};return L.divIcon({className:'',html:`<div class="feature-marker">${iconMap[type]||'•'}</div>`,iconSize:[18,18],iconAnchor:[9,9]});}
function renderTicker(){const el=$('ticker');if(!el)return;const rows=(state.markets||[]).filter(m=>Number.isFinite(Number(m.changePct))).slice(0,8);el.innerHTML=rows.map(m=>{const ch=Number(m.changePct);const cls=ch>0?'up':ch<0?'down':'flat';const arrow=ch>0?'▲':ch<0?'▼':'•';return `<span class="tick ${cls}">${esc(m.id||m.name)} ${arrow} ${ch.toFixed(2)}%</span>`;}).join('')||'No live market data';}
function legend(){const el=$('legend');if(!el)return;const rows=[['dark red area','conflict'],['war dot',colors.war],['terror',colors.terror],['earthquake','symbol'],['crisis',colors.crisis],['politics',colors.politics],['movement',colors.movement],['money',colors.money],['city',colors.city]];el.innerHTML=rows.map(([name,col])=>col==='symbol'?`<span><b style="font-size:15px">⌁</b>${name}</span>`:col==='conflict'?`<span><i style="background:#7d001b;border:1px solid #ff174f"></i>${name}</span>`:`<span><i style="background:${col}"></i>${name}</span>`).join('');}
window.MoneyMap={init,setData,legend,drawAreaScan,setLanguage};
})();
