(function(){
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function panel(title,html){$('panel').style.display='block';$('panelTitle').textContent=title||'Info';$('panelBody').innerHTML=html||'';}
function cls(v,reverse=false){if(v===null||v===undefined||Number.isNaN(Number(v)))return'grey';const n=Number(v);if(reverse){if(n>=70)return'red';if(n>=40)return'orange';if(n>0)return'yellow';return'green';}if(n>=75)return'green';if(n>=55)return'yellow';if(n>=35)return'orange';return'red';}
function verdictClass(v){const s=String(v||'').toUpperCase();if(s==='SAFE'||s==='GO')return'green';if(s==='CAUTION')return'yellow';if(s==='HIGH RISK')return'orange';if(s==='AVOID')return'red';return'grey';}
function tile(label,value,small,reverse=false){const shown=value===null||value===undefined||Number.isNaN(Number(value))?'N/A':Math.round(Number(value));return`<div class="tile ${cls(value,reverse)}"><div class="label">${esc(label)}</div><div class="num">${shown}</div><div class="muted">${esc(small||'')}</div></div>`;}
function sourceTag(level){return`<span class="source-tag">${esc(level||'source')}</span>`;}
function labelType(type){return String(type||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function weather(w){if(!w||!w.current)return'N/A';const c=w.current;return `${esc(c.temperatureC??'N/A')}°C, wind ${esc(c.windKmh??'N/A')} km/h, gust ${esc(c.gustKmh??'N/A')} km/h, rain ${esc(c.precipitationMm??c.rainMm??'N/A')} mm`;}
function distance(item){if(!item)return'';return `${Number(item.distanceMiles||0).toFixed(1)} mi / ${Number(item.distanceKm||0).toFixed(1)} km`;}
function eventItem(e){return`<div class="item ${e.kind==='war'||e.kind==='terror'?'red':e.kind==='crisis'?'orange':''}"><b>${esc(e.title||'Live signal')}</b><br><span class="muted">${esc(e.kind||'signal')} | ${esc(e.place||e.country||'mapped place')} | ${e.distanceKm!==undefined?esc(`${Number(e.distanceKm).toFixed(1)} km | `):''}${esc(e.source||e.sourceSystem||'source')}</span>${e.url?`<br><a target="_blank" rel="noopener" href="${esc(e.url)}">open source</a>`:''}</div>`;}
function eventCard(e){panel(e.title||'Live signal',`<div class="card"><h3>${esc(e.title||'Live signal')}</h3><div class="list"><div class="item"><b>Type:</b> ${esc(e.kind||'signal')}</div><div class="item"><b>Place:</b> ${esc(e.place||e.country||'mapped place')}</div><div class="item"><b>Source:</b> ${esc(e.source||e.sourceSystem||'source')}</div><div class="item"><b>Meaning:</b> ${esc(e.summary||e.title||'No summary loaded')}</div>${e.url?`<div class="item"><a target="_blank" rel="noopener" href="${esc(e.url)}">open source</a></div>`:''}</div></div>`);}
function wikiBlock(wiki){return wiki&&wiki.found?`<div class="card"><h3>${esc(wiki.title)}</h3>${wiki.thumbnail?`<img class="wiki-img" src="${esc(wiki.thumbnail)}" alt="${esc(wiki.title)}">`:''}<p class="plain">${esc((wiki.extract||'').slice(0,420))}</p><a target="_blank" rel="noopener" href="${esc(wiki.url)}">Wikipedia source</a></div>`:`<div class="card"><h3>Wikipedia image</h3><p class="plain">No sourced Wikipedia image found for this exact place.</p></div>`;}
function placeName(data){const p=data.place||{},r=p.raw||{};return [r.neighbourhood,r.suburb,p.name,p.city,p.county,p.state,p.country].filter(Boolean).filter((x,i,a)=>a.findIndex(y=>String(y).toLowerCase()===String(x).toLowerCase())===i).join(', ')||p.displayName||'Selected place';}
function indicator(row){if(!row||row.value===null||row.value===undefined)return'N/A';return `${Number(row.value).toFixed(2)} (${esc(row.year||'latest')})`;}
function placeCard(data){const p=data.place||{},c=data.country||{},r=data.risk||{},i=data.infrastructure||{},wiki=data.wiki||{},events=data.nearbyEvents||[],ind=data.indicators||{};
 if(data.isOcean||(!p.country&&!c.name&&!data.country)){panel('Ocean',`<div class="card"><h3>${esc(data.oceanName||'Ocean / sea area')}</h3><p class="plain">This point is not land. Country safety, local crime and travel advice are not shown for ocean clicks.</p></div>`);return;}
 const name=placeName(data);
 panel('Place intelligence',`<div class="card"><h3>${esc(name)}</h3><p class="plain"><b>Verdict:</b> <span class="${cls(r.safety&&r.safety.value)}">${esc(r.verdict||'UNKNOWN')}</span></p><div class="grid">${tile('Safety',r.safety&&r.safety.value,r.safety&&r.safety.label)}${tile('Crime',r.crime&&r.crime.value,r.crime&&r.crime.dataLevel)}${tile('War',r.war&&r.war.value,r.war&&r.war.label,true)}${tile('Terror',r.terror&&r.terror.value,r.terror&&r.terror.label,true)}${tile('Politics',r.politics&&r.politics.value,r.politics&&r.politics.label,true)}${tile('Crisis',r.crisis&&r.crisis.value,r.crisis&&r.crisis.label,true)}</div></div>
 <div class="card"><h3>Local vs national</h3><div class="list"><div class="item"><b>Local crime:</b> ${data.localCrime&&data.localCrime.available?esc(`${data.localCrime.total} official local records`):'No official local crime feed for this exact area'} ${sourceTag(data.localCrime&&data.localCrime.available?'LOCAL':'MISSING')}</div><div class="item"><b>National homicide:</b> ${indicator(ind.homicide)} ${sourceTag('NATIONAL')}</div><div class="item"><b>Political stability:</b> ${indicator(ind.politicalStability)} ${sourceTag('NATIONAL')}</div><div class="item"><b>Infrastructure nearby:</b> ${Object.entries(i.counts||{}).slice(0,12).map(([k,v])=>`${esc(labelType(k))} ${esc(v)}`).join(' | ')||'none loaded'} ${sourceTag('OSM')}</div><div class="item"><b>Weather now:</b> ${weather(data.weather)} ${sourceTag('LOCAL COORDINATE')}</div></div></div>
 ${wikiBlock(wiki)}
 <div class="card"><h3>Nearby live signals</h3><div class="list">${events.length?events.slice(0,10).map(eventItem).join(''):`<div class="item">No nearby live signals loaded.</div>`}</div></div>
 <div class="card"><h3>Data quality</h3><div class="list">${(data.dataRules||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join('')}</div></div>`);}
function areaScanForm(){panel('Area Scan',`<div class="card"><h3>Radius Security Scan</h3><p class="plain">Type a street, neighbourhood, town, border crossing, airport or city. The top search uses this same scan.</p><div class="scan-form"><label>Street / area / town</label><input id="areaScanQuery" placeholder="Old City Damascus or Countess Wear Exeter"><label>Radius in miles</label><input id="areaScanRadius" type="number" min="0.5" max="50" step="0.5" value="5"><button id="areaScanRun">SCAN AREA</button></div></div><div class="card"><h3>What this checks</h3><div class="list"><div class="item">SAFE / CAUTION / AVOID / UNKNOWN verdict</div><div class="item">Hospitals, clinics, pharmacies, police, embassies, airports, fuel, borders, ports, rail and main roads</div><div class="item">Live war, terror, crisis, politics and movement signals in and around the radius</div><div class="item">Local crime only where an official local feed exists; estimated values are labelled.</div></div></div>`);}
function infraRow(row){const item=row.item;if(!item)return`<div class="item"><b>${esc(labelType(row.type))}</b>: none found in radius</div>`;return`<div class="item"><b>${esc(labelType(row.type))}</b>: ${esc(item.name||labelType(row.type))}<br><span class="muted">${esc(distance(item))} away | ${esc(item.source||'OSM')}</span></div>`;}
function metricTiles(m){if(!m)return'';return `<div class="card"><h3>Radius estimates</h3><p class="plain">These are estimated from loaded public sources. They are not fake exact measurements.</p><div class="grid">${tile('Safety est.',m.safetyEstimate,'EST: events + crime + infra')}${tile('Security risk',m.securityRisk,'EST: events/advisory/weather',true)}${tile('Medical access',m.medicalAccess,'OSM hospitals/clinics')}${tile('Police access',m.policeAccess,'OSM police')}${tile('Transport',m.transportAccess,'OSM roads/rail/air/port')}${tile('Infra access',m.infrastructureAccess,'OSM all key infra')}</div><div class="list"><div class="item"><b>Basis:</b> ${(m.dataBasis||[]).map(esc).join(' | ')||'limited data loaded'}</div></div></div>`;}
function areaScanResult(scan){if(!scan||scan.ok===false){panel('Area Scan',`<div class="card"><h3>No result</h3><p class="plain">${esc(scan&&scan.error||'No place found')}</p></div>`);return;}
 if(scan.isOcean){panel('Area Scan',`<div class="card"><h3>Ocean / no land result</h3><p class="plain">${esc(scan.verdict&&scan.verdict.reasons&&scan.verdict.reasons[0]||'This did not resolve to a land place.')}</p></div>`);return;}
 const v=scan.verdict||{},target=scan.target||{},place=scan.place||{},country=scan.country||{},localCrime=scan.localCrime||{},infra=scan.infrastructureSummary||{},nearest=infra.nearest||[],inside=scan.insideEvents||[],near=scan.nearEvents||[],ind=scan.indicators||{};
 const title=place.displayName||target.displayName||target.name||scan.query;
 panel('Area Scan',`<div class="card area-verdict"><h3>${esc(title)}</h3><p class="plain"><b>Radius:</b> ${esc(scan.radiusMiles)} miles</p><div class="verdict ${verdictClass(v.verdict)}">${esc(v.verdict||'UNKNOWN')}</div><p class="plain"><b>Danger:</b> ${v.danger===null||v.danger===undefined?'N/A':esc(v.danger+'/100')} | <b>Coverage:</b> ${esc(v.confidence||'unknown')}</p></div>
 ${metricTiles(scan.areaMetrics)}
 <div class="card"><h3>Why</h3><div class="list">${(v.reasons||[]).map(x=>`<div class="item">${esc(x)}</div>`).join('')||'<div class="item">No reason loaded.</div>'}</div></div>
 <div class="card"><h3>What to check before moving</h3><div class="list">${(v.actions||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join('')}</div></div>
 <div class="card"><h3>Emergency infrastructure inside radius</h3><div class="list">${nearest.map(infraRow).join('')}</div></div>
 <div class="card"><h3>Local crime / country context</h3><div class="list"><div class="item"><b>Country:</b> ${esc(country.name||place.country||'N/A')}</div><div class="item"><b>Local crime:</b> ${localCrime.available?esc(`${localCrime.total} official police records from ${localCrime.samplePoints||1} sample point(s), ${localCrime.date||'latest'}`):'No official local crime feed connected here'} ${sourceTag(localCrime.available?'LOCAL':'MISSING')}</div><div class="item"><b>National homicide:</b> ${indicator(ind.homicide)} ${sourceTag('NATIONAL')}</div><div class="item"><b>Political stability:</b> ${indicator(ind.politicalStability)} ${sourceTag('NATIONAL')}</div><div class="item"><b>Weather:</b> ${weather(scan.weather)} ${sourceTag('LOCAL COORDINATE')}</div><div class="item"><b>Travel advice:</b> ${esc(scan.advisory&&scan.advisory.level||'No official advisory loaded')} ${sourceTag(scan.advisory&&scan.advisory.available?'OFFICIAL':'MISSING')}</div></div></div>
 ${wikiBlock(scan.wiki)}
 <div class="card"><h3>Live signals inside the circle</h3><div class="list">${inside.length?inside.slice(0,15).map(eventItem).join(''):'<div class="item">No live security/crisis event loaded inside the radius.</div>'}</div></div>
 <div class="card"><h3>Nearby signals outside circle</h3><div class="list">${near.length?near.slice(0,12).map(eventItem).join(''):'<div class="item">No nearby outside-radius signals loaded.</div>'}</div></div>
 <div class="card"><h3>Data quality</h3><div class="list">${(scan.dataRules||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join('')}</div></div>`);}
function liveBrief(data){const alerts=(data&&data.keyAlerts||[]);const worse=(data&&data.countriesWorse||[]);panel('Live Brief',`<div class="card"><h3>${esc(data&&data.headline||'Live Brief')}</h3><p class="plain">Filtered for travel/security use. Junk items and low-severity noise are removed.</p></div><div class="card"><h3>Top matters now</h3><div class="list">${alerts.length?alerts.slice(0,12).map(eventItem).join(''):'<div class="item">No major live travel/security alert loaded.</div>'}</div></div><div class="card"><h3>Countries getting attention</h3><div class="list">${worse.length?worse.map(r=>`<div class="item ${r.war>0?'red':r.crisis>0?'orange':''}"><b>${esc(r.country)}</b> risk ${esc(r.risk)}<br><span class="muted">war ${esc(r.war)} | terror ${esc(r.terror)} | movement ${esc(r.movement)} | crisis ${esc(r.crisis)}</span></div>`).join(''):'<div class="item">No country spike loaded.</div>'}</div></div><div class="card"><h3>Rules</h3><div class="list">${(data&&data.rules||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join('')}</div></div>`);}
function markets(data){panel('Money',`<div class="card"><h3>Money / markets</h3><p class="plain">Real loaded market rows only. No zero placeholders and no guaranteed buy/sell calls.</p></div><div class="card"><h3>Rapid movers</h3><div class="list">${(data.rapid||[]).map(m=>`<div class="item"><b>${esc(m.name||m.id)}</b> ${esc(m.price)} | ${esc(Number(m.changePct).toFixed(2))}%<br><span class="muted">${esc(m.direction)} | score ${esc(Math.round(m.score))} | ${esc(m.source)}</span><br>${(m.reason||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>`).join('')||'<div class="item">No market rows loaded.</div>'}</div></div>`);}
function sources(data){panel('Sources',`<div class="card"><h3>Source health</h3><p class="plain">Every scraper reports success/failure and record count. Failed sources do not create fake numbers.</p></div><table class="source-table"><tr><th>Source</th><th>Status</th><th>Records</th></tr>${(data.sources||[]).map(s=>`<tr><td>${esc(s.name)}<br><span class="muted">${esc(s.category||'')}</span></td><td class="${s.success?'source-ok':'source-bad'}">${s.success?'OK':'FAIL'}<br><span class="muted">${esc(s.message||'')}</span></td><td>${esc(s.records??0)}</td></tr>`).join('')}</table>`);}
function crisis(state){panel('Crisis',`<div class="card"><h3>Crisis tracker</h3><p class="plain">Serious earthquakes, disasters, severe hazards and humanitarian signals.</p></div><div class="list">${(state.events||[]).filter(e=>e.kind==='crisis'&&Number(e.severity||0)>=3).slice(0,40).map(eventItem).join('')||'<div class="item">No serious crisis data loaded.</div>'}</div>`);}
function travel(state){panel('Travel Security',`<div class="card"><h3>Travel Security Companion</h3><p class="plain">Use AREA SCAN for the street/neighbourhood workflow: search, zoom, radius circle, verdict and emergency infrastructure.</p></div><div class="card"><h3>Active travel/security signals</h3><div class="list">${(state.events||[]).filter(e=>['war','terror','politics','movement'].includes(e.kind)&&Number(e.severity||0)>=2).slice(0,30).map(eventItem).join('')||'<div class="item">No travel/security signals loaded.</div>'}</div></div>`);}
function cityRisk(){panel('City Risk',`<div class="card"><h3>City risk</h3><p class="plain">Use the top search to type a street, area, town or city and generate a 5 mile radius security scan.</p></div>`);}
function countryRisk(state){panel('Country Risk',`<div class="card"><h3>Country risk</h3><p class="plain">Country risk now appears mainly when a country/place is clicked. This list is source health/debug context.</p></div><div class="list">${(state.countryRisk||[]).sort((a,b)=>b.risk-a.risk).slice(0,30).map(r=>`<div class="item ${r.war>0?'red':r.crisis>0?'orange':''}"><b>${esc(r.country)}</b> risk ${esc(r.risk)}<br><span class="muted">war ${esc(r.war)} | terror ${esc(r.terror)} | politics ${esc(r.politics)} | crisis ${esc(r.crisis)} | movement ${esc(r.movement)}</span></div>`).join('')}</div>`);}
window.Renderers={panel,placeCard,liveBrief,markets,sources,crisis,travel,eventItem,tile,eventCard,cityRisk,countryRisk,areaScanForm,areaScanResult};
})();
