(function(){
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function panel(title,html){$('panel').style.display='block';$('panelTitle').textContent=title||'Info';$('panelBody').innerHTML=html||'';}
function cls(v,reverse=false){if(v===null||v===undefined)return'grey';const n=Number(v);if(reverse){if(n>=60)return'red';if(n>=30)return'orange';if(n>0)return'yellow';return'green';}if(n>=75)return'green';if(n>=55)return'yellow';if(n>=35)return'orange';return'red';}
function tile(label,value,small,reverse=false){const shown=value===null||value===undefined?'N/A':Math.round(Number(value));return`<div class="tile ${cls(value,reverse)}"><div class="label">${esc(label)}</div><div class="num">${shown}</div><div class="muted">${esc(small||'')}</div></div>`;}
function eventItem(e){return`<div class="item ${e.kind==='war'||e.kind==='terror'?'red':e.kind==='crisis'?'orange':''}"><b>${esc(e.title||'Live signal')}</b><br><span class="muted">${esc(e.kind||'signal')} | ${esc(e.place||e.country||'mapped place')} | ${esc(e.source||e.sourceSystem||'source')}</span>${e.url?`<br><a target="_blank" rel="noopener" href="${esc(e.url)}">open source</a>`:''}</div>`;}
function eventCard(e){panel(e.title||'Live signal',`<div class="card"><h3>${esc(e.title||'Live signal')}</h3><div class="list"><div class="item"><b>Type:</b> ${esc(e.kind||'signal')}</div><div class="item"><b>Place:</b> ${esc(e.place||e.country||'mapped place')}</div><div class="item"><b>Source:</b> ${esc(e.source||e.sourceSystem||'source')}</div><div class="item"><b>What it means:</b> ${esc(e.summary||e.title||'No summary loaded')}</div>${e.url?`<div class="item"><a target="_blank" rel="noopener" href="${esc(e.url)}">open source</a></div>`:''}</div></div>`);}
function placeName(data){const p=data.place||{};const r=p.raw||{};return [r.neighbourhood,r.suburb,p.name,p.city,p.county,p.state,p.country].filter(Boolean).filter((x,i,a)=>a.findIndex(y=>String(y).toLowerCase()===String(x).toLowerCase())===i).join(', ')||p.displayName||'Selected place';}
function placeCard(data){const p=data.place||{}, c=data.country||{}, r=data.risk||{}, i=data.infrastructure||{}, wiki=data.wiki||{}, events=data.nearbyEvents||[];
 if(data.isOcean||(!p.country&&!c.name&&!data.country)){panel('Ocean',`<div class="card"><h3>${esc(data.oceanName||'Ocean / sea area')}</h3><p class="plain">This point is not land. Country safety, local crime and travel advice are not shown for ocean clicks.</p></div>`);return;}
 const name=placeName(data);
 panel('Place intelligence',`<div class="card"><h3>${esc(name)}</h3><p class="plain"><b>Verdict:</b> <span class="${cls(r.safety&&r.safety.value)}">${esc(r.verdict||'UNKNOWN')}</span></p><div class="grid">${tile('Safety',r.safety&&r.safety.value,r.safety&&r.safety.label)}${tile('Crime',r.crime&&r.crime.value,r.crime&&r.crime.dataLevel)}${tile('War',r.war&&r.war.value,r.war&&r.war.label,true)}${tile('Terror',r.terror&&r.terror.value,r.terror&&r.terror.label,true)}${tile('Politics',r.politics&&r.politics.value,r.politics&&r.politics.label,true)}${tile('Crisis',r.crisis&&r.crisis.value,r.crisis&&r.crisis.label,true)}</div></div>
 <div class="card"><h3>Security check</h3><div class="list"><div class="item"><b>Local crime:</b> ${data.localCrime&&data.localCrime.available?esc(`${data.localCrime.total} official local records in latest available police month`):'No official local crime feed for this exact area'}</div><div class="item"><b>Country context:</b> ${esc(c.name||p.country||'N/A')}</div><div class="item"><b>Travel advice:</b> ${esc(data.advisory&&data.advisory.level||'No advisory loaded')}</div><div class="item"><b>Weather now:</b> ${weather(data.weather)}</div><div class="item"><b>Nearby useful places:</b> ${Object.entries(i.counts||{}).slice(0,10).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(' | ')||'none loaded'}</div></div></div>
 ${wiki.found?`<div class="card"><h3>${esc(wiki.title)}</h3>${wiki.thumbnail?`<img class="wiki-img" src="${esc(wiki.thumbnail)}">`:''}<p class="plain">${esc((wiki.extract||'').slice(0,420))}</p><a target="_blank" rel="noopener" href="${esc(wiki.url)}">Wikipedia source</a></div>`:`<div class="card"><h3>Wikipedia image</h3><p class="plain">No sourced Wikipedia image found for this exact place.</p></div>`}
 <div class="card"><h3>Nearby live signals</h3><div class="list">${events.length?events.slice(0,10).map(eventItem).join(''):`<div class="item">No nearby live signals loaded.</div>`}</div></div>
 <div class="card"><h3>Data quality</h3><div class="list">${(data.dataRules||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join('')}</div></div>`);}
function weather(w){if(!w||!w.current)return'N/A';const c=w.current;return `${esc(c.temperatureC??'N/A')}°C, wind ${esc(c.windKmh??'N/A')} km/h, gust ${esc(c.gustKmh??'N/A')} km/h, rain ${esc(c.precipitationMm??'N/A')} mm`;}
function liveBrief(data){const buckets=data.buckets||[];panel('Live Brief',`<div class="card"><h3>Useful live brief</h3><p class="plain">Shows security/travel signals only. Marine notices and generic business headlines are filtered out of the main brief.</p></div><div class="card"><h3>Top alerts</h3><div class="list">${(data.keyAlerts||[]).slice(0,12).map(eventItem).join('')||'<div class="item">No major live alerts loaded.</div>'}</div></div><div class="card"><h3>By category</h3><div class="list">${buckets.map(b=>`<div class="item"><b>${esc(b.kind)}</b>: ${esc((b.items||[]).length)} loaded signals</div>`).join('')}</div></div>`);}
function markets(data){panel('Money',`<div class="card"><h3>Money / markets</h3><p class="plain">Real loaded market rows only. No zero placeholders and no guaranteed buy/sell calls.</p></div><div class="card"><h3>Rapid movers</h3><div class="list">${(data.rapid||[]).map(m=>`<div class="item"><b>${esc(m.name||m.id)}</b> ${esc(m.price)} | ${esc(Number(m.changePct).toFixed(2))}%<br><span class="muted">${esc(m.direction)} | score ${esc(Math.round(m.score))} | ${esc(m.source)}</span><br>${(m.reason||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>`).join('')||'<div class="item">No market rows loaded.</div>'}</div></div>`);}
function sources(data){panel('Sources',`<div class="card"><h3>Source health</h3><p class="plain">Every scraper reports success/failure and record count. Failed sources do not create fake numbers.</p></div><table class="source-table"><tr><th>Source</th><th>Status</th><th>Records</th></tr>${(data.sources||[]).map(s=>`<tr><td>${esc(s.name)}<br><span class="muted">${esc(s.category||'')}</span></td><td class="${s.success?'source-ok':'source-bad'}">${s.success?'OK':'FAIL'}<br><span class="muted">${esc(s.message||'')}</span></td><td>${esc(s.records??0)}</td></tr>`).join('')}</table>`);}
function crisis(state){panel('Crisis',`<div class="card"><h3>Crisis tracker</h3><p class="plain">Earthquakes, disasters, severe hazards and humanitarian signals. Weather is only displayed when it is actually relevant to safety or travel.</p></div><div class="list">${(state.events||[]).filter(e=>e.kind==='crisis').slice(0,40).map(eventItem).join('')||'<div class="item">No crisis data loaded.</div>'}</div>`);}
function travel(state){panel('Travel Security',`<div class="card"><h3>Travel Security Companion</h3><p class="plain">Click any place on the map. The place card checks local data where available, country context, live events, infrastructure, weather and travel advice.</p></div><div class="card"><h3>Active travel/security signals</h3><div class="list">${(state.events||[]).filter(e=>['war','terror','politics','movement'].includes(e.kind)).slice(0,20).map(eventItem).join('')||'<div class="item">No travel/security signals loaded.</div>'}</div></div>`);}
function cityRisk(){panel('City Risk',`<div class="card"><h3>City risk</h3><p class="plain">Search or click a city. The system returns exact place resolution, UK local crime where available, nearby infrastructure, weather, live signals, country context and Wikipedia image. It will not invent local crime for countries without a local official feed.</p></div>`);}
function countryRisk(state){panel('Country Risk',`<div class="card"><h3>Country risk</h3><p class="plain">Country-level. Not town crime. War overlay uses the war column only.</p></div><div class="list">${(state.countryRisk||[]).sort((a,b)=>b.risk-a.risk).map(r=>`<div class="item ${r.war>0?'red':r.crisis>0?'orange':''}"><b>${esc(r.country)}</b> risk ${esc(r.risk)}<br><span class="muted">war ${esc(r.war)} | terror ${esc(r.terror)} | politics ${esc(r.politics)} | crisis ${esc(r.crisis)} | movement ${esc(r.movement)}</span></div>`).join('')}</div>`);}
window.Renderers={panel,placeCard,liveBrief,markets,sources,crisis,travel,eventItem,tile,eventCard,cityRisk,countryRisk};
})();
