(function(){
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function panel(title,html){document.getElementById("panelTitle").textContent=title;document.getElementById("panelBody").innerHTML=html;document.getElementById("panel").style.display="block";}
function cls(v, inverse=false){const n=Number(v);if(!Number.isFinite(n))return"muted";if(inverse){return n>=60?"red":n>=30?"orange":n>0?"yellow":"green";}return n>=75?"green":n>=55?"yellow":n>=35?"orange":"red";}
function tile(label,value,sub,inverse=false){const n=Number(value);return `<div class="tile"><div class="label">${esc(label)}</div><div class="num ${cls(n,inverse)}">${Number.isFinite(n)?Math.round(n):"N/A"}</div><div class="muted">${esc(sub||"")}</div></div>`;}
function eventItem(e){const c=e.kind==="war"||e.kind==="terror"?"red":e.kind==="crisis"?"orange":"";return `<div class="item ${c}"><b>${esc(e.kind||"signal").toUpperCase()}</b> ${esc(e.title||e.summary||"")}<br><span class="muted">${esc(e.place||e.country||"mapped point")} | ${esc(e.source||e.sourceSystem||"source")}</span>${e.url?`<br><a target="_blank" rel="noopener" href="${esc(e.url)}">open source</a>`:""}</div>`;}
function placeCard(data){const p=data.place||{}, r=data.risk||{}, i=data.infrastructure||{}, wiki=data.wiki||{}, events=data.nearbyEvents||[], country=data.country||{};panel("Place Intelligence",`<div class="card"><h3>${esc(p.displayName||p.name||country.name||"Selected place")}</h3><p class="plain"><b>Verdict:</b> <span class="${cls(r.safety&&r.safety.value)}">${esc(r.verdict||"UNKNOWN")}</span></p><div class="grid">${tile("Safety",r.safety&&r.safety.value,r.safety&&r.safety.dataLevel)}${tile("Crime",r.crime&&r.crime.value,r.crime&&r.crime.dataLevel)}${tile("War",r.war&&r.war.value,r.war&&r.war.label,true)}${tile("Terror",r.terror&&r.terror.value,r.terror&&r.terror.label,true)}${tile("Politics",r.politics&&r.politics.value,r.politics&&r.politics.label,true)}${tile("Crisis",r.crisis&&r.crisis.value,r.crisis&&r.crisis.label,true)}</div></div><div class="card"><h3>For travel / family check</h3><div class="list"><div class="item"><b>Local crime:</b> ${esc(data.localCrime&&data.localCrime.available?`${data.localCrime.total} official local records (${data.localCrime.date})`:"No official local crime feed for this exact area")}</div><div class="item"><b>Weather now:</b> ${weather(data.weather)}</div><div class="item"><b>Travel advice:</b> ${esc(data.advisory&&data.advisory.level||"No advisory loaded")}</div><div class="item"><b>Useful nearby infrastructure:</b> ${Object.entries(i.counts||{}).slice(0,8).map(([k,v])=>`${esc(k)} ${esc(v)}`).join(" | ")||"none loaded"}</div></div></div>${wiki.found?`<div class="card"><h3>${esc(wiki.title)}</h3>${wiki.thumbnail?`<img class="wiki-img" src="${esc(wiki.thumbnail)}">`:""}<p class="plain">${esc((wiki.extract||"").slice(0,420))}</p><a target="_blank" rel="noopener" href="${esc(wiki.url)}">Wikipedia source</a></div>`:`<div class="card"><h3>Wikipedia image</h3><p class="plain">No sourced image found for this exact place.</p></div>`}<div class="card"><h3>Nearby live signals</h3><div class="list">${events.length?events.slice(0,10).map(eventItem).join(""):`<div class="item">No nearby live signals loaded.</div>`}</div></div><div class="card"><h3>Data rules</h3><div class="list">${(data.dataRules||[]).map(x=>`<div class="item yellow">${esc(x)}</div>`).join("")}</div></div>`);}
function weather(w){if(!w||!w.current)return"N/A";const c=w.current;return `${esc(c.temperatureC??"N/A")}°C, wind ${esc(c.windKmh??"N/A")} km/h, gust ${esc(c.gustKmh??"N/A")} km/h, rain ${esc(c.precipitationMm??"N/A")} mm`;}
function liveBrief(data){panel("Live Brief",`<div class="card"><h3>${esc(data.headline||"Live security brief")}</h3><p class="plain">Current priority: travel security, family watch, movement disruption, crisis and money signals. This is not a guarantee; it is a source-backed brief.</p></div><div class="card"><h3>Key alerts</h3><div class="list">${(data.keyAlerts||[]).slice(0,10).map(eventItem).join("")||"<div class='item'>No major live alerts loaded.</div>"}</div></div><div class="card"><h3>Family watch</h3><div class="list">${(data.topFamilyWatch||[]).map(f=>`<div class="item ${f.risk>=70?"red":f.risk>=35?"orange":""}"><b>${esc(f.name)}, ${esc(f.country)}</b><br>${esc(f.verdict)} | risk ${esc(f.risk)}</div>`).join("")}</div></div>`);}
function family(rows){panel("Family Watch",`<div class="card"><h3>Syria / Middle East / Ukraine watchlist</h3><p class="plain">Built for checking people and places you care about. Risk is from nearby live signals, not fake local police data.</p></div><div class="list">${(rows.familyWatch||[]).map(f=>`<div class="item ${f.risk>=70?"red":f.risk>=35?"orange":""}"><b>${esc(f.name)}, ${esc(f.country)}</b><br>${esc(f.verdict)} | risk ${esc(f.risk)}<br>${(f.nearby||[]).slice(0,3).map(n=>`<span class="tag">${esc(n.kind)} ${Math.round(n.distanceKm)}km</span>`).join("")}</div>`).join("")}</div>`);}
function markets(data){panel("Money",`<div class="card"><h3>Money / markets</h3><p class="plain">Shows real loaded market rows only. No zero placeholders and no guaranteed buy/sell calls.</p></div><div class="card"><h3>Rapid movers</h3><div class="list">${(data.rapid||[]).map(m=>`<div class="item"><b>${esc(m.name||m.id)}</b> ${esc(m.price)} | ${esc(Number(m.changePct).toFixed(2))}%<br><span class="muted">${esc(m.direction)} | score ${esc(Math.round(m.score))} | ${esc(m.source)}</span><br>${(m.reason||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div>`).join("")}</div></div>`);}
function sources(data){panel("Sources",`<div class="card"><h3>Source health</h3><p class="plain">Every scraper reports success/failure and record count.</p></div><table class="source-table"><tr><th>Source</th><th>Status</th><th>Records</th></tr>${(data.sources||[]).map(s=>`<tr><td>${esc(s.name)}<br><span class="muted">${esc(s.category||"")}</span></td><td class="${s.success?"source-ok":"source-bad"}">${s.success?"OK":"FAIL"}<br><span class="muted">${esc(s.message||"")}</span></td><td>${esc(s.records??0)}</td></tr>`).join("")}</table>`);}
function crisis(state){panel("Crisis",`<div class="card"><h3>Crisis tracker</h3><p class="plain">Earthquakes, disasters, severe weather and humanitarian signals.</p></div><div class="list">${(state.events||[]).filter(e=>e.kind==="crisis").slice(0,30).map(eventItem).join("")}</div>`);}
function travel(state){panel("Travel Security",`<div class="card"><h3>Travel Security Companion</h3><p class="plain">Click any place on the map. The place card checks travel advice, local data where available, national indicators, live events, infrastructure, weather and family-safety context.</p></div><div class="card"><h3>Active travel/security signals</h3><div class="list">${(state.events||[]).filter(e=>["war","terror","politics","movement"].includes(e.kind)).slice(0,15).map(eventItem).join("")}</div></div>`);}
window.Renderers={panel,placeCard,liveBrief,family,markets,sources,crisis,travel,eventItem,tile};
})();
