import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createApplication } from '../../src/app/create-application.js';
import { loadConfig } from '../../src/config/load-config.js';
import { createLogger } from '../../src/core/logger.js';
let server, application, baseUrl;
test.before(async () => { const config = loadConfig({ NODE_ENV: 'test', LOG_LEVEL: 'fatal', PORT: '4174' }); application = await createApplication({ config, logger: createLogger({ level: 'fatal', service: 'part15-test' }) }); server = createServer(application.handle); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); baseUrl = `http://127.0.0.1:${server.address().port}`; });
test.after(async () => { server.closeAllConnections?.(); await new Promise(resolve => server.close(resolve)); await application.close(); });
test('commercial catalog and diagnostics endpoints are available', async () => { const catalog = await fetch(`${baseUrl}/api/commercial/catalog`); assert.equal(catalog.status, 200); assert.equal((await catalog.json()).platform, 'MERLIN_COMMERCIAL_OPERATIONS'); const diagnostics = await fetch(`${baseUrl}/api/commercial/diagnostics`); assert.equal(diagnostics.status, 200); });
test('commercial seed and snapshot create operational customer data', async () => { const seed = await fetch(`${baseUrl}/api/commercial/seed`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); assert.equal(seed.status, 201); const snapshot = await fetch(`${baseUrl}/api/commercial/snapshot`); const body = await snapshot.json(); assert.equal(snapshot.status, 200); assert.ok(body.tenants.length >= 1); assert.ok(body.featureFlags.length >= 1); });
test('commercial API records usage and returns customer health', async () => { await fetch(`${baseUrl}/api/commercial/usage`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ tenantId: 'tenant-merlin-demo', userId: 'anonymous', metric: 'apiRequests', quantity: 10 }) }); const response = await fetch(`${baseUrl}/api/commercial/health/tenant-merlin-demo`); assert.equal(response.status, 200); assert.equal((await response.json()).usage.rollup.metrics.apiRequests, 10); });
