import test from 'node:test';
import assert from 'node:assert/strict';
import { createCommercialOperationsService } from '../../src/services/commercial-operations-service.js';
function platform() { return createCommercialOperationsService(); }
test('platform seeds a customer workspace and operating assets', async () => { const service = platform(); const snapshot = await service.seed('u'); assert.equal(snapshot.tenants.length, 1); assert.ok(snapshot.status.components.length >= 3); assert.equal(snapshot.diagnostics.status, 'READY'); });
test('seat invitations can be accepted into active seats', async () => { const service = platform(); await service.seed('u'); const invite = await service.inviteSeat('u', { tenantId: 'tenant-merlin-demo', email: 'analyst@example.test', role: 'ANALYST', seatLimit: 10 }); const result = await service.acceptInvitation('u', invite.token, { userId: 'analyst', name: 'Analyst' }); assert.equal(result.seat.role, 'ANALYST'); assert.equal(result.invitation.state, 'ACCEPTED'); });
test('usage, health and account brief remain evidence based', async () => { const service = platform(); await service.seed('u'); await service.recordUsage('u', { tenantId: 'tenant-merlin-demo', userId: 'u', metric: 'apiRequests', quantity: 50 }); await service.recordUsage('u', { tenantId: 'tenant-merlin-demo', userId: 'u', metric: 'activeDays', quantity: 12 }); const health = await service.customerHealth('u', 'tenant-merlin-demo'); assert.equal(health.usage.rollup.metrics.apiRequests, 50); const brief = await service.accountBrief('u', 'tenant-merlin-demo'); assert.equal(brief.tenantId, 'tenant-merlin-demo'); });
test('support cases expose SLA status and update lifecycle timestamps', async () => { const service = platform(); await service.seed('u'); const opened = await service.openSupportCase('u', { tenantId: 'tenant-merlin-demo', title: 'Issue', severity: 'SEV2' }); const updated = await service.updateSupportCase('u', { id: opened.case.id, state: 'RESOLVED', firstResponse: true }); assert.ok(updated.case.firstResponseAt); assert.ok(updated.case.resolvedAt); });
test('feature evaluation, status and exports operate through platform service', async () => { const service = platform(); await service.seed('u'); const feature = await service.evaluateFeature('u', { key: 'COMMERCIAL_OPERATIONS', context: { tenantId: 'tenant-merlin-demo' } }); assert.equal(feature.evaluation.enabled, true); const status = await service.statusSummary('u'); assert.ok(status.uptime.uptimePercent <= 100); const output = await service.export('u', { format: 'SUMMARY' }); assert.match(output.body, /MERLIN CUSTOMER OPERATIONS/); });
