import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createApplication } from '../../src/app/create-application.js';
import { loadConfig } from '../../src/config/load-config.js';
import { createLogger } from '../../src/core/logger.js';
let server, application, baseUrl;
test.before(async () => { const config = loadConfig({ NODE_ENV: 'test', LOG_LEVEL: 'fatal', PORT: '4188' }); application = await createApplication({ config, logger: createLogger({ level: 'fatal', service: 'part18-test' }) }); server = createServer(application.handle); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); baseUrl = `http://127.0.0.1:${server.address().port}`; });
test.after(async () => { server.closeAllConnections?.(); await new Promise(resolve => server.close(resolve)); await application.close(); });
test('release catalog and diagnostics APIs are available', async () => { const response = await fetch(`${baseUrl}/api/release/catalog`); assert.equal(response.status, 200); assert.equal((await response.json()).parts, 18); assert.equal((await fetch(`${baseUrl}/api/release/diagnostics`)).status, 200); });
test('seeded release snapshot exposes component and readiness evidence', async () => { assert.equal((await fetch(`${baseUrl}/api/release/seed`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' })).status, 201); const body = await (await fetch(`${baseUrl}/api/release/snapshot`)).json(); assert.ok(body.components.length >= 6); assert.ok(body.readiness); assert.ok(body.goLive); });
test('release calculation APIs perform checks', async () => { const response = await fetch(`${baseUrl}/api/release/acceptance/evaluate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ partsDelivered: 18, maximumPartFiles: 99, sourceLines: 60000, passedTests: 1, failedTests: 0, syntaxFailures: 0, syntaxChecks: 1, securityScanPassed: true, archiveIntegrity: true, fabricatedLiveData: false }) }); assert.equal((await response.json()).accepted, true); });
