window.MoneyMap = (() => {
  let map, nodesLayer, cityLayer, eventsLayer, seaLayer, landLayer, warGlowLayer;
  let currentFilter='all'; let lastEventIds=new Set();
  const colors={war:'#c4002f',terror:'#ff004f',disaster:'#ff7b22',election:'#a871ff',shipping:'#00d8ff',port:'#00d8ff',ai:'#a871ff',tech:'#a871ff',energy:'#00ff87',commodity:'#ffd94a',finance:'#3ea0ff',city:'#7aa7ff',risk:'#ff326a'};
  function sound(){ try{ const A=window.AudioContext||window.webkitAudioContext; const ctx=new A(); const o=ctx.createOscillator(); const g=ctx.createGain(); o.type='sine'; o.frequency.value=880; g.gain.value=.035; o.connect(g); g.connect(ctx.destination); o.start(); setTimeout(()=>o.frequency.value=1180,90); setTimeout(()=>{o.stop();ctx.close();},260); }catch(e){} }
  function icon(kind, flash=false){ return L.divIcon({ className:'', html:`<div class="node-dot ${kind} ${flash?'flash':''}"></div>`, iconSize:[18,18], iconAnchor:[9,9] }); }
  function init(){
    map=L.map('map',{worldCopyJump:false,zoomSnap:.25,zoomDelta:.5,minZoom:2.55,maxZoom:16,zoomControl:true,attributionControl:true,maxBounds:[[-68,-176],[78,176]],maxBoundsViscosity:1}).setView([24,18],2.7);
    L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{subdomains:'abcd',noWrap:true,bounds:[[-85,-180],[85,180]],attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(map);
    nodesLayer=L.layerGroup().addTo(map); cityLayer=L.layerGroup().addTo(map); eventsLayer=L.layerGroup().addTo(map); seaLayer=L.layerGroup().addTo(map); landLayer=L.layerGroup().addTo(map); warGlowLayer=L.layerGroup().addTo(map);
    map.on('zoomend moveend',()=>{ renderEvents(window.APP_STATE?.events||[]); renderCities(window.MAP_DATA?.cityNodes||[]); renderWarGlow(window.APP_STATE?.events||[]); resize(); });
    map.on('click', async e => { const d=await fetch(`/api/context?lat=${e.latlng.lat}&lng=${e.latlng.lng}`).then(r=>r.json()); try{ const rev=await fetch(`/api/reverse?lat=${e.latlng.lat}&lng=${e.latlng.lng}`).then(r=>r.json()); d.reverse=rev; }catch(_){} Renderers.renderContext(d); });
    document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{ document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); currentFilter=b.dataset.filter; Panels.closeAll(); renderEvents(window.APP_STATE?.events||[]); }));
    document.addEventListener('change', e=>{ if(e.target?.id==='seaToggle'){ window.SHOW_SEA=e.target.checked; renderRoutes(window.ROUTES||[]); } if(e.target?.id==='landToggle'){ window.SHOW_LAND=e.target.checked; renderRoutes(window.ROUTES||[]); } });
    setTimeout(resize,250);
  }
  function renderLegend(){ const el=document.getElementById('legend'); const keys={war:'war',terror:'terror',disaster:'disaster',election:'election',shipping:'shipping',ai:'AI',commodity:'commodity',energy:'energy',finance:'finance',city:'city'}; el.innerHTML=Object.entries(keys).map(([k,v])=>`<span><i style="background:${colors[k]}"></i>${v}</span>`).join(''); }
  function renderBase(nodes){ nodesLayer.clearLayers(); for(const n of nodes||[]){ const kind=n.kind==='tech'?'ai':n.kind; L.marker([n.lat,n.lng],{icon:icon(kind)}).on('click',()=>Renderers.renderNode(n)).addTo(nodesLayer); } renderLegend(); }
  function renderCities(cities){ cityLayer.clearLayers(); const z=map.getZoom(); if(z<4.5) return; const bounds=map.getBounds(); const limit=z>=10?900:z>=8?620:z>=6?360:120; for(const c of (cities||[]).filter(x=>bounds.pad(.35).contains([x.lat,x.lng])).slice(0,limit)){ L.marker([c.lat,c.lng],{icon:icon(c.kind||'city')}).on('click',()=>Renderers.renderNode(c)).addTo(cityLayer); } }
  function renderEvents(events, flashIds=new Set()){ eventsLayer.clearLayers(); const z=map.getZoom(); const bounds=map.getBounds(); const filtered=(events||[]).filter(e=> currentFilter==='all' || e.kind===currentFilter || (currentFilter==='ai' && e.kind==='tech')); const visible=filtered.filter(e=>z<5 || bounds.pad(.45).contains([e.lat,e.lng])).slice(0,z>=9?1200:z>=7?800:z>=5?520:360); for(const e of visible){ const kind=e.kind==='tech'?'ai':e.kind; L.marker([e.lat,e.lng],{icon:icon(kind, flashIds.has(e.id))}).on('click',()=>Renderers.renderEvent(e)).addTo(eventsLayer); } renderWarGlow(events); }
  function renderWarGlow(events){ warGlowLayer.clearLayers(); const clusters={}; for(const e of (events||[]).filter(x=>['war','terror'].includes(x.kind))){ const key=`${Math.round(e.lat*2)/2},${Math.round(e.lng*2)/2}`; clusters[key] = clusters[key] || {lat:e.lat,lng:e.lng,n:0}; clusters[key].n++; } for(const c of Object.values(clusters).filter(c=>c.n>=1).slice(0,80)){ L.circle([c.lat,c.lng],{radius:Math.min(90000,24000+c.n*9000),color:'#5a001b',fillColor:'#6d001d',fillOpacity:.22,weight:1,className:'war-glow'}).addTo(warGlowLayer); } }
  function renderRoutes(routes){ seaLayer.clearLayers(); landLayer.clearLayers(); const add = r => { const layer=r.type==='sea'?seaLayer:landLayer; const pts=r.points.map(p=>[p[0],p[1]]); const cls=r.type==='sea'?'moving-route sea-route':'moving-route land-route'; L.polyline(pts,{color:r.color,weight:r.type==='sea'?7:6,opacity:.32,className:'route-shadow'}).on('click',()=>Renderers.renderRoute(r)).addTo(layer); L.polyline(pts,{color:r.color,weight:r.type==='sea'?3:3,opacity:.98,className:cls}).on('click',()=>Renderers.renderRoute(r)).addTo(layer); if(map.getZoom()>=4){ const mid=pts[Math.floor(pts.length/2)]; L.marker(mid,{icon:L.divIcon({className:'route-label',html:`${r.name}<br><span>${r.goods}</span>`,iconSize:null})}).on('click',()=>Renderers.renderRoute(r)).addTo(layer); } };
    for(const r of routes||[]){ if(r.type==='sea' && window.SHOW_SEA) add(r); if(r.type==='land' && window.SHOW_LAND) add(r); }
  }
  function setData(mapData,state){ window.MAP_DATA=mapData; window.ROUTES=mapData.routes; window.SHOW_SEA=true; window.SHOW_LAND=true; renderBase(mapData.nodes); renderCities(mapData.cityNodes); renderRoutes(mapData.routes); renderEvents(state?.events||[]); setTimeout(resize,250); }
  function newEvent(e){ if(!e || lastEventIds.has(e.id)) return; lastEventIds.add(e.id); showToast(e.title); sound(); renderEvents(window.APP_STATE?.events||[], new Set([e.id])); }
  function showToast(text){ const t=document.getElementById('toast'); t.textContent='NEW MAP EVENT: '+String(text||'').slice(0,155); t.classList.remove('show'); void t.offsetWidth; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),6500); }
  function resize(){ if(!map) return; map.invalidateSize(); setTimeout(()=>map.invalidateSize(),220); }
  return { init,setData,newEvent,resize,renderEvents,renderCities,renderRoutes };
})();
