window.Renderers = (() => {
  const esc = s => String(s??'').replace(/[&<>"']/g,m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[m]));
  const money = n => Number.isFinite(Number(n)) ? '$' + Number(n).toLocaleString(undefined,{maximumFractionDigits:Number(n)<10?4:2}) : '—';
  const pct = n => Number(n||0);
  const arrow = n => `<span class="${pct(n)>=0?'up':'down'}">${pct(n)>=0?'▲':'▼'} ${Math.abs(pct(n)).toFixed(2)}%</span>`;
  function groupMarkets(kind){ const list=(window.APP_STATE?.markets||[]); return list.filter(m=> kind==='all' || m.group===kind || m.type===kind || (kind==='crypto'&&m.source==='Binance')); }
  function renderTicker(markets){ document.getElementById('ticker').innerHTML=(markets||[]).slice(0,22).map(m=>`<span><b>${esc(m.id)}</b> ${money(m.price)} ${arrow(m.changePct)}</span>`).join('') || '<span>No market data</span>'; }
  function renderMarkets(markets){ renderTicker(markets); }
  function marketTable(list){ return `<div class="market-table">${(list||[]).map(m=>`<div class="market-row"><div class="sym">${esc(m.id)}</div><div><div class="name">${esc(m.name)}</div><div class="sub">${esc(m.source)} · ${esc(m.status||'unknown')} ${m.ageSec?`· ${m.ageSec}s old`:''}</div></div><div class="price"><b>${money(m.price)}</b><br>${arrow(m.changePct)}</div></div>`).join('') || '<div class="warn">No feed result. Check API/network status.</div>'}</div>`; }
  function sourceList(sources){ return (sources||[]).map(s=>`<a target="_blank" href="${esc(s.url||'#')}">${esc(s.name||s.source||'source')}</a>`).join(' · ') || 'source pending'; }
  function eventList(events){ return (events||[]).map(e=>`<div class="info-card"><h3>${esc(e.title)}</h3><p>${esc(e.place||'')} · ${esc(e.source||'')}</p><p>${esc(e.summary||'')}</p><p class="action-line"><b>Watch:</b> ${(e.watch||[]).map(esc).join(', ') || 'source-specific assets pending'}</p><p><b>Check before acting:</b> confirm a market move, a second source, and whether related assets are reacting.</p><p class="source-line">${sourceList(e.sources||[{name:e.source,url:e.url}])}</p></div>`).join('') || '<div class="warn">No source-backed events loaded in this category.</div>'; }
  function routeControls(){ return `<p class="plain">Routes are off by default. Turn on only the layer you want. Lines show direction with slow moving flow.</p><div class="toggle-row"><label><input type="checkbox" id="seaToggle" ${window.SHOW_SEA?'checked':''}> Sea routes</label><label><input type="checkbox" id="landToggle" ${window.SHOW_LAND?'checked':''}> Land routes</label></div>`; }
  function riskLegend(){ return `<div class="safety-key"><span class="risk-pill darkred">ACTIVE WAR</span><span class="risk-pill red">HIGH RISK</span><span class="risk-pill yellow">MONITOR</span><span class="risk-pill green">LOW EVENT PRESSURE</span></div>`; }
  function openPanel(name){
    const state=window.APP_STATE||{};
    if(name==='crypto'){
      Panels.setDrawer('Crypto', `<p class="plain">Liquid crypto moves are useful when they confirm breaking events or risk-on/risk-off pressure. Avoid acting on fallback data.</p>${marketTable(groupMarkets('crypto'))}<div id="cryptoCharts"></div>`, 'crypto');
      const k=state.klines||{}; Charts.grid('cryptoCharts', ['BTCUSDT','ETHUSDT','SOLUSDT','XRPUSDT','BNBUSDT','ADAUSDT','DOGEUSDT'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='commodities'){
      Panels.setDrawer('Commodities', `<p class="plain">Use commodities as confirmation: oil for war/shipping, copper for grid/AI, gold for fear, uranium for energy security.</p>${marketTable(groupMarkets('commodity'))}<div id="commodityCharts"></div>`, 'commodities');
      const k=state.klines||{}; Charts.grid('commodityCharts', ['HG=F','BZ=F','GC=F','SI=F','URA','USO'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='polymarket') return Panels.setInfo('Polymarket', `<p class="plain">Crowd probability, not truth. Stronger signal = odds move + news source + asset reaction.</p>${(state.polymarket||[]).slice(0,45).map(p=>`<div class="info-card"><h3>${esc(p.question)}</h3><p><b>Volume:</b> ${Math.round(p.volume||0).toLocaleString()} · <b>Liquidity:</b> ${Math.round(p.liquidity||0).toLocaleString()}</p><p><b>Use:</b> compare probability movement with related assets. Do not trade only because a market is popular.</p><a target="_blank" href="${esc(p.url||'#')}">open market</a></div>`).join('')||'<div class="warn">No Polymarket data loaded.</div>'}`, 'polymarket');
    if(name==='xfeed') return Panels.setInfo('X live feed', `<p class="plain"><b>Status:</b> ${esc(state.xStatus?.connected?'connected':'not connected')} — ${esc(state.xStatus?.reason||'X_BEARER_TOKEN required in Render Environment')}.</p><p class="plain">This uses official X recent search only. No scraped/fake posts.</p>${(state.xfeed||[]).slice(0,60).map(x=>`<div class="info-card"><h3>${esc(x.title)}</h3><p>${esc(x.time||'')}</p><a target="_blank" href="${esc(x.url||'#')}">open post</a></div>`).join('') || '<div class="warn">X API not connected. Add X_BEARER_TOKEN in Render → Environment.</div>'}`, 'xfeed');
    if(name==='routes') return Panels.setInfo('Routes', `${routeControls()}<div class="route-list">${(window.ROUTES||[]).map(r=>`<div class="info-card route-chip" data-route="${esc(r.id)}"><h3>${esc(r.name)}</h3><p><b>Moves:</b> ${esc(r.goods)}</p><p><b>Direction:</b> ${esc(r.direction||'two-way')}</p><p><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</p><p><b>Check:</b> ${esc(r.verify||'confirm with freight/routing/source updates')}</p></div>`).join('')}</div>`, 'routes');
    if(name==='layers') return Panels.setInfo('Safety map', `${riskLegend()}<p class="plain">Toggle land-colour safety below. Green/yellow/red means current event-pressure layer. It is not fabricated crime data. UK local crime appears when you click a UK location.</p><div class="toggle-row"><label><input checked data-layer="risk" type="checkbox"> Conflict overlays</label><label><input id="safetyToggle" type="checkbox"> Safety land colour</label><label><input checked data-layer="events" type="checkbox"> Event dots</label></div>`, 'layers');
    if(name==='rapid'){
      Panels.setDrawer('Rapid movers', `<p class="plain">Shows assets moving unusually fast. Projection is a scenario estimate from trend, volatility and event support; it is not a prediction guarantee.</p>${(state.rapid||[]).map((r,i)=>`<div class="rapid-card"><h3>${esc(r.asset)} · ${esc(r.label)}</h3><p><b>Why shown:</b> ${(r.reasons||[]).map(esc).join(' · ')}</p><p><b>Chance estimate:</b> continuation ${esc(r.continuation)}% · reversal ${esc(r.drop)}%</p><p><b>Checks:</b> ${(r.checks||[]).map(esc).join(' · ')}</p><div class="chart-box"><canvas id="rapidChart${i}"></canvas><p class="chart-note">x-axis: projected steps · y-axis: price</p></div></div>`).join('')||'<div class="warn">No rapid movers yet.</div>'}`, 'rapid');
      setTimeout(()=> (state.rapid||[]).forEach((r,i)=>Charts.line(`rapidChart${i}`, r.projection||[], r.asset, 'price')),80); return;
    }
  }
  function renderNode(n){
    fetch('/api/image?title='+encodeURIComponent(n.imageTitle||n.name)).then(r=>r.json()).then(img=>{
      Panels.setInfo(n.name, `${img.ok?`<img class="ctx-image" src="${esc(img.image)}"><p class="source-line">image/source: <a target="_blank" href="${esc(img.source)}">Wikipedia/Wikimedia</a></p>`:''}<div class="info-card"><h3>${esc(n.name)}</h3><p>${esc(n.note||'Monitoring node.')}</p><p><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</p><p><b>Source:</b> ${esc(n.source||'baseline')}</p><p class="plain">Click the surrounding map for live nearby events and area safety context.</p></div>`, 'node');
    }).catch(()=>Panels.setInfo(n.name, `<div class="info-card"><h3>${esc(n.name)}</h3><p>${esc(n.note||'Monitoring node.')}</p><p><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</p></div>`, 'node'));
  }
  function renderEvent(e){ Panels.setInfo(e.title, eventList([e]), 'event'); }
  function renderRoute(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><p><b>Moves:</b> ${esc(r.goods)}</p><p><b>Direction:</b> ${esc(r.direction||'two-way')}</p><p><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</p><p><b>Why it matters:</b> ${esc(r.reason||'Route stress can change freight, energy and delivery costs.')}</p><p><b>Check:</b> ${esc(r.verify||'confirm with freight/routing/source updates')}</p></div>`, 'routes'); }
  function renderRiskRegion(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><p>${esc(r.note)}</p><p><b>Layer:</b> ${esc(r.kind)} · ${esc(r.level)}</p><p><b>Sources:</b> ${(r.sources||[]).map(esc).join(' · ')}</p><p class="plain">This is an event-risk overlay, not a precise frontline. Exact borders require a paid/official geospatial conflict feed.</p></div>`, 'layers'); }
  function renderSafetyRegion(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><p><b>Safety colour:</b> ${esc(r.level).toUpperCase()}</p><p>${esc(r.note)}</p><p class="plain">This layer uses event pressure, not invented crime rates. Click a UK location for police.uk crime data where available.</p></div>`, 'layers'); }
  function renderContext(d){
    const place=d?.reverse?.place || 'Selected area';
    const events=(d.nearbyEvents||[]).slice(0,18);
    const risk=events.some(e=>['war','terror'].includes(e.kind))?'red':events.some(e=>['disaster','election','shipping'].includes(e.kind))?'yellow':'green';
    const label=risk==='red'?'HIGH EVENT PRESSURE':risk==='yellow'?'MONITOR':'LOW EVENT PRESSURE';
    Panels.setInfo(place, `<div class="risk-row"><span class="risk-pill ${risk}">${label}</span><span>${events.length} nearby source-backed events/nodes in current feed.</span></div><p class="plain">Safety is based on nearby verified event pressure. UK locations may include police.uk crime data when available; global crime scores are not invented.</p>${eventList(events)}${(d.nearbyNodes||[]).slice(0,12).map(n=>`<div class="info-card"><h3>${esc(n.name)}</h3><p>${esc(n.note)}</p><p><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</p></div>`).join('')}`, 'context');
  }
  return { renderMarkets, openPanel, renderNode, renderEvent, renderRoute, renderContext, renderRiskRegion, renderSafetyRegion };
})();
