window.Renderers = (() => {
  const esc = s => String(s??'').replace(/[&<>"']/g,m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[m]));
  const money = n => Number.isFinite(Number(n)) ? '$' + Number(n).toLocaleString(undefined,{maximumFractionDigits:Number(n)<10?4:2}) : '—';
  const pct = n => Number(n||0);
  const arrow = n => `<span class="${pct(n)>=0?'up':'down'}">${pct(n)>=0?'▲':'▼'} ${Math.abs(pct(n)).toFixed(2)}%</span>`;
  function groupMarkets(kind){ const list=(window.APP_STATE?.markets||[]); return list.filter(m=> kind==='all' || m.group===kind || m.type===kind || (kind==='crypto'&&m.source==='Binance')); }
  function renderTicker(markets){
    const html=(markets||[]).slice(0,18).map(m=>`<span><b>${esc(m.id)}</b> ${money(m.price)} ${arrow(m.changePct)}</span>`).join('');
    document.getElementById('ticker').innerHTML=html || '<span>No market data</span>';
  }
  function marketTable(list){
    return `<div class="market-table">${(list||[]).map(m=>`<div class="market-row"><div class="sym">${esc(m.id)}</div><div><div class="name">${esc(m.name)}</div><div class="sub">${esc(m.source)} · ${esc(m.status||'unknown')} ${m.ageSec?`· ${m.ageSec}s old`:''}</div></div><div class="price"><b>${money(m.price)}</b><br>${arrow(m.changePct)}</div></div>`).join('') || '<div class="warn">No feed result. Check API/network status.</div>'}</div>`;
  }
  function renderMarkets(markets){ renderTicker(markets); }
  function renderPolymarket(items){}
  function renderSignals(items){}
  function renderRapid(items){}
  function sourceList(sources){ return (sources||[]).map(s=>`<a target="_blank" href="${esc(s.url||'#')}">${esc(s.name||s.source||'source')}</a>`).join(' · ') || 'source pending'; }
  function openPanel(name){
    const state=window.APP_STATE||{};
    if(name==='markets') return Panels.setInfo('Markets', `<p class="plain">Live tape, source status and freshness. Green/red arrows show direction from the latest feed.</p>${marketTable(state.markets||[])}`, 'markets');
    if(name==='crypto'){
      Panels.setDrawer('Crypto', `<p class="plain">Crypto is the fastest liquid layer in this build. Use the chart and feed freshness. Do not act if the source is fallback.</p><div id="cryptoTable">${marketTable(groupMarkets('crypto'))}</div><div id="cryptoCharts"></div>`, 'crypto');
      const k=state.klines||{}; Charts.grid('cryptoCharts', ['BTCUSDT','ETHUSDT','SOLUSDT'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='commodities'){
      Panels.setDrawer('Commodities', `<p class="plain">Commodity moves are useful when they confirm events: oil for war/shipping, copper for grid/AI, gold for risk, uranium for energy.</p>${marketTable(groupMarkets('commodity'))}<div id="commodityCharts"></div>`, 'commodities');
      const k=state.klines||{}; Charts.grid('commodityCharts', ['HG=F','BZ=F','GC=F','SI=F','URA'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='polymarket') return Panels.setInfo('Polymarket probabilities', `<p class="plain">Event-market odds. Use them as crowd probability, not truth. Strong signal = odds move + news source + asset reaction.</p>${(state.polymarket||[]).slice(0,30).map(p=>`<div class="info-card"><h3>${esc(p.question)}</h3><p>Volume ${Math.round(p.volume||0).toLocaleString()} · Liquidity ${Math.round(p.liquidity||0).toLocaleString()}</p><a target="_blank" href="${esc(p.url||'#')}">market</a></div>`).join('')||'<div class="warn">No Polymarket data loaded.</div>'}`, 'polymarket');
    if(name==='xfeed') return Panels.setInfo('X live feed', `<p class="plain">Official X recent-search feed. Needs X_BEARER_TOKEN in Render. Without it, the app will not pretend to scrape X.</p>${(state.xfeed||[]).slice(0,40).map(x=>`<div class="info-card"><h3>${esc(x.title)}</h3><p>${esc(x.time||'')}</p><a target="_blank" href="${esc(x.url||'#')}">post</a></div>`).join('') || '<div class="warn">X feed not connected. Add X_BEARER_TOKEN to Render Environment for live X posts.</div>'}`, 'xfeed');
    if(name==='war') return Panels.setInfo('War and attack monitor', `<p class="plain">Latest source-backed war/attack dots. Territory and battleline layers are disabled unless a verified geospatial source is connected. No invented frontlines.</p>${warMomentum(state.events||[])}${eventList((state.events||[]).filter(e=>['war','terror'].includes(e.kind)).slice(0,45))}`, 'war');
    if(name==='safety') return Panels.setInfo('Safety', `<p class="plain">Click any place on the map for local context. UK points use data.police.uk when available. Global safety uses live event density only unless a crime API is connected.</p>${safetySummary(state.events||[])}`, 'safety');
    if(name==='routes') return Panels.setInfo('Routes', `${routeControls()}<div class="route-list">${(window.ROUTES||[]).map(r=>`<div class="info-card route-chip" data-route="${esc(r.id)}"><h3>${esc(r.name)}</h3><p><b>Moves:</b> ${esc(r.goods)}</p><p><b>Direction:</b> ${esc(r.direction||'two-way')}</p><p><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</p></div>`).join('')}</div>`, 'routes');
    if(name==='rapid'){
      Panels.setDrawer('Rapid movers', `<p class="plain">Only shows assets moving faster than the rest of the board. Projection is a scenario estimate from trend, volatility and event support, not a promise.</p>${(state.rapid||[]).map((r,i)=>`<div class="rapid-card"><h3>${esc(r.asset)} · ${esc(r.label)}</h3><p><b>Why shown:</b> ${(r.reasons||[]).map(esc).join(' · ')}</p><p><b>Chance estimate:</b> continuation ${esc(r.continuation)}% · reversal ${esc(r.drop)}%</p><p><b>Checks:</b> ${(r.checks||[]).map(esc).join(' · ')}</p><div class="chart-box"><canvas id="rapidChart${i}"></canvas><p class="chart-note">x-axis: projected steps · y-axis: price</p></div></div>`).join('')||'<div class="warn">No rapid movers yet.</div>'}`, 'rapid');
      setTimeout(()=> (state.rapid||[]).forEach((r,i)=>Charts.line(`rapidChart${i}`, r.projection||[], r.asset, 'price')),80); return;
    }
  }
  function routeControls(){ return `<p class="plain">Toggle routes without changing map dots.</p><div class="toggle-row"><label><input type="checkbox" id="seaToggle" ${window.SHOW_SEA?'checked':''}> Sea routes</label><label><input type="checkbox" id="landToggle" ${window.SHOW_LAND?'checked':''}> Land routes</label></div>`; }
  function eventList(events){ return events.map(e=>`<div class="info-card"><h3>${esc(e.title)}</h3><p>${esc(e.place||'')} · ${esc(e.source||'')}</p><p>${esc(e.summary||'')}</p><p><b>Watch:</b> ${(e.watch||[]).map(esc).join(', ')}</p><p class="source-line">${sourceList(e.sources||[{name:e.source,url:e.url}])}</p></div>`).join('') || '<div class="warn">No verified events loaded in this category.</div>'; }
  function warMomentum(events){ const recent=events.filter(e=>['war','terror'].includes(e.kind)); const n=recent.length; const score=Math.min(100,n*6); return `<div class="momentum"><div><b>Conflict event pressure</b><span>${n} mapped reports in current feed</span></div><div class="bar"><i style="width:${score}%"></i></div><p class="sub">This is a source-count pressure indicator, not territorial control.</p></div>`; }
  function safetySummary(events){ const risks=events.filter(e=>['war','terror','disaster'].includes(e.kind)); return `<div class="safety-key"><span class="safe green">GREEN</span> no nearby verified risk feed</div><div class="safety-key"><span class="safe yellow">YELLOW</span> current event/incident pressure nearby</div><div class="safety-key"><span class="safe red">RED</span> active war/terror/disaster reports nearby</div>${eventList(risks.slice(0,30))}`; }
  async function imageFor(name){ try{ const r=await fetch('/api/image?title='+encodeURIComponent(name)); const d=await r.json(); return d.ok && d.image ? `<img class="ctx-image" src="${esc(d.image)}" alt="${esc(d.title)}"><div class="source-line">image/source: <a target="_blank" href="${esc(d.source)}">Wikipedia/Wikimedia</a></div>` : '<div class="warn">No verified location image available. No stock image shown.</div>'; }catch(e){ return '<div class="warn">No verified image available.</div>'; } }
  async function renderNode(n){ const img=await imageFor(n.imageTitle||n.name); Panels.setInfo(n.name, `${img}<div class="info-card"><h3>${esc(n.name)}</h3><p>${esc(n.note)}</p><p><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</p><p class="source-line">${esc(n.source||'baseline map node')}</p></div>${eventList((window.APP_STATE?.events||[]).filter(e=>distance(n.lat,n.lng,e.lat,e.lng)<8).slice(0,12))}`); }
  function renderRoute(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><p><b>Goods:</b> ${esc(r.goods)}</p><p><b>Direction:</b> ${esc(r.direction||'two-way / lane varies')}</p><p><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</p><p><b>Why it matters:</b> ${esc(r.reason||'Route stress can change costs, delivery times, fuel demand and insurance premiums.')}</p><p><b>Verify:</b> ${esc(r.verify||'Check route-specific source reports before acting.')}</p></div>${eventList((window.APP_STATE?.events||[]).filter(e=>r.watch?.some(w=>(e.watch||[]).includes(w))).slice(0,8))}`); }
  function renderEvent(e){ Panels.setInfo(e.kind.toUpperCase(), `<div class="info-card"><h3>${esc(e.title)}</h3><p>${esc(e.summary||'')}</p><p><b>Place:</b> ${esc(e.place)}</p><p><b>Watch:</b> ${(e.watch||[]).map(esc).join(', ')}</p><p class="source-line">${sourceList(e.sources||[{name:e.source,url:e.url}])} · ${esc(e.time||'')}</p></div>`); }
  async function renderContext(data){ const title=data.reverse?.place?.split(',').slice(0,2).join(', ') || data.country?.name || 'Area'; const img=await imageFor(title.split(',')[0]); let safety=data.safety||{}; const html=`${img}<div class="info-card"><h3>${esc(title)}</h3><p>${esc(data.country?.summary||'No country brief loaded. Nearby dots and source feeds are shown below.')}</p><p><b>Watch:</b> ${(data.country?.watches||[]).map(esc).join(', ')}</p></div><div class="safety-panel ${esc(safety.level||'green')}"><h3>Safety light: ${(safety.level||'green').toUpperCase()}</h3><p>${esc(safety.explain||'No verified risk feed near this point.')}</p></div>${data.crime?.ok?`<div class="info-card"><h3>Crime feed</h3><p>${esc(data.crime.summary)}</p><p class="source-line">${esc(data.crime.source)}</p></div>`:`<div class="warn">No verified local crime feed for this area. UK points use data.police.uk where available; global city crime needs a licensed source.</div>`}<h3>Nearby latest reports</h3>${eventList(data.nearEvents||[])}<h3>Nearby nodes</h3>${[...(data.nearCities||[]),...(data.nearNodes||[])].slice(0,14).map(n=>`<div class="info-card"><b>${esc(n.name)}</b><p>${esc(n.note)}</p><p>Watch: ${(n.watch||[]).map(esc).join(', ')}</p></div>`).join('')}`; Panels.setInfo(title, html); }
  function distance(a,b,c,d){ return Math.hypot((a-c)*1.2,b-d); }
  return { renderTicker, renderMarkets, renderPolymarket, renderSignals, renderRapid, openPanel, renderNode, renderRoute, renderEvent, renderContext };
})();
