window.Renderers = (() => {
  const esc = s => String(s??'').replace(/[&<>"']/g,m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[m]));
  const money = n => Number.isFinite(Number(n)) ? '$' + Number(n).toLocaleString(undefined,{maximumFractionDigits:Number(n)<10?4:2}) : '—';
  const pct = n => Number(n||0);
  const arrow = n => `<span class="${pct(n)>=0?'up':'down'}">${pct(n)>=0?'▲':'▼'} ${Math.abs(pct(n)).toFixed(2)}%</span>`;
  const kindLabel = { war:'War', terror:'Terror', disaster:'Disaster', election:'Election', shipping:'Shipping', energy:'Energy', ai:'AI', tech:'AI', commodity:'Commodity', finance:'Finance', city:'City' };
  function groupMarkets(kind){ const list=(window.APP_STATE?.markets||[]); return list.filter(m=> kind==='all' || m.group===kind || m.type===kind || (kind==='crypto'&&m.source==='Binance')); }
  function renderTicker(markets){ document.getElementById('ticker').innerHTML=(markets||[]).slice(0,22).map(m=>`<span><b>${esc(m.id)}</b> ${money(m.price)} ${arrow(m.changePct)}</span>`).join('') || '<span>No market data</span>'; }
  function renderMarkets(markets){ renderTicker(markets); }
  function marketTable(list){ return `<div class="market-table">${(list||[]).map(m=>`<div class="market-row"><div class="sym">${esc(m.id)}</div><div><div class="name">${esc(m.name)}</div><div class="sub">${esc(m.source)} · ${esc(m.status||'unknown')} ${m.ageSec?`· ${m.ageSec}s old`:''}</div></div><div class="price"><b>${money(m.price)}</b><br>${arrow(m.changePct)}</div></div>`).join('') || '<div class="warn">No feed result. Check API/network status.</div>'}</div>`; }
  function sourceList(sources){ return (sources||[]).map(s=>`<a target="_blank" href="${esc(s.url||'#')}">${esc(s.name||s.source||'source')}</a>`).join(' · ') || 'source pending'; }
  function fmtNum(n){ return Number.isFinite(Number(n)) ? Number(n).toLocaleString(undefined,{maximumFractionDigits:2}) : '—'; }
  function scoreClass(score){ score=Number(score||0); if(score>=75) return 'green'; if(score>=55) return 'yellow'; if(score>=35) return 'orange'; return 'red'; }
  function riskClass(level){ const x=String(level||'').toLowerCase(); if(['green','low','safer'].includes(x)) return 'green'; if(['yellow','monitor','medium'].includes(x)) return 'yellow'; if(['orange','high-risk'].includes(x)) return 'orange'; return 'red'; }
  function scoreLabel(score, highGood=true){ score=Number(score||0); if(highGood) return score>=75?'Strong':score>=55?'Okay':score>=35?'Weak':'Poor'; return score>=75?'High risk':score>=55?'Watch':score>=35?'Moderate':'Lower'; }
  function isForeignText(t){ const s=String(t||''); if(!s) return false; const nonAscii=(s.match(/[^\x00-\x7F]/g)||[]).length; return nonAscii/Math.max(s.length,1) > .08; }
  function plainEventTitle(e){ const kind = kindLabel[e.kind] || 'Event'; const place = e.place ? ` near ${e.place}` : ''; if(isForeignText(e.title)) return `${kind} report${place}`; return String(e.title||`${kind} report${place}`).slice(0,130); }
  function plainSummary(e){ if(isForeignText(e.summary||e.title)) return `Source is not in English. Category: ${kindLabel[e.kind]||'Event'}. Location: ${e.place||'mapped area'}. Open the source before acting.`; return String(e.summary||e.title||'Source-backed event.').slice(0,260); }
  function eventCard(e){ const cls=e.kind==='war'?'red':e.kind==='terror'?'orange':e.kind==='disaster'?'yellow':'blue'; return `<div class="info-card"><h3>${esc(plainEventTitle(e))}</h3><div class="quick-list"><div class="quick-item ${cls}"><b>Type:</b> ${esc(kindLabel[e.kind]||e.kind||'Event')} · <b>Place:</b> ${esc(e.place||'mapped area')}</div><div class="quick-item"><b>What happened:</b> ${esc(plainSummary(e))}</div><div class="quick-item"><b>Check:</b> open source + look for market reaction before acting.</div></div><p class="action-line"><b>Markets to watch:</b> ${(e.watch||[]).map(esc).join(', ') || 'none mapped yet'}</p>${isForeignText(e.title)?`<p class="original-title"><b>Original title:</b> ${esc(e.title)}</p>`:''}<p class="source-box">${sourceList(e.sources||[{name:e.source,url:e.url}])}</p></div>`; }
  function eventList(events){ return (events||[]).map(eventCard).join('') || '<div class="warn">No source-backed events loaded in this category.</div>'; }
  function nationalBlock(n){ if(!n) return ''; const h=n.homicide?fmtNum(n.homicide.value):null; const pop=n.population?fmtNum(n.population.value):null; const gdp=n.gdpPerCapita?fmtNum(n.gdpPerCapita.value):null; return `<div class="info-card"><h3>Country averages</h3><div class="quick-list"><div class="quick-item"><b>Homicide:</b> ${h?`${h} per 100k (${esc(n.homicide.year)})`:'not published in feed'}</div><div class="quick-item"><b>Population:</b> ${pop||'not published'}</div><div class="quick-item"><b>GDP per person:</b> ${gdp?`$${gdp}`:'not published'}</div></div><p class="source-box">Country-level only. It cannot show safe/unsafe streets.</p></div>`; }
  function routeControls(){ return `<p class="plain">Routes are off by default. Tick only the routes you want.</p><div class="toggle-row"><label><input type="checkbox" id="seaToggle" ${window.SHOW_SEA?'checked':''}> Sea routes</label><label><input type="checkbox" id="landToggle" ${window.SHOW_LAND?'checked':''}> Land routes</label></div>`; }
  function riskLegend(){ return `<div class="safety-key"><span class="risk-pill red">WAR</span><span class="risk-pill orange">TERROR</span><span class="risk-pill yellow">WATCH</span><span class="risk-pill green">LOWER RISK</span></div>`; }
  function openPanel(name){
    const state=window.APP_STATE||{};
    if(name==='crypto'){
      Panels.setDrawer('Crypto', `<p class="plain">Use this for liquid crypto only. Green/red ticker shows direction. Do not use fallback data for entries.</p>${marketTable(groupMarkets('crypto'))}<div id="cryptoCharts"></div>`, 'crypto');
      const k=state.klines||{}; Charts.grid('cryptoCharts', ['BTCUSDT','ETHUSDT','SOLUSDT','XRPUSDT','BNBUSDT','ADAUSDT','DOGEUSDT'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='commodities'){
      Panels.setDrawer('Commodities', `<p class="plain">Use these to confirm real-world pressure: oil, copper, gold, silver, uranium and energy stocks.</p>${marketTable(groupMarkets('commodity'))}<div id="commodityCharts"></div>`, 'commodities');
      const k=state.klines||{}; Charts.grid('commodityCharts', ['HG=F','BZ=F','GC=F','SI=F','URA','USO'].map(x=>({title:x,data:k[x]||[],y:'price'})) ); return;
    }
    if(name==='polymarket') return Panels.setInfo('Polymarket', `<p class="plain">Use probabilities as a crowd signal, not truth. Stronger setup = odds move + source-backed news + asset move.</p>${(state.polymarket||[]).slice(0,45).map(p=>`<div class="info-card"><h3>${esc(p.question)}</h3><div class="index-grid"><div class="index-tile blue"><div class="label">volume</div><div class="num">${Math.round((p.volume||0)/1000)}k</div></div><div class="index-tile blue"><div class="label">liquidity</div><div class="num">${Math.round((p.liquidity||0)/1000)}k</div></div><div class="index-tile yellow"><div class="label">use</div><div class="tag">check price reaction</div></div></div><a target="_blank" href="${esc(p.url||'#')}">open market</a></div>`).join('')||'<div class="warn">No Polymarket data loaded.</div>'}`, 'polymarket');
    if(name==='routes') return Panels.setInfo('Routes', `${routeControls()}<div class="route-list">${(window.ROUTES||[]).map(r=>`<div class="info-card route-chip" data-route="${esc(r.id)}"><h3>${esc(r.name)}</h3><div class="quick-list"><div class="quick-item"><b>Goods:</b> ${esc(r.goods)}</div><div class="quick-item"><b>Direction:</b> ${esc(r.direction||'two-way')}</div><div class="quick-item"><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</div><div class="quick-item"><b>Check:</b> ${esc(r.verify||'confirm with freight/routing/source updates')}</div></div></div>`).join('')}</div>`, 'routes');
    if(name==='layers') return Panels.setInfo('Safety map', `${riskLegend()}<p class="plain">Shows country-level safety colours and incident dots. UK local crime appears where police.uk has data. Missing local data is shown as unknown, not guessed.</p><div class="toggle-row"><label><input checked data-layer="risk" type="checkbox"> Conflict countries</label><label><input id="safetyToggle" type="checkbox"> Safety colours</label><label><input checked data-layer="events" type="checkbox"> Event dots</label></div>`, 'layers');
    if(name==='rapid'){
      Panels.setDrawer('Rapid movers', `<p class="plain">Fast moving assets only. The chart is a scenario estimate, not a promise.</p>${(state.rapid||[]).map((r,i)=>`<div class="rapid-card"><h3>${esc(r.asset)} · ${esc(r.label)}</h3><div class="index-grid"><div class="index-tile green"><div class="label">continue</div><div class="num">${esc(r.continuation)}%</div></div><div class="index-tile red"><div class="label">reverse</div><div class="num">${esc(r.drop)}%</div></div><div class="index-tile blue"><div class="label">verify</div><div class="tag">${(r.checks||[])[0]||'check market'}</div></div></div><p><b>Reason:</b> ${(r.reasons||[]).map(esc).join(' · ')}</p><div class="chart-box"><canvas id="rapidChart${i}"></canvas><p class="chart-note">x-axis: projected steps · y-axis: price</p></div></div>`).join('')||'<div class="warn">No rapid movers yet.</div>'}`, 'rapid');
      setTimeout(()=> (state.rapid||[]).forEach((r,i)=>Charts.line(`rapidChart${i}`, r.projection||[], r.asset, 'price')),80); return;
    }
  }
  function renderLocalPlace(p){ Panels.setInfo(p.name, `<div class="info-card"><h3>${esc(p.name)}</h3><div class="quick-list"><div class="quick-item"><b>Type:</b> ${esc(p.tags?.place || p.tags?.amenity || p.kind || 'local place')}</div><div class="quick-item"><b>Source:</b> ${esc(p.source || 'OpenStreetMap')}</div>${p.tags?.population?`<div class="quick-item"><b>Population:</b> ${esc(p.tags.population)}</div>`:''}</div><p class="plain">For safety, click the surrounding map. The app uses official local crime feeds only where available.</p></div>`, 'local'); }
  function renderNode(n){ fetch('/api/image?title='+encodeURIComponent(n.imageTitle||n.name)).then(r=>r.json()).then(img=>{ Panels.setInfo(n.name, `${img.ok?`<img class="ctx-image" src="${esc(img.image)}"><p class="source-line">image/source: <a target="_blank" href="${esc(img.source)}">Wikipedia/Wikimedia</a></p>`:''}<div class="info-card"><h3>${esc(n.name)}</h3><div class="quick-list"><div class="quick-item"><b>Why it matters:</b> ${esc(n.note||'Monitoring node.')}</div><div class="quick-item"><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</div><div class="quick-item"><b>Source:</b> ${esc(n.source||'baseline')}</div></div></div>`, 'node'); }).catch(()=>Panels.setInfo(n.name, `<div class="info-card"><h3>${esc(n.name)}</h3><p>${esc(n.note||'Monitoring node.')}</p></div>`, 'node')); }
  function renderEvent(e){ Panels.setInfo(plainEventTitle(e), eventList([e]), 'event'); }
  function renderRoute(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><div class="quick-list"><div class="quick-item"><b>Goods:</b> ${esc(r.goods)}</div><div class="quick-item"><b>Direction:</b> ${esc(r.direction||'two-way')}</div><div class="quick-item"><b>Watch:</b> ${(r.watch||[]).map(esc).join(', ')}</div><div class="quick-item"><b>Check:</b> ${esc(r.verify||'confirm with freight/routing/source updates')}</div></div></div>`, 'routes'); }
  function renderRiskRegion(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><div class="quick-list"><div class="quick-item red"><b>Type:</b> ${esc(r.kind||'risk')}</div><div class="quick-item"><b>Status:</b> ${esc(r.level||'tracked')}</div><div class="quick-item"><b>Meaning:</b> ${esc(r.note||'Mapped risk region.')}</div></div><p class="source-box">${(r.sources||[]).map(esc).join(' · ')}</p></div>`, 'layers'); }
  function renderCountryConflict(c){ const english=c.englishName||c.name; const local=c.localName&&c.localName!==english?c.localName:''; Panels.setInfo(english, `<div class="info-card country-card"><h3>${esc(english)}${local?` <span class="subtle">/ ${esc(local)}</span>`:''}</h3><div class="index-grid"><div class="index-tile red"><div class="label">war risk</div><div class="num">90</div><div class="tag">active</div></div><div class="index-tile yellow"><div class="label">market impact</div><div class="num">65</div><div class="tag">watch</div></div><div class="index-tile orange"><div class="label">travel risk</div><div class="num">80</div><div class="tag">high</div></div></div><div class="quick-list"><div class="quick-item red"><b>Status:</b> ${esc(c.status||c.level||'tracked conflict')}</div><div class="quick-item"><b>Meaning:</b> ${esc(c.note||'Country-level conflict overlay.')}</div><div class="quick-item"><b>Watch:</b> ${(c.watch||[]).map(esc).join(', ') || 'event dots and related markets'}</div></div><p class="source-box">Country polygon is boundary-level colouring, not exact frontlines.</p></div>`, 'layers'); }
  function renderSafetyCountry(c){ const english=c.englishName||c.name; const local=c.localName&&c.localName!==english?c.localName:''; const crimeIndex=c.crimeIndex|| (c.level==='red'?22:c.level==='orange'?38:c.level==='yellow'?58:74); const safetyIndex=c.safetyIndex|| (c.level==='red'?25:c.level==='orange'?45:c.level==='yellow'?60:78); const economyIndex=c.economyIndex|| (c.marketIndex||55); Panels.setInfo(english, `<div class="info-card country-card"><h3>${esc(english)}${local?` <span class="subtle">/ ${esc(local)}</span>`:''}</h3><div class="index-grid"><div class="index-tile ${scoreClass(safetyIndex)}"><div class="label">safety</div><div class="num">${Math.round(safetyIndex)}</div><div class="tag">${scoreLabel(safetyIndex,true)}</div></div><div class="index-tile ${scoreClass(crimeIndex)}"><div class="label">crime data</div><div class="num">${Math.round(crimeIndex)}</div><div class="tag">${scoreLabel(crimeIndex,true)}</div></div><div class="index-tile ${scoreClass(economyIndex)}"><div class="label">money lanes</div><div class="num">${Math.round(economyIndex)}</div><div class="tag">${scoreLabel(economyIndex,true)}</div></div></div><div class="quick-list"><div class="quick-item ${riskClass(c.level)}"><b>Map colour:</b> ${esc(String(c.level||'unknown').toUpperCase())}</div><div class="quick-item"><b>Safety:</b> ${esc(c.safetyRead||c.note||'Country-level only. Local street crime requires official local feed.')}</div><div class="quick-item"><b>Money:</b> ${esc(c.marketRead||'Check crypto, commodities, routes and Polymarket for direct market reaction.')}</div><div class="quick-item"><b>Crime feed:</b> ${esc(c.crimeFeed||'Official local crime feed not connected for this country.')}</div></div><p class="source-box">No guessed street-level crime. UK uses police.uk where available; other countries need official feeds.</p></div>`, 'layers'); }
  function renderSafetyRegion(r){ Panels.setInfo(r.name, `<div class="info-card"><h3>${esc(r.name)}</h3><div class="index-grid"><div class="index-tile ${riskClass(r.level)}"><div class="label">safety</div><div class="num">${r.level==='green'?75:r.level==='yellow'?55:30}</div><div class="tag">${esc(r.level||'unknown')}</div></div></div><p>${esc(r.note||'Safety region.')}</p></div>`, 'layers'); }
  function renderContext(d){
    const place=d?.reverse?.place||'Selected area'; const country=d?.country?.englishName||d?.country?.name||'Unknown country'; const localCountry=d?.country?.localName||(d?.reverse?.address?.country&&d.reverse.address.country!==country?d.reverse.address.country:'');
    const events=(d.nearEvents||d.nearbyEvents||[]).slice(0,18); const countryEvents=(d.inCountryEvents||[]).slice(0,24); const nodes=(d.nearNodes||d.nearbyNodes||[]).slice(0,10); const cities=(d.nearCities||[]).slice(0,10);
    const hasWar=[...events,...countryEvents].some(e=>e.kind==='war'); const hasTerror=[...events,...countryEvents].some(e=>e.kind==='terror'); const hasDisaster=[...events,...countryEvents].some(e=>e.kind==='disaster'); const crimeOK=!!d?.crime?.ok;
    const safetyIndex = d?.safety?.level==='red'?25:d?.safety?.level==='yellow'?55:hasWar||hasTerror?30:hasDisaster?50:70;
    const crimeIndex = crimeOK ? (d.crime.level==='red'?20:d.crime.level==='yellow'?50:75) : 45;
    const moneyIndex = Math.min(95, 35 + (nodes.length*3) + (countryEvents.length>8?18:countryEvents.length*2) + (hasWar||hasTerror?12:0));
    const crimeLine = crimeOK ? `${d.crime.count} official local crimes in latest police.uk month. ${d.crime.level.toUpperCase()} local crime signal.` : (d?.crime?.source||'No official local crime feed here.');
    const conflictLine = d.conflict ? `${d.conflict.status||d.conflict.level||'tracked'} — ${d.conflict.note||'conflict overlay active'}` : 'No active country-level conflict overlay in this build.';
    Panels.setInfo(country, `<div class="info-card country-card"><h3>${esc(country)}${localCountry?` <span class="subtle">/ ${esc(localCountry)}</span>`:''}</h3><p class="source-line">Clicked: ${esc(place)}</p><div class="index-grid"><div class="index-tile ${scoreClass(safetyIndex)}"><div class="label">safety</div><div class="num">${Math.round(safetyIndex)}</div><div class="tag">${scoreLabel(safetyIndex,true)}</div></div><div class="index-tile ${scoreClass(crimeIndex)}"><div class="label">crime info</div><div class="num">${Math.round(crimeIndex)}</div><div class="tag">${crimeOK?'official':'limited'}</div></div><div class="index-tile ${scoreClass(moneyIndex)}"><div class="label">money lanes</div><div class="num">${Math.round(moneyIndex)}</div><div class="tag">${scoreLabel(moneyIndex,true)}</div></div></div><div class="quick-list"><div class="quick-item ${hasWar?'red':hasTerror?'orange':hasDisaster?'yellow':'green'}"><b>Conflict:</b> ${esc(conflictLine)}</div><div class="quick-item"><b>Crime:</b> ${esc(crimeLine)}</div><div class="quick-item"><b>Events:</b> ${countryEvents.length} in country · ${events.length} near click</div><div class="quick-item"><b>Useful nearby places:</b> ${cities.map(c=>esc(c.name)).join(', ') || 'none loaded'}</div><div class="quick-item"><b>Money check:</b> compare event dots with Crypto, Commodities, Routes and Polymarket before acting.</div></div></div>${nationalBlock(d.national)}${eventList([...events,...countryEvents].slice(0,22))}${nodes.map(n=>`<div class="info-card"><h3>${esc(n.name)}</h3><div class="quick-list"><div class="quick-item"><b>Why:</b> ${esc(n.note)}</div><div class="quick-item"><b>Watch:</b> ${(n.watch||[]).map(esc).join(', ')}</div></div></div>`).join('')}`, 'context');
  }
  return { renderMarkets, openPanel, renderNode, renderLocalPlace, renderEvent, renderRoute, renderContext, renderRiskRegion, renderSafetyRegion, renderCountryConflict, renderSafetyCountry };
})();
