export const LIVE_DATA_STATES = Object.freeze({
  STARTING: 'STARTING', ONLINE: 'ONLINE', DEGRADED: 'DEGRADED', OFFLINE: 'OFFLINE',
  DISABLED: 'DISABLED', NOT_CONFIGURED: 'NOT_CONFIGURED', CACHED: 'CACHED'
});

export const ACCESS_CLASSES = Object.freeze({
  PUBLIC_KEYLESS: 'PUBLIC_KEYLESS', PUBLIC_REGISTRATION: 'PUBLIC_REGISTRATION',
  OPTIONAL_KEY: 'OPTIONAL_KEY', COMMERCIAL_LICENSE: 'COMMERCIAL_LICENSE'
});

export const DATA_DOMAINS = Object.freeze([
  'EVENTS', 'NEWS', 'HAZARDS', 'MARKETS', 'MACRO', 'POLITICS', 'SANCTIONS',
  'HUMANITARIAN', 'SHIPPING', 'TRADE', 'WEATHER', 'GEOGRAPHY'
]);

export const DEFAULT_PUBLIC_COUNTRIES = Object.freeze(['GB','US','CN','DE','FR','IN','JP','BR','SA','AE','TR','RU','EG','ZA','AU']);
