import crypto from 'node:crypto';
import { id } from '../util/id.js';
import { parseCsv, normaliseStoreCsv } from './csv.js';

function safeJson(v,f={}){try{return JSON.parse(v||JSON.stringify(f));}catch{return f;}}
function moneyObj(v){if(!v)return null;const amount=Number(v.amount),divisor=Number(v.divisor||100);return Number.isFinite(amount)&&Number.isFinite(divisor)&&divisor?amount/divisor:null;}
function matchProduct(db,code,title){if(code){const p=db.prepare('SELECT id,product_code,name FROM products WHERE upper(product_code)=upper(?)').get(code);if(p)return p;}if(title){const exact=db.prepare('SELECT id,product_code,name FROM products WHERE lower(name)=lower(?)').get(title);if(exact)return exact;}return null;}
function dedupeInsert(db,t){const old=db.prepare('SELECT id FROM store_transactions WHERE platform=? AND external_id=?').get(t.platform,t.external_id);if(old)return {status:'duplicate',id:old.id};const product=matchProduct(db,t.product_code,t.title);const sid=id('STX');db.prepare(`INSERT INTO store_transactions (id,platform,external_id,product_id,product_code_raw,title,quantity,gross_revenue,fees,shipping_cost,refunds,currency,sold_at,raw_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(sid,t.platform,t.external_id,product?.id||null,t.product_code||null,t.title||null,Number(t.quantity||1),t.gross_revenue,t.fees||0,t.shipping_cost||0,t.refunds||0,t.currency||'GBP',t.sold_at||new Date().toISOString(),JSON.stringify(t.raw||{}));
  let saleId=null;if(t.gross_revenue!=null){saleId=id('SALE');db.prepare(`INSERT INTO sales_events (id,product_id,channel,quantity,gross_revenue,fees,shipping_cost,refunds,currency,sold_at,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(saleId,product?.id||null,t.platform,Number(t.quantity||1),Number(t.gross_revenue),Number(t.fees||0),Number(t.shipping_cost||0),Number(t.refunds||0),t.currency||'GBP',t.sold_at||new Date().toISOString(),`Imported from ${t.platform}: ${t.external_id}`);db.prepare('UPDATE store_transactions SET sale_event_id=? WHERE id=?').run(saleId,sid);}
  return {status:'created',id:sid,sale_id:saleId,product};}

export function importStoreCsv(db,platform,buffer,filename){const runId=id('SIMP');const text=buffer.toString('utf8');const rows=normaliseStoreCsv(platform,parseCsv(text));let created=0,duplicates=0,unmatched=0;const results=[];for(const row of rows){const r=dedupeInsert(db,row);if(r.status==='created'){created++;if(!r.product)unmatched++;}else duplicates++;results.push({...r,external_id:row.external_id,title:row.title});}db.prepare(`INSERT INTO store_import_runs (id,platform,mode,filename,row_count,created_count,duplicate_count,unmatched_count,status) VALUES (?,?,?,?,?,?,?,?,'success')`).run(runId,platform,'csv',filename,rows.length,created,duplicates,unmatched);return {run_id:runId,row_count:rows.length,created,duplicates,unmatched,results:results.slice(0,50)};}

export function storeStatus(db){const platforms=['etsy','ebay','direct'];return platforms.map(platform=>{const row=db.prepare('SELECT * FROM store_connections WHERE platform=?').get(platform);const count=db.prepare('SELECT COUNT(*) n,COALESCE(SUM(gross_revenue-refunds),0) revenue FROM store_transactions WHERE platform=?').get(platform);return {platform,status:row?.status||'not_connected',mode:row?.mode||null,shop_name:row?.shop_name||null,last_synced_at:row?.last_synced_at||null,transactions:Number(count.n||0),revenue:Number(count.revenue||0),api_available:platform==='etsy'?Boolean(process.env.ETSY_KEYSTRING&&process.env.ETSY_SHARED_SECRET&&process.env.ETSY_SHOP_ID):platform==='ebay'?Boolean(process.env.EBAY_ACCESS_TOKEN):false};});}

export async function syncEtsy(db){const key=process.env.ETSY_KEYSTRING,secret=process.env.ETSY_SHARED_SECRET,shopId=process.env.ETSY_SHOP_ID,token=process.env.ETSY_ACCESS_TOKEN;if(!key||!secret||!shopId||!token)throw new Error('Etsy API is not configured. Set ETSY_KEYSTRING, ETSY_SHARED_SECRET, ETSY_SHOP_ID and ETSY_ACCESS_TOKEN, or use CSV import.');
  const headers={'x-api-key':`${key}:${secret}`,Authorization:`Bearer ${token}`,accept:'application/json'};let offset=0,created=0,duplicates=0,unmatched=0,total=0;for(let page=0;page<10;page++){const url=new URL(`https://openapi.etsy.com/v3/application/shops/${shopId}/transactions`);url.searchParams.set('limit','100');url.searchParams.set('offset',String(offset));const r=await fetch(url,{headers});if(!r.ok)throw new Error(`Etsy sync failed ${r.status}: ${await r.text()}`);const data=await r.json();const rows=data.results||[];if(!rows.length)break;for(const x of rows){const unitPrice=moneyObj(x.price);const gross=unitPrice==null?null:unitPrice*Number(x.quantity||1);const t={platform:'etsy',external_id:String(x.transaction_id),title:x.title||null,sku:x.product_data?.[0]?.sku||null,product_code:(String(x.product_data?.[0]?.sku||x.title||'').match(/\b[A-Z0-9]{2,6}-\d{3,6}\b/i)||[])[0]?.toUpperCase()||null,quantity:Number(x.quantity||1),gross_revenue:gross,fees:0,shipping_cost:0,refunds:0,currency:x.price?.currency_code||'GBP',sold_at:new Date(Number(x.created_timestamp||x.create_timestamp||Date.now()/1000)*1000).toISOString(),raw:x};const rr=dedupeInsert(db,t);total++;if(rr.status==='created'){created++;if(!rr.product)unmatched++;}else duplicates++;}if(rows.length<100)break;offset+=100;}
  db.prepare(`INSERT INTO store_connections (platform,status,mode,shop_name,last_synced_at,config_json) VALUES ('etsy','connected','api',?,CURRENT_TIMESTAMP,'{}') ON CONFLICT(platform) DO UPDATE SET status='connected',mode='api',shop_name=excluded.shop_name,last_synced_at=CURRENT_TIMESTAMP`).run(`Etsy shop ${shopId}`);return {platform:'etsy',total,created,duplicates,unmatched};}

export async function syncEbay(db){const token=process.env.EBAY_ACCESS_TOKEN;if(!token)throw new Error('eBay API is not configured. Set EBAY_ACCESS_TOKEN or use CSV import.');const headers={Authorization:`Bearer ${token}`,accept:'application/json','content-type':'application/json','X-EBAY-C-MARKETPLACE-ID':process.env.EBAY_MARKETPLACE_ID||'EBAY_GB'};let offset=0,created=0,duplicates=0,unmatched=0,total=0;for(let page=0;page<10;page++){const url=new URL('https://api.ebay.com/sell/fulfillment/v1/order');url.searchParams.set('limit','200');url.searchParams.set('offset',String(offset));const r=await fetch(url,{headers});if(!r.ok)throw new Error(`eBay sync failed ${r.status}: ${await r.text()}`);const data=await r.json();const orders=data.orders||[];if(!orders.length)break;for(const o of orders){for(const li of o.lineItems||[]){const code=(String(li.sku||li.title||'').match(/\b[A-Z0-9]{2,6}-\d{3,6}\b/i)||[])[0]?.toUpperCase()||null;const amount=Number(li.lineItemCost?.value||li.total?.value||0);const t={platform:'ebay',external_id:`${o.orderId}:${li.lineItemId}`,title:li.title||null,sku:li.sku||null,product_code:code,quantity:Number(li.quantity||1),gross_revenue:Number.isFinite(amount)?amount:null,fees:0,shipping_cost:0,refunds:0,currency:li.lineItemCost?.currency||'GBP',sold_at:o.creationDate||new Date().toISOString(),raw:{order:o,lineItem:li}};const rr=dedupeInsert(db,t);total++;if(rr.status==='created'){created++;if(!rr.product)unmatched++;}else duplicates++;}}if(orders.length<200)break;offset+=200;}
  db.prepare(`INSERT INTO store_connections (platform,status,mode,shop_name,last_synced_at,config_json) VALUES ('ebay','connected','api','eBay',CURRENT_TIMESTAMP,'{}') ON CONFLICT(platform) DO UPDATE SET status='connected',mode='api',last_synced_at=CURRENT_TIMESTAMP`).run();return {platform:'ebay',total,created,duplicates,unmatched};}

export function analytics(db,{days=365}={}){const d=Math.max(7,Math.min(3650,Number(days)||365));const daily=db.prepare(`SELECT date(sold_at) day,channel,COALESCE(SUM(quantity),0) units,COALESCE(SUM(gross_revenue-refunds),0) revenue,COALESCE(SUM(fees+shipping_cost),0) costs FROM sales_events WHERE datetime(sold_at)>=datetime('now',?) GROUP BY date(sold_at),channel ORDER BY day`).all(`-${d} days`);const channels=db.prepare(`SELECT COALESCE(channel,'unknown') channel,COALESCE(SUM(quantity),0) units,COALESCE(SUM(gross_revenue-refunds),0) revenue,COALESCE(SUM(fees+shipping_cost),0) costs,COUNT(*) events FROM sales_events WHERE datetime(sold_at)>=datetime('now',?) GROUP BY channel ORDER BY revenue DESC`).all(`-${d} days`);const products=db.prepare(`SELECT p.product_code,p.name,COALESCE(SUM(s.quantity),0) units,COALESCE(SUM(s.gross_revenue-s.refunds),0) revenue,COALESCE(SUM(s.fees+s.shipping_cost),0) costs FROM sales_events s LEFT JOIN products p ON p.id=s.product_id WHERE datetime(s.sold_at)>=datetime('now',?) GROUP BY s.product_id ORDER BY revenue DESC LIMIT 30`).all(`-${d} days`);const ads=db.prepare(`SELECT platform,date,COALESCE(SUM(spend),0) spend,COALESCE(SUM(impressions),0) impressions,COALESCE(SUM(clicks),0) clicks,COALESCE(SUM(attributed_revenue),0) attributed_revenue,COALESCE(SUM(attributed_orders),0) attributed_orders FROM ad_metrics WHERE date>=date('now',?) GROUP BY platform,date ORDER BY date`).all(`-${d} days`);return {days:d,daily,channels,products,ads};}

export function recordAdMetric(db,p){const aid=id('AD');db.prepare(`INSERT INTO ad_metrics (id,platform,date,campaign,spend,impressions,clicks,attributed_orders,attributed_revenue,currency,raw_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(aid,p.platform,p.date||new Date().toISOString().slice(0,10),p.campaign||null,Number(p.spend||0),Number(p.impressions||0),Number(p.clicks||0),Number(p.attributed_orders||0),Number(p.attributed_revenue||0),p.currency||'GBP',JSON.stringify(p.raw||{}));return db.prepare('SELECT * FROM ad_metrics WHERE id=?').get(aid);}
