import test from 'node:test';
import assert from 'node:assert/strict';
import { createPublishingPlatformService } from '../../src/services/publishing-platform-service.js';
import { decisionSupportStub, publicationFixture, subscriberFixture } from './fixtures.js';

function platform() { return createPublishingPlatformService({ decisionSupport: decisionSupportStub(), fetchImpl: async () => ({ ok: true, status: 200 }) }); }

test('platform seeds publication assets and reports diagnostics', async () => { const service = platform(); const seeded = await service.seed('u'); assert.equal(seeded.templates.length, 3); const diagnostics = await service.diagnostics('u'); assert.equal(diagnostics.status, 'READY'); assert.equal(diagnostics.metrics.publications, 1); });
test('platform generates, approves and publishes an edition', async () => { const service = platform(); await service.publications.put('u', publicationFixture()); const edition = await service.generateEdition('u', { publicationId: 'publication-test' }); assert.equal(edition.blocks[0].type, 'EXECUTIVE_SUMMARY'); await service.approveEdition('u', edition.id, { state: 'APPROVED' }); const result = await service.publishEdition('u', edition.id, {}); assert.equal(result.published, true); assert.equal(result.edition.state, 'PUBLISHED'); });
test('platform creates and validates secure share links', async () => { const service = platform(); await service.publications.put('u', { ...publicationFixture(), approvalRequired: false }); const edition = await service.generateEdition('u', { publicationId: 'publication-test' }); const share = await service.createShare('u', { editionId: edition.id, passcode: 'secret' }); assert.ok(share.url.includes('/publication/share/')); const access = await service.accessShare(share.token, { passcode: 'secret', clearance: 'CLIENT' }); assert.equal(access.allowed, true); assert.equal(access.edition.id, edition.id); });
test('platform delivers personalized editions and records analytics', async () => { const service = platform(); await service.publications.put('u', { ...publicationFixture(), approvalRequired: false }); await service.subscribers.put('u', subscriberFixture()); const edition = await service.generateEdition('u', { publicationId: 'publication-test' }); const result = await service.deliverEdition('u', { editionId: edition.id, subscriberIds: ['subscriber-test'], channels: ['IN_APP', 'SECURE_LINK'] }); assert.equal(result.recipients, 1); assert.ok(result.results.some(item => item.state === 'DELIVERED')); const analytics = await service.analytics.summary('u'); assert.ok(analytics.delivered >= 1); });
test('platform snapshot exposes publishing operating state', async () => { const service = platform(); await service.seed('u'); const snapshot = await service.snapshot('u'); assert.equal(snapshot.publications.length, 1); assert.equal(snapshot.templates.length, 3); assert.equal(snapshot.diagnostics.platform, 'MERLIN_PUBLISHING'); });
