import {EVENT_TAXONOMY} from '../catalog/event-taxonomy.js';import {PUBLIC_SIGNAL_INDICATORS} from '../catalog/public-signal-indicators.js';import {TRANSMISSION_RULES} from '../catalog/market-transmission.js';import {SOURCE_POLICY} from '../catalog/source-policy.js';import {clamp,tokens} from '../core/utils.js';
const categoryRules={
 conflict:['attack','strike','missile','drone','military','war ','troops','navy','air force','blockade','ceasefire','mobilis','shelling','invasion','interceptor'],
 maritime:['shipping','ship ','vessel','tanker','port ','canal','strait','freight','container','maritime','suez','hormuz','red sea','danube'],
 sanctions:['sanction','export control','asset freeze','designation','embargo','blacklist','trade restriction'],
 cyber:['cyber','hack','ransomware','malware','vulnerability','cve-','digital attack','subsea cable','gps interference'],
 energy:['oil','gas','lng','refinery','pipeline','energy','power grid','crude','petroleum','fuel shortage'],
 markets:['market','stocks','equities','bond','yield','inflation','rate hike','interest rate','currency','dollar','yen','euro','bitcoin','trade deficit'],
 policy:['tariff','election','government','minister','parliament','central bank','federal reserve','boj','treaty','diplomatic','trade deal','policy'],
 hazard:['earthquake','wildfire','hurricane','flood','volcano','storm']
};

const RULE_ANCHORS={
 'tx-01':['hormuz','strait'], 'tx-02':['red sea','bab el-mandeb','houthi','shipping attack'], 'tx-03':['suez','canal closure','canal traffic'],
 'tx-04':['sanctions','ofac','oil exports'], 'tx-05':['ceasefire','talks','agreement','nuclear deal','de-escalation'], 'tx-06':['missile','airstrike','retaliation','attack','strike'],
 'tx-07':['missile','offensive','mobilisation','attack','attacks','strike','strikes'], 'tx-08':['sanctions','secondary sanctions','oil price cap'], 'tx-09':['pipeline','refinery','terminal'],
 'tx-10':['rate hike','hawkish'], 'tx-11':['rate cut','dovish'], 'tx-12':['rate hike','hawkish','inflation'], 'tx-13':['rate cut','dovish'],
 'tx-14':['tariff','import duty','trade war'], 'tx-15':['export control','semiconductor','advanced chip','ai chip','lithography'], 'tx-16':['blockade','exercise','missile','strait'],
 'tx-17':['talks','de-escalation','dialogue'], 'tx-18':['missile','nuclear test','artillery','dmz'], 'tx-19':['rate hike','yield curve','rate expectations','intervention'],
 'tx-20':['stimulus','reserve requirement','property support','fiscal support'], 'tx-21':['developer default','property crisis','home sales'],
 'tx-22':['collision','water cannon','shoal','blockade'], 'tx-23':['malacca','port closure','shipping accident','blockage'], 'tx-24':['cyberattack','critical infrastructure','grid','telecom','port system'],
 'tx-25':['port strike','dockworker strike','port closure','labour dispute'], 'tx-26':['enrichment','uranium','centrifuge','inspectors','nuclear facility'],
 'tx-27':['default','debt restructuring','capital controls','sovereign debt'], 'tx-28':['airspace closed','flight suspension','notam','airline cancels'],
 'tx-29':['production cut','output cut','quota'], 'tx-30':['terminal outage','liquefaction outage','gas export'], 'tx-31':['rare earth','export ban','gallium','germanium','graphite'],
 'tx-32':['earthquake']
};
const extraIndicators=[
 ['waterway-control','maritime','Strategic waterway access dispute',91,['control of the strait','strait is under','blockade','closed strait','reopen the strait'],'Changes to access or claimed control at a strategic waterway can immediately affect shipping, insurance and energy pricing.',['naval authority notice','shipping advisories','independent vessel traffic data']],
 ['traffic-contraction','maritime','Maritime traffic contraction',88,['traffic fell','shipping disruption','vessel traffic','rerouting','shipping delays','container shortages'],'A sustained traffic reduction or rerouting can propagate into freight rates and inventory lead times.',['port/authority statistics','AIS-derived public summaries','carrier advisories']],
 ['cyber-campaign','cyber','Cyber campaign disclosure',82,['hacking campaign','cyber campaign','cyberattack','ai-assisted cyber'],'A publicly disclosed campaign against government or infrastructure changes cyber-operational risk.',['national cyber authority','affected operator statement','technical indicators']],
 ['energy-strike','energy','Energy infrastructure strike',92,['refinery','pipeline','oil terminal','gas plant','power plant'],'Physical disruption to energy infrastructure can change regional supply and prices.',['operator status','official emergency notice','independent imagery/reporting']],
 ['anti-blockade-drill','defense','Blockade / resilience drill',80,['anti-blockade','war games','military drill','civil defence drill','naval drill'],'Exercises designed around blockade or invasion scenarios are visible indicators of contingency preparation.',['defence ministry','coast guard/navy release','independent reporting']],
 ['trade-policy','policy','Tariff / trade-policy change',78,['tariff','trade restriction','trade offer','export control'],'Trade-policy changes can alter company margins, supply routes and FX expectations.',['official tariff schedule','customs notice','counterparty statement']],
 ['fx-policy','markets','FX intervention / rate-policy shift',84,['intervention','rate hike','central bank','boj','federal reserve'],'Central-bank or intervention expectations can quickly reprice currencies, bonds and equities.',['central bank release','finance ministry','market pricing']],
 ['port-disruption','maritime','Port attack / disruption',90,['port infrastructure','port attack','port strike','port closure'],'Port disruption can constrain exports, raise freight costs and redirect flows.',['port authority','carrier notice','satellite/public imagery']],
 ['market-spillover','markets','Geopolitical market spillover',74,['markets ease','stocks rise','stocks fall','risk pricing','oil prices','equities'],'Cross-asset reaction helps distinguish materially market-relevant geopolitical developments.',['exchange/price feed','multiple market reports','sector pricing']]
].map(([id,lane,label,weight,patterns,why,verify])=>({id,lane,label,weight,patterns,why,verify}));
function phrase(text,p){p=String(p).toLowerCase();if(p.includes(' '))return text.includes(p);return tokens(text).includes(p.replace(/[^a-z0-9-]/g,''));}
export function classifyRecord(r,geo){const text=`${r.title||''} ${r.summary||''}`.toLowerCase().replace(/\bu\.s\./g,'united states').replace(/\bfed\b/g,'federal reserve').replace(/\bboj\b/g,'bank of japan');let best=null;for(const e of EVENT_TAXONOMY){if((e.excludeTerms||[]).some(x=>text.includes(x.toLowerCase())))continue;const matched=(e.terms||[]).filter(x=>phrase(text,x));if(matched.length){const score=(e.weight||0)+matched.length*3;if(!best||score>best.score)best={...e,matched,score};}}
 let category=r.presetCategory||best?.category||Object.entries(categoryRules).map(([c,arr])=>[c,arr.filter(x=>text.includes(x)).length]).sort((a,b)=>b[1]-a[1])[0]?.[0]||'policy';
 const categoryHits=Object.entries(categoryRules).map(([c,arr])=>[c,arr.filter(x=>text.includes(x)).length]).sort((a,b)=>b[1]-a[1]);if(categoryHits[0]?.[1]>0&&(!best||categoryHits[0][1]>=2))category=categoryHits[0][0];
 const indicators=[...PUBLIC_SIGNAL_INDICATORS,...extraIndicators].map(i=>{const matched=(i.patterns||[]).filter(p=>text.includes(String(p).toLowerCase()));return matched.length?{id:i.id,lane:i.lane,label:i.label,weight:i.weight,why:i.why,verify:i.verify,matched}:null;}).filter(Boolean).sort((a,b)=>b.weight-a.weight).slice(0,8);
 const transmissions=TRANSMISSION_RULES.map(t=>{const matched=(t.terms||[]).filter(x=>phrase(text,x));const minMatches=t.minMatches??((t.terms||[]).length>1?2:1);const anchor=(t.terms||[])[0],required=RULE_ANCHORS[t.id]||[];const anchorOK=!required.length||required.some(x=>phrase(text,x));const regionOK=!t.regions?.length||t.regions.includes('world')||t.regions.includes(geo.regionId)||(anchor&&phrase(text,anchor));if(!regionOK||!anchorOK||matched.length<minMatches)return null;const confidence=clamp((t.baseConfidence||.6)*(0.58+Math.min(.42,matched.length/Math.max(2,(t.terms||[]).length))),.35,.99);return{...t,matched,confidence};}).filter(Boolean).sort((a,b)=>b.confidence-a.confidence).slice(0,4);
 const policy=sourceQuality(r.sourceDomain);const ageH=Math.max(0,(Date.now()-Date.parse(r.publishedAt||0))/36e5);const freshness=Math.max(0,24-Math.min(24,ageH/7*24));const score=clamp(Math.round(26+(best?.weight||0)+(indicators[0]?.weight||0)*.28+transmissions.length*8+policy.quality*12+freshness*.45),25,99);return{category,eventType:best?.name||categoryLabel(category),taxonomyId:best?.id||null,publicIndicators:indicators,marketTransmission:transmissions,signalScore:score,priority:score>=78?'HIGH':score>=58?'MEDIUM':'LOW',sourceQuality:policy.quality,confidence:Math.round(clamp(52+policy.quality*24+indicators.length*2.5+transmissions.length*2,50,97))};}
export function sourceQuality(domain){const d=String(domain||'').replace(/^www\./,'');const p=SOURCE_POLICY.find(x=>d===x.domain||d.endsWith('.'+x.domain));return p||{quality:.55,class:'unrated',mode:'reporting'};}
function categoryLabel(c){return({conflict:'Security / conflict development',maritime:'Maritime / logistics development',sanctions:'Sanctions / trade restriction',cyber:'Cyber / infrastructure development',energy:'Energy development',markets:'Market / macro development',policy:'Policy / diplomatic development',hazard:'Material hazard'})[c]||'Material development';}
