export function buildWatchboard(signals=[],markets=[],predictions=[],coverage={}){
  const regions=aggregate(signals,s=>s.regionIds?.find(x=>x!=='world')||'world');const categories=aggregate(signals,s=>s.category||'other');const exposures=new Map();
  for(const s of signals)for(const row of s.intelligence?.exposures||[]){const v=exposures.get(row.id)||{id:row.id,name:row.name,kind:row.kind,count:0,maxRelevance:0,drivers:new Set()};v.count++;v.maxRelevance=Math.max(v.maxRelevance,Number(row.relevance||0));for(const d of row.drivers||[])v.drivers.add(d);exposures.set(row.id,v);}
  const exposureWatch=[...exposures.values()].map(x=>({...x,drivers:[...x.drivers]})).sort((a,b)=>b.maxRelevance-a.maxRelevance||b.count-a.count).slice(0,12);
  const routeWatch=signals.filter(s=>s.category==='shipping'||/port|shipping|tanker|canal|strait|maritime|rerout/i.test(`${s.title} ${s.summary}`)).sort((a,b)=>b.signalScore-a.signalScore).slice(0,8).map(s=>({id:s.id,title:s.title,score:s.signalScore,location:s.location?.name||'Regional',market:s.market?.assets?.slice(0,4)||[]}));
  const confirmationWatch=signals.filter(s=>(s.independentSources||0)>=2||s.officialPrimary).sort((a,b)=>b.signalScore-a.signalScore).slice(0,10).map(s=>({id:s.id,title:s.title,score:s.signalScore,sources:s.independentSources,official:s.officialPrimary,grade:s.evidenceGrade}));
  const predictionWatch=[...predictions].sort((a,b)=>(b.volume||0)-(a.volume||0)).slice(0,8).map(p=>({id:p.id,title:p.title,probability:p.probability,volume:p.volume,updatedAt:p.updatedAt,url:p.url}));
  return{high:signals.filter(s=>['HIGH','CRITICAL'].includes(s.urgency)).length,total:signals.length,regions,categories,exposureWatch,routeWatch,confirmationWatch,predictionWatch,markets:markets.slice(0,12),coverage};
}
function aggregate(rows,keyFn){const m=new Map();for(const row of rows){const k=keyFn(row),v=m.get(k)||{id:k,count:0,high:0,maxScore:0,_sum:0};v.count++;v._sum+=Number(row.signalScore||0);v.maxScore=Math.max(v.maxScore,Number(row.signalScore||0));if(['HIGH','CRITICAL'].includes(row.urgency))v.high++;m.set(k,v);}return[...m.values()].map(v=>({id:v.id,count:v.count,high:v.high,maxScore:v.maxScore,avgScore:Math.round(v._sum/v.count)})).sort((a,b)=>b.high-a.high||b.maxScore-a.maxScore||b.count-a.count);}
