import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {config} from './config.js';import {SOURCES} from './source-catalog.js';import {runner} from './adapters/index.js';import {runPool} from './core/http.js';import {loadStored,saveStored} from './core/storage.js';import {buildSnapshot} from './analysis/pipeline.js';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'..');
export class MerlinService{
 constructor(){this.sources=SOURCES;this.snapshot=null;this.refreshing=false;this.refreshPromise=null;this.startedAt=new Date().toISOString();this.timer=null;this.seed=null;this.countries=[];this.reference=null;}
 async init(){this.seed=JSON.parse(await fs.readFile(path.join(root,'seed','build-snapshot.json'),'utf8'));const names=['countries','cities','ports','routes','chokepoints','places'];const raw=await Promise.all(names.map(n=>fs.readFile(path.join(root,'public','data',`${n}.json`),'utf8').then(JSON.parse)));const [countries,cities,ports,routes,chokepoints,places]=raw;this.countries=countries.countries||countries;this.reference={countries:this.countries,cities:cities.cities||cities,ports:ports.ports||ports,routes,chokepoints:chokepoints.chokepoints||chokepoints,places:places.places||places};const stored=await loadStored();const seed=this.#seedSnapshot();this.snapshot=stored?.version==='8.0.0'&&Array.isArray(stored.signals)?mergeStoredWithSeed(stored,seed):seed;if(!config.disableLive){this.refresh('startup').catch(e=>console.error('startup refresh',e));this.timer=setInterval(()=>this.refresh('interval').catch(()=>{}),config.refreshMs);this.timer.unref?.();}return this;}
 #seedSnapshot(){const records=this.seed.records.map(r=>({...r,fallback:true,sourceId:`build:${r.sourceDomain}`}));const markets=this.seed.markets.map(m=>({...m,fallback:true}));const statuses=this.sources.map(s=>status(s,'seed',{checkedAt:null,error:null,itemCount:0}));return buildSnapshot({records,markets,predictions:[],sourceStatuses:statuses,countries:this.countries,reference:this.reference,seedMeta:{capturedAt:this.seed.capturedAt,notice:this.seed.notice}});}
 async refresh(reason='manual'){if(this.refreshPromise)return this.refreshPromise;this.refreshing=true;this.refreshPromise=this.#refresh(reason).finally(()=>{this.refreshing=false;this.refreshPromise=null;});return this.refreshPromise;}
 async #refresh(reason){const started=Date.now(),results=await runPool(this.sources.map(s=>()=>runner(s)),config.concurrency);let records=[],markets=[],predictions=[];const statuses=[];for(let i=0;i<this.sources.length;i++){const s=this.sources[i],r=results[i];if(!r?.ok){statuses.push(status(s,'error',{checkedAt:new Date().toISOString(),durationMs:r?.durationMs||null,error:safeError(r?.error),itemCount:0}));continue;}const v=r.value||{},count=(v.records?.length||0)+(v.markets?.length||0)+(v.predictions?.length||0);statuses.push(status(s,count?'ok':'ok-empty',{checkedAt:new Date().toISOString(),durationMs:r.durationMs,itemCount:count,error:null}));records.push(...(v.records||[]));markets.push(...(v.markets||[]));predictions.push(...(v.predictions||[]));}
  // Retain recent last-known-good LIVE records if a publisher temporarily fails.
  const prev=this.snapshot;for(const r of prev?.records||[]){if(r.fallback)continue;if(Date.parse(r.publishedAt||0)<Date.now()-96*36e5)continue;if(!records.some(x=>x.url===r.url))records.push({...r,retainedLastKnownGood:true});}
  for(const m of prev?.markets||[]){if(m.fallback)continue;if(Date.parse(m.updatedAt||0)<Date.now()-18*36e5)continue;if(!markets.some(x=>String(x.symbol).toUpperCase()===String(m.symbol).toUpperCase()))markets.push({...m,stale:true});}
  const cutoff=Date.now()-config.currentWindowHours*36e5;const recentLive=records.filter(r=>Date.parse(r.publishedAt||0)>=cutoff);if(recentLive.length<14){for(const r of this.seed.records){if(records.some(x=>x.url===r.url))continue;records.push({...r,fallback:true,staleFallback:Date.parse(r.publishedAt||0)<cutoff,sourceId:`build:${r.sourceDomain}`});}}
  const symbols=new Set(markets.map(m=>String(m.symbol).toUpperCase()));for(const m of this.seed.markets)if(!symbols.has(String(m.symbol).toUpperCase()))markets.push({...m,fallback:true});
  const next=buildSnapshot({records,markets,predictions,sourceStatuses:statuses,countries:this.countries,reference:this.reference,seedMeta:{capturedAt:this.seed.capturedAt,notice:this.seed.notice}});next.refreshReason=reason;next.refreshDurationMs=Date.now()-started;this.snapshot=next;await saveStored(next).catch(()=>{});return next;}
 country(iso2){const code=String(iso2||'').toUpperCase(),country=this.countries.find(c=>c.iso2===code);if(!country)return null;const signals=this.snapshot.signals.filter(s=>s.countryIso2===code||distanceKm(country.lat,country.lon,s.lat,s.lon)<700).slice(0,30);return{country,signals,risk:this.snapshot.countryRisk.find(x=>x.iso2===code)||{score:12,signals:0,high:0,categories:{}},neighbours:(country.borders||[]).map(iso3=>this.countries.find(c=>c.iso3===iso3)).filter(Boolean).map(c=>({iso2:c.iso2,name:c.name}))};}
}
function mergeStoredWithSeed(stored,seed){const isFresh=Date.parse(stored.generatedAt||0)>Date.now()-6*36e5;if(!isFresh)return seed;return stored;}
function status(s,st,extra={}){return{id:s.id,name:s.name,kind:s.kind,lane:s.lane,region:s.region,status:st,...extra};}
function safeError(e){return String(e?.message||e||'source_failed').slice(0,160);}
function distanceKm(a,b,c,d){const r=6371,p=x=>x*Math.PI/180;const x=p(c-a),y=p(d-b);const h=Math.sin(x/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(y/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)));}
