const gdelt=(id,name,query,region='world')=>({id,name,kind:'gdelt',lane:'discovery',region,query});
const rss=(id,name,url,lane='reporting',region='world')=>({id,name,kind:'rss',lane,region,url});
const json=(id,name,url,adapter,lane='official',region='world')=>({id,name,kind:'json',lane,region,url,adapter});
const market=(id,name,url,adapter,symbol,type='market')=>({id,name,kind:'market',lane:'markets',region:'world',url,adapter,symbol,type});
export const SOURCES=Object.freeze([
 gdelt('gdelt-me-security','GDELT · Middle East security','(Iran OR Israel OR Gulf OR Lebanon OR Yemen) (strike OR attack OR ceasefire OR missile OR drone OR military OR sanctions)','middle-east'),
 gdelt('gdelt-hormuz-redsea','GDELT · Hormuz / Red Sea shipping','("Strait of Hormuz" OR "Red Sea" OR "Bab el Mandeb") (ship OR tanker OR vessel OR shipping OR blockade OR attack OR insurance)','middle-east'),
 gdelt('gdelt-me-energy','GDELT · Middle East energy','(Iran OR Gulf OR Saudi OR UAE OR Qatar) (oil OR gas OR LNG OR refinery OR pipeline OR terminal) (disruption OR attack OR outage OR export)','middle-east'),
 gdelt('gdelt-europe-war','GDELT · Europe / Ukraine security','(Ukraine OR Russia OR NATO OR Black Sea) (missile OR drone OR attack OR mobilisation OR offensive OR airspace OR port)','europe'),
 gdelt('gdelt-russia-sanctions','GDELT · Russia sanctions / economy','Russia (sanctions OR export controls OR refinery OR oil OR gas OR rouble OR defense production)','russia-eurasia'),
 gdelt('gdelt-taiwan-security','GDELT · Taiwan security','Taiwan (China OR PLA OR blockade OR drill OR missile OR aircraft OR navy OR invasion OR cyber)','strategic-asia'),
 gdelt('gdelt-china-tech-trade','GDELT · China trade / technology','China (semiconductor OR export control OR tariff OR rare earth OR AI chip OR trade restriction)','strategic-asia'),
 gdelt('gdelt-japan-korea','GDELT · Japan / Korea','(Japan OR South Korea OR North Korea) (missile OR BOJ OR yen OR sanctions OR defense OR trade)','strategic-asia'),
 gdelt('gdelt-us-policy-markets','GDELT · US policy / markets','United States (Federal Reserve OR tariff OR sanctions OR export controls OR Treasury OR inflation OR defense)','north-america'),
 gdelt('gdelt-global-cyber','GDELT · Critical cyber','(cyberattack OR ransomware OR "critical infrastructure" OR subsea cable OR GPS interference) (government OR energy OR port OR telecom OR finance)','world'),
 gdelt('gdelt-global-energy','GDELT · Energy disruption','(oil OR gas OR LNG OR refinery OR pipeline OR power grid) (shutdown OR disruption OR strike OR outage OR sanctions)','world'),
 gdelt('gdelt-global-shipping','GDELT · Shipping disruption','(port OR shipping OR tanker OR container OR canal OR chokepoint) (closure OR strike OR attack OR congestion OR reroute OR disruption)','world'),
 gdelt('gdelt-nuclear-watch','GDELT · Nuclear / safeguards','(IAEA OR enrichment OR uranium OR centrifuge OR nuclear facility OR inspectors) (Iran OR Russia OR North Korea OR Ukraine OR China)','world'),
 gdelt('gdelt-sanctions-enforcement','GDELT · Sanctions / enforcement','(sanctions OR OFAC OR designation OR asset freeze OR secondary sanctions OR export controls) (Russia OR Iran OR China OR North Korea)','world'),
 gdelt('gdelt-black-sea','GDELT · Black Sea shipping','(Black Sea OR Odesa OR Odessa OR Novorossiysk OR Bosphorus) (port OR shipping OR tanker OR grain OR attack OR closure)','europe'),
 gdelt('gdelt-nato-defense','GDELT · NATO / European defence','(NATO OR European defence OR rearmament) (deployment OR exercise OR air defence OR troops OR procurement OR readiness)','europe'),
 gdelt('gdelt-baltic-infrastructure','GDELT · Baltic infrastructure','(Baltic Sea OR Finland OR Estonia OR Sweden OR Denmark) (subsea cable OR pipeline OR GPS interference OR sabotage OR telecom cable)','europe'),
 gdelt('gdelt-russia-energy','GDELT · Russia energy infrastructure','Russia (refinery OR pipeline OR oil terminal OR gas plant OR fuel shortage) (attack OR outage OR shutdown OR sanction OR repair)','russia-eurasia'),
 gdelt('gdelt-me-airspace','GDELT · Middle East airspace / aviation','(Iran OR Israel OR Iraq OR Gulf OR Jordan OR Lebanon) (airspace OR NOTAM OR flight suspension OR airline OR airport) (closure OR cancel OR reopen OR attack)','middle-east'),
 gdelt('gdelt-gulf-lng','GDELT · Gulf LNG / gas','(Qatar OR UAE OR Saudi OR Oman OR Gulf) (LNG OR gas export OR liquefaction OR terminal) (outage OR disruption OR shipping OR attack)','middle-east'),
 gdelt('gdelt-taiwan-semiconductors','GDELT · Taiwan semiconductors','(Taiwan OR TSMC) (semiconductor OR chip OR fab OR export control OR blockade OR power outage OR supply chain)','strategic-asia'),
 gdelt('gdelt-south-china-sea','GDELT · South China Sea','(South China Sea OR Philippines OR Scarborough OR Spratly) (China OR coast guard OR collision OR water cannon OR blockade OR vessel)','strategic-asia'),
 gdelt('gdelt-north-korea','GDELT · North Korea security','(North Korea OR DPRK) (missile OR nuclear OR artillery OR DMZ OR sanctions OR military exercise)','strategic-asia'),
 gdelt('gdelt-critical-minerals','GDELT · Critical minerals / export controls','(rare earth OR gallium OR germanium OR graphite OR critical minerals) (China OR export control OR restriction OR ban OR supply)','strategic-asia'),
 rss('rss-bbc-world','BBC World','https://feeds.bbci.co.uk/news/world/rss.xml','reporting'),
 rss('rss-bbc-business','BBC Business','https://feeds.bbci.co.uk/news/business/rss.xml','reporting'),
 rss('rss-un-news','UN News','https://news.un.org/feed/subscribe/en/news/all/rss.xml','official'),
 rss('rss-ecb-press','ECB Press','https://www.ecb.europa.eu/rss/press.html','official','europe'),
 rss('rss-fed','Federal Reserve','https://www.federalreserve.gov/feeds/press_all.xml','official','north-america'),
 rss('rss-dw-world','Deutsche Welle','https://rss.dw.com/rdf/rss-en-all','reporting'),
 rss('rss-nato','NATO News','https://www.nato.int/cps/en/natohq/news_rss.htm','official','europe'),
 json('json-usgs-significant','USGS Significant Earthquakes','https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson','usgs','hazards'),
 json('json-cisa-kev','CISA Known Exploited Vulnerabilities','https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json','cisa','cyber'),
 json('json-nasa-eonet','NASA EONET','https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=50','eonet','hazards'),
 json('json-polymarket','Polymarket public events','https://gamma-api.polymarket.com/events?active=true&closed=false&limit=100','polymarket','prediction'),
 market('mkt-btc','Coinbase BTC/USD','https://api.exchange.coinbase.com/products/BTC-USD/stats','coinbase','BTC/USD','crypto'),
 market('mkt-eth','Coinbase ETH/USD','https://api.exchange.coinbase.com/products/ETH-USD/stats','coinbase','ETH/USD','crypto'),
 market('mkt-sol','Coinbase SOL/USD','https://api.exchange.coinbase.com/products/SOL-USD/stats','coinbase','SOL/USD','crypto'),
 market('mkt-spy','Stooq S&P 500 proxy','https://stooq.com/q/l/?s=spy.us&f=sd2t2ohlcv&h&e=csv','stooq','SPY','equity'),
 market('mkt-qqq','Stooq Nasdaq proxy','https://stooq.com/q/l/?s=qqq.us&f=sd2t2ohlcv&h&e=csv','stooq','QQQ','equity'),
 market('mkt-gold','Stooq Gold ETF','https://stooq.com/q/l/?s=gld.us&f=sd2t2ohlcv&h&e=csv','stooq','GLD','commodity'),
 market('mkt-oil','Stooq Oil ETF','https://stooq.com/q/l/?s=uso.us&f=sd2t2ohlcv&h&e=csv','stooq','USO','commodity'),
 market('mkt-eurusd','Stooq EUR/USD','https://stooq.com/q/l/?s=eurusd&f=sd2t2ohlcv&h&e=csv','stooq','EUR/USD','fx'),
 market('mkt-usdjpy','Stooq USD/JPY','https://stooq.com/q/l/?s=usdjpy&f=sd2t2ohlcv&h&e=csv','stooq','USD/JPY','fx')
]);
